// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type QuizcraftBank struct {
	ID               uuid.UUID          `json:"id"`
	BankKey          string             `json:"bank_key"`
	Name             string             `json:"name"`
	ActiveVersionID  uuid.NullUUID      `json:"active_version_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LifecycleVersion int64              `json:"lifecycle_version"`
}

type QuizcraftBankVersion struct {
	ID            uuid.UUID          `json:"id"`
	BankID        uuid.UUID          `json:"bank_id"`
	Name          string             `json:"name"`
	SourceVersion string             `json:"source_version"`
	SourceSha256  string             `json:"source_sha256"`
	ContentSha256 string             `json:"content_sha256"`
	ImportReport  []byte             `json:"import_report"`
	ImportedAt    pgtype.Timestamptz `json:"imported_at"`
	SealedAt      pgtype.Timestamptz `json:"sealed_at"`
}

type QuizcraftBankVersionQuestion struct {
	BankID            uuid.UUID `json:"bank_id"`
	BankVersionID     uuid.UUID `json:"bank_version_id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Position          int32     `json:"position"`
}

type QuizcraftFavorite struct {
	UserID     uuid.UUID          `json:"user_id"`
	BankID     uuid.UUID          `json:"bank_id"`
	QuestionID uuid.UUID          `json:"question_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftFeedback struct {
	ID                uuid.UUID          `json:"id"`
	BankID            uuid.UUID          `json:"bank_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	QuestionVersionID uuid.UUID          `json:"question_version_id"`
	ActorUserID       uuid.NullUUID      `json:"actor_user_id"`
	ActorKey          string             `json:"actor_key"`
	Category          string             `json:"category"`
	Detail            string             `json:"detail"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftFeedbackInboxOutbox struct {
	ID                 uuid.UUID          `json:"id"`
	FeedbackID         uuid.UUID          `json:"feedback_id"`
	SourceProductCode  string             `json:"source_product_code"`
	SourceResourceType string             `json:"source_resource_type"`
	SourceResourceID   string             `json:"source_resource_id"`
	SourceResourceUrl  string             `json:"source_resource_url"`
	Category           string             `json:"category"`
	Priority           string             `json:"priority"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftIdempotencyResult struct {
	ActorKey       string             `json:"actor_key"`
	OperationKind  string             `json:"operation_kind"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestSha256  string             `json:"request_sha256"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   string             `json:"response_body"`
	ResourceID     uuid.NullUUID      `json:"resource_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftLearningState struct {
	UserID            uuid.UUID          `json:"user_id"`
	BankID            uuid.UUID          `json:"bank_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	QuestionVersionID uuid.UUID          `json:"question_version_id"`
	Wrong             bool               `json:"wrong"`
	AttemptCount      int64              `json:"attempt_count"`
	CorrectCount      int64              `json:"correct_count"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type QuizcraftPracticeAttempt struct {
	ID                uuid.UUID          `json:"id"`
	SessionID         uuid.UUID          `json:"session_id"`
	BankID            uuid.UUID          `json:"bank_id"`
	BankVersionID     uuid.UUID          `json:"bank_version_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	QuestionVersionID uuid.UUID          `json:"question_version_id"`
	UserID            uuid.NullUUID      `json:"user_id"`
	SubmittedAnswer   []byte             `json:"submitted_answer"`
	Correct           bool               `json:"correct"`
	ExpectedAnswer    []byte             `json:"expected_answer"`
	Analysis          string             `json:"analysis"`
	ResponseBody      string             `json:"response_body"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
}

type QuizcraftPracticeSession struct {
	ID            uuid.UUID          `json:"id"`
	BankID        uuid.UUID          `json:"bank_id"`
	BankVersionID uuid.UUID          `json:"bank_version_id"`
	UserID        uuid.NullUUID      `json:"user_id"`
	ActorKey      string             `json:"actor_key"`
	Mode          string             `json:"mode"`
	ChapterID     pgtype.Text        `json:"chapter_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftPracticeSessionClaim struct {
	SessionID     uuid.UUID          `json:"session_id"`
	GuestActorKey string             `json:"guest_actor_key"`
	UserID        uuid.UUID          `json:"user_id"`
	UserActorKey  string             `json:"user_actor_key"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
}

type QuizcraftPracticeSessionQuestion struct {
	SessionID         uuid.UUID `json:"session_id"`
	BankID            uuid.UUID `json:"bank_id"`
	BankVersionID     uuid.UUID `json:"bank_version_id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Position          int32     `json:"position"`
}

type QuizcraftQuestion struct {
	ID               uuid.UUID          `json:"id"`
	BankID           uuid.UUID          `json:"bank_id"`
	SourceQuestionID string             `json:"source_question_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftQuestionStat struct {
	QuestionID   uuid.UUID          `json:"question_id"`
	AttemptCount int64              `json:"attempt_count"`
	CorrectCount int64              `json:"correct_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type QuizcraftQuestionVersion struct {
	ID            uuid.UUID          `json:"id"`
	BankID        uuid.UUID          `json:"bank_id"`
	QuestionID    uuid.UUID          `json:"question_id"`
	Type          string             `json:"type"`
	ChapterID     string             `json:"chapter_id"`
	ChapterName   string             `json:"chapter_name"`
	Content       string             `json:"content"`
	Options       []byte             `json:"options"`
	Answer        []byte             `json:"answer"`
	Analysis      string             `json:"analysis"`
	ContentSha256 string             `json:"content_sha256"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftRankingProfile struct {
	UserID       uuid.UUID          `json:"user_id"`
	Nickname     string             `json:"nickname"`
	SystemAvatar string             `json:"system_avatar"`
	Visible      bool               `json:"visible"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type QuizcraftRankingSettlementEvent struct {
	ID          uuid.UUID          `json:"id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	Scope       string             `json:"scope"`
	BankID      uuid.NullUUID      `json:"bank_id"`
	Metric      string             `json:"metric"`
	Standings   []byte             `json:"standings"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftShadowComparison struct {
	ID             uuid.UUID          `json:"id"`
	SessionID      uuid.UUID          `json:"session_id"`
	QuestionID     uuid.UUID          `json:"question_id"`
	NewResponse    []byte             `json:"new_response"`
	LegacyResponse []byte             `json:"legacy_response"`
	Outcome        string             `json:"outcome"`
	Detail         string             `json:"detail"`
	ComparedAt     pgtype.Timestamptz `json:"compared_at"`
}

type QuizcraftWorkshopAuditEvent struct {
	ID               uuid.UUID          `json:"id"`
	ActorUserID      uuid.UUID          `json:"actor_user_id"`
	PermissionCode   string             `json:"permission_code"`
	Action           string             `json:"action"`
	BankID           uuid.UUID          `json:"bank_id"`
	BankVersionID    uuid.NullUUID      `json:"bank_version_id"`
	ExpectedVersion  int64              `json:"expected_version"`
	ResultingVersion int64              `json:"resulting_version"`
	RequestID        string             `json:"request_id"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftWorkshopVersionState struct {
	BankID         uuid.UUID          `json:"bank_id"`
	BankVersionID  uuid.UUID          `json:"bank_version_id"`
	State          string             `json:"state"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	ValidatedBy    uuid.NullUUID      `json:"validated_by"`
	ValidationNote string             `json:"validation_note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ValidatedAt    pgtype.Timestamptz `json:"validated_at"`
}
