// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: practice.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO quizcraft_favorites(user_id,bank_id,question_id)
VALUES($1,$2,$3)
ON CONFLICT(user_id,bank_id,question_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BankID     uuid.UUID `json:"bank_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.BankID, arg.QuestionID)
	return err
}

const addPracticeSessionQuestion = `-- name: AddPracticeSessionQuestion :exec
INSERT INTO quizcraft_practice_session_questions(session_id,bank_id,bank_version_id,question_id,question_version_id,position)
VALUES($1,$2,$3,$4,$5,$6)
`

type AddPracticeSessionQuestionParams struct {
	SessionID         uuid.UUID `json:"session_id"`
	BankID            uuid.UUID `json:"bank_id"`
	BankVersionID     uuid.UUID `json:"bank_version_id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Position          int32     `json:"position"`
}

func (q *Queries) AddPracticeSessionQuestion(ctx context.Context, arg AddPracticeSessionQuestionParams) error {
	_, err := q.db.Exec(ctx, addPracticeSessionQuestion,
		arg.SessionID,
		arg.BankID,
		arg.BankVersionID,
		arg.QuestionID,
		arg.QuestionVersionID,
		arg.Position,
	)
	return err
}

const claimGuestPracticeSession = `-- name: ClaimGuestPracticeSession :execrows
INSERT INTO quizcraft_practice_session_claims(session_id,guest_actor_key,user_id,user_actor_key)
SELECT id,$2,$3,$4
FROM quizcraft_practice_sessions
WHERE id=$1 AND user_id IS NULL AND actor_key=$2
ON CONFLICT(session_id) DO NOTHING
`

type ClaimGuestPracticeSessionParams struct {
	ID            uuid.UUID `json:"id"`
	GuestActorKey string    `json:"guest_actor_key"`
	UserID        uuid.UUID `json:"user_id"`
	UserActorKey  string    `json:"user_actor_key"`
}

func (q *Queries) ClaimGuestPracticeSession(ctx context.Context, arg ClaimGuestPracticeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimGuestPracticeSession,
		arg.ID,
		arg.GuestActorKey,
		arg.UserID,
		arg.UserActorKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearLearningState = `-- name: ClearLearningState :exec
DELETE FROM quizcraft_learning_state
`

func (q *Queries) ClearLearningState(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearLearningState)
	return err
}

const countFavoritesForBank = `-- name: CountFavoritesForBank :one
SELECT count(*)::bigint
FROM quizcraft_favorites
WHERE user_id=$1 AND bank_id=$2
`

type CountFavoritesForBankParams struct {
	UserID uuid.UUID `json:"user_id"`
	BankID uuid.UUID `json:"bank_id"`
}

func (q *Queries) CountFavoritesForBank(ctx context.Context, arg CountFavoritesForBankParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritesForBank, arg.UserID, arg.BankID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPracticeAttempt = `-- name: CreatePracticeAttempt :one
INSERT INTO quizcraft_practice_attempts(id,session_id,bank_id,bank_version_id,question_id,question_version_id,user_id,submitted_answer,correct,expected_answer,analysis,response_body)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING submitted_at
`

type CreatePracticeAttemptParams struct {
	ID                uuid.UUID     `json:"id"`
	SessionID         uuid.UUID     `json:"session_id"`
	BankID            uuid.UUID     `json:"bank_id"`
	BankVersionID     uuid.UUID     `json:"bank_version_id"`
	QuestionID        uuid.UUID     `json:"question_id"`
	QuestionVersionID uuid.UUID     `json:"question_version_id"`
	UserID            uuid.NullUUID `json:"user_id"`
	SubmittedAnswer   []byte        `json:"submitted_answer"`
	Correct           bool          `json:"correct"`
	ExpectedAnswer    []byte        `json:"expected_answer"`
	Analysis          string        `json:"analysis"`
	ResponseBody      string        `json:"response_body"`
}

func (q *Queries) CreatePracticeAttempt(ctx context.Context, arg CreatePracticeAttemptParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createPracticeAttempt,
		arg.ID,
		arg.SessionID,
		arg.BankID,
		arg.BankVersionID,
		arg.QuestionID,
		arg.QuestionVersionID,
		arg.UserID,
		arg.SubmittedAnswer,
		arg.Correct,
		arg.ExpectedAnswer,
		arg.Analysis,
		arg.ResponseBody,
	)
	var submitted_at pgtype.Timestamptz
	err := row.Scan(&submitted_at)
	return submitted_at, err
}

const createPracticeSession = `-- name: CreatePracticeSession :exec
INSERT INTO quizcraft_practice_sessions(id,bank_id,bank_version_id,user_id,actor_key,mode,chapter_id)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type CreatePracticeSessionParams struct {
	ID            uuid.UUID     `json:"id"`
	BankID        uuid.UUID     `json:"bank_id"`
	BankVersionID uuid.UUID     `json:"bank_version_id"`
	UserID        uuid.NullUUID `json:"user_id"`
	ActorKey      string        `json:"actor_key"`
	Mode          string        `json:"mode"`
	ChapterID     pgtype.Text   `json:"chapter_id"`
}

func (q *Queries) CreatePracticeSession(ctx context.Context, arg CreatePracticeSessionParams) error {
	_, err := q.db.Exec(ctx, createPracticeSession,
		arg.ID,
		arg.BankID,
		arg.BankVersionID,
		arg.UserID,
		arg.ActorKey,
		arg.Mode,
		arg.ChapterID,
	)
	return err
}

const createRankingSettlementEvent = `-- name: CreateRankingSettlementEvent :execrows
INSERT INTO quizcraft_ranking_settlement_events(id,period_start,period_end,scope,bank_id,metric,standings)
VALUES($1,$2,$3,$4,$5,'correct_answer_count',$6)
ON CONFLICT(period_start,period_end,scope,bank_id) DO NOTHING
`

type CreateRankingSettlementEventParams struct {
	ID          uuid.UUID          `json:"id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	Scope       string             `json:"scope"`
	BankID      uuid.NullUUID      `json:"bank_id"`
	Standings   []byte             `json:"standings"`
}

func (q *Queries) CreateRankingSettlementEvent(ctx context.Context, arg CreateRankingSettlementEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createRankingSettlementEvent,
		arg.ID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Scope,
		arg.BankID,
		arg.Standings,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveBankVersion = `-- name: GetActiveBankVersion :one
SELECT bv.id
FROM quizcraft_banks b
JOIN quizcraft_bank_versions bv ON bv.id=b.active_version_id AND bv.bank_id=b.id AND bv.sealed_at IS NOT NULL
WHERE b.id=$1
`

func (q *Queries) GetActiveBankVersion(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveBankVersion, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getIdempotencyResult = `-- name: GetIdempotencyResult :one
SELECT request_sha256,response_status,response_body
FROM quizcraft_idempotency_results
WHERE actor_key=$1 AND operation_kind=$2 AND idempotency_key=$3
`

type GetIdempotencyResultParams struct {
	ActorKey       string `json:"actor_key"`
	OperationKind  string `json:"operation_kind"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetIdempotencyResultRow struct {
	RequestSha256  string `json:"request_sha256"`
	ResponseStatus int32  `json:"response_status"`
	ResponseBody   string `json:"response_body"`
}

func (q *Queries) GetIdempotencyResult(ctx context.Context, arg GetIdempotencyResultParams) (GetIdempotencyResultRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyResult, arg.ActorKey, arg.OperationKind, arg.IdempotencyKey)
	var i GetIdempotencyResultRow
	err := row.Scan(&i.RequestSha256, &i.ResponseStatus, &i.ResponseBody)
	return i, err
}

const getLearningStateReconciliation = `-- name: GetLearningStateReconciliation :one
WITH aggregates AS (
  SELECT user_id,bank_id,question_id,
         count(*)::bigint AS attempt_count,
         count(*) FILTER (WHERE correct)::bigint AS correct_count,
         max(submitted_at) AS updated_at
  FROM quizcraft_practice_attempts
  WHERE user_id IS NOT NULL
  GROUP BY user_id,bank_id,question_id
),
latest AS (
  SELECT DISTINCT ON (user_id,bank_id,question_id)
         user_id,bank_id,question_id,id AS latest_attempt_id,question_version_id,(NOT correct) AS wrong
  FROM quizcraft_practice_attempts
  WHERE user_id IS NOT NULL
  ORDER BY user_id,bank_id,question_id,submitted_at DESC,id DESC
),
expected AS (
  SELECT aggregates.user_id,aggregates.bank_id,aggregates.question_id,latest.latest_attempt_id,
         latest.question_version_id,latest.wrong,aggregates.attempt_count,
         aggregates.correct_count,aggregates.updated_at
  FROM aggregates
  JOIN latest USING (user_id,bank_id,question_id)
),
compared AS (
  SELECT expected.user_id AS expected_user_id,
         actual.user_id AS actual_user_id,
         expected.latest_attempt_id AS expected_latest_attempt_id,
         actual.latest_attempt_id AS actual_latest_attempt_id,
         expected.question_version_id AS expected_question_version_id,
         actual.question_version_id AS actual_question_version_id,
         expected.wrong AS expected_wrong,actual.wrong AS actual_wrong,
         expected.attempt_count AS expected_attempt_count,actual.attempt_count AS actual_attempt_count,
         expected.correct_count AS expected_correct_count,actual.correct_count AS actual_correct_count,
         expected.updated_at AS expected_updated_at,actual.updated_at AS actual_updated_at
  FROM expected
  FULL OUTER JOIN quizcraft_learning_state actual
    ON actual.user_id=expected.user_id AND actual.bank_id=expected.bank_id AND actual.question_id=expected.question_id
)
SELECT count(*) FILTER (WHERE expected_user_id IS NOT NULL AND actual_user_id IS NULL)::bigint AS missing_rows,
       count(*) FILTER (WHERE expected_user_id IS NULL AND actual_user_id IS NOT NULL)::bigint AS extra_rows,
       count(*) FILTER (WHERE expected_user_id IS NOT NULL AND actual_user_id IS NOT NULL AND
         (expected_latest_attempt_id IS DISTINCT FROM actual_latest_attempt_id OR
          expected_question_version_id IS DISTINCT FROM actual_question_version_id OR
          expected_wrong IS DISTINCT FROM actual_wrong OR
          expected_attempt_count IS DISTINCT FROM actual_attempt_count OR
          expected_correct_count IS DISTINCT FROM actual_correct_count OR
          expected_updated_at IS DISTINCT FROM actual_updated_at))::bigint AS mismatched_rows
FROM compared
`

type GetLearningStateReconciliationRow struct {
	MissingRows    int64 `json:"missing_rows"`
	ExtraRows      int64 `json:"extra_rows"`
	MismatchedRows int64 `json:"mismatched_rows"`
}

func (q *Queries) GetLearningStateReconciliation(ctx context.Context) (GetLearningStateReconciliationRow, error) {
	row := q.db.QueryRow(ctx, getLearningStateReconciliation)
	var i GetLearningStateReconciliationRow
	err := row.Scan(&i.MissingRows, &i.ExtraRows, &i.MismatchedRows)
	return i, err
}

const getOperationResult = `-- name: GetOperationResult :one
SELECT resource_id, response_body
FROM quizcraft_idempotency_results
WHERE actor_key = $1 AND operation_kind = $2 AND idempotency_key = $3
`

type GetOperationResultParams struct {
	ActorKey       string `json:"actor_key"`
	OperationKind  string `json:"operation_kind"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetOperationResultRow struct {
	ResourceID   uuid.NullUUID `json:"resource_id"`
	ResponseBody string        `json:"response_body"`
}

func (q *Queries) GetOperationResult(ctx context.Context, arg GetOperationResultParams) (GetOperationResultRow, error) {
	row := q.db.QueryRow(ctx, getOperationResult, arg.ActorKey, arg.OperationKind, arg.IdempotencyKey)
	var i GetOperationResultRow
	err := row.Scan(&i.ResourceID, &i.ResponseBody)
	return i, err
}

const getPersonalPracticeTotals = `-- name: GetPersonalPracticeTotals :one
SELECT count(*)::bigint AS total_answers,
       count(*) FILTER (WHERE correct)::bigint AS correct_answers
FROM quizcraft_practice_attempts
WHERE user_id=$1
`

type GetPersonalPracticeTotalsRow struct {
	TotalAnswers   int64 `json:"total_answers"`
	CorrectAnswers int64 `json:"correct_answers"`
}

func (q *Queries) GetPersonalPracticeTotals(ctx context.Context, userID uuid.NullUUID) (GetPersonalPracticeTotalsRow, error) {
	row := q.db.QueryRow(ctx, getPersonalPracticeTotals, userID)
	var i GetPersonalPracticeTotalsRow
	err := row.Scan(&i.TotalAnswers, &i.CorrectAnswers)
	return i, err
}

const getPracticeAttemptResponse = `-- name: GetPracticeAttemptResponse :one
SELECT response_body
FROM quizcraft_practice_attempts
WHERE session_id=$1 AND question_id=$2
`

type GetPracticeAttemptResponseParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetPracticeAttemptResponse(ctx context.Context, arg GetPracticeAttemptResponseParams) (string, error) {
	row := q.db.QueryRow(ctx, getPracticeAttemptResponse, arg.SessionID, arg.QuestionID)
	var response_body string
	err := row.Scan(&response_body)
	return response_body, err
}

const getPracticeSessionActor = `-- name: GetPracticeSessionActor :one
SELECT COALESCE(c.user_actor_key,s.actor_key) AS actor_key
FROM quizcraft_practice_sessions s
LEFT JOIN quizcraft_practice_session_claims c ON c.session_id=s.id
WHERE s.id=$1
`

func (q *Queries) GetPracticeSessionActor(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPracticeSessionActor, id)
	var actor_key string
	err := row.Scan(&actor_key)
	return actor_key, err
}

const getSessionQuestion = `-- name: GetSessionQuestion :one
SELECT s.bank_id,s.bank_version_id,COALESCE(c.user_id,s.user_id) AS user_id,COALESCE(c.user_actor_key,s.actor_key) AS actor_key,qv.type,qv.answer,COALESCE(qv.options,'null'::jsonb) AS options,qv.analysis,b.bank_key,q.source_question_id
FROM quizcraft_practice_sessions s
JOIN quizcraft_practice_session_questions sq ON sq.session_id=s.id
JOIN quizcraft_question_versions qv ON qv.id=sq.question_version_id AND qv.question_id=sq.question_id
JOIN quizcraft_questions q ON q.id=sq.question_id
JOIN quizcraft_banks b ON b.id=s.bank_id
LEFT JOIN quizcraft_practice_session_claims c ON c.session_id=s.id
WHERE s.id=$1 AND sq.question_id=$2 AND sq.question_version_id=$3
`

type GetSessionQuestionParams struct {
	ID                uuid.UUID `json:"id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
}

type GetSessionQuestionRow struct {
	BankID           uuid.UUID `json:"bank_id"`
	BankVersionID    uuid.UUID `json:"bank_version_id"`
	UserID           uuid.UUID `json:"user_id"`
	ActorKey         string    `json:"actor_key"`
	Type             string    `json:"type"`
	Answer           []byte    `json:"answer"`
	Options          []byte    `json:"options"`
	Analysis         string    `json:"analysis"`
	BankKey          string    `json:"bank_key"`
	SourceQuestionID string    `json:"source_question_id"`
}

func (q *Queries) GetSessionQuestion(ctx context.Context, arg GetSessionQuestionParams) (GetSessionQuestionRow, error) {
	row := q.db.QueryRow(ctx, getSessionQuestion, arg.ID, arg.QuestionID, arg.QuestionVersionID)
	var i GetSessionQuestionRow
	err := row.Scan(
		&i.BankID,
		&i.BankVersionID,
		&i.UserID,
		&i.ActorKey,
		&i.Type,
		&i.Answer,
		&i.Options,
		&i.Analysis,
		&i.BankKey,
		&i.SourceQuestionID,
	)
	return i, err
}

const insertShadowComparison = `-- name: InsertShadowComparison :exec
INSERT INTO quizcraft_shadow_comparisons(id,session_id,question_id,new_response,legacy_response,outcome,detail)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertShadowComparisonParams struct {
	ID             uuid.UUID `json:"id"`
	SessionID      uuid.UUID `json:"session_id"`
	QuestionID     uuid.UUID `json:"question_id"`
	NewResponse    []byte    `json:"new_response"`
	LegacyResponse []byte    `json:"legacy_response"`
	Outcome        string    `json:"outcome"`
	Detail         string    `json:"detail"`
}

func (q *Queries) InsertShadowComparison(ctx context.Context, arg InsertShadowComparisonParams) error {
	_, err := q.db.Exec(ctx, insertShadowComparison,
		arg.ID,
		arg.SessionID,
		arg.QuestionID,
		arg.NewResponse,
		arg.LegacyResponse,
		arg.Outcome,
		arg.Detail,
	)
	return err
}

const isPublishedBankVersion = `-- name: IsPublishedBankVersion :one
SELECT true AS published
FROM quizcraft_banks b
JOIN quizcraft_bank_versions bv ON bv.id=$2 AND bv.bank_id=b.id
WHERE b.id=$1 AND b.active_version_id=$2 AND bv.sealed_at IS NOT NULL
`

type IsPublishedBankVersionParams struct {
	ID   uuid.UUID `json:"id"`
	ID_2 uuid.UUID `json:"id_2"`
}

func (q *Queries) IsPublishedBankVersion(ctx context.Context, arg IsPublishedBankVersionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPublishedBankVersion, arg.ID, arg.ID_2)
	var published bool
	err := row.Scan(&published)
	return published, err
}

const isQuestionInBank = `-- name: IsQuestionInBank :one
SELECT true AS exists
FROM quizcraft_questions
WHERE bank_id=$1 AND id=$2
`

type IsQuestionInBankParams struct {
	BankID uuid.UUID `json:"bank_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) IsQuestionInBank(ctx context.Context, arg IsQuestionInBankParams) (bool, error) {
	row := q.db.QueryRow(ctx, isQuestionInBank, arg.BankID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBankRanking = `-- name: ListBankRanking :many
WITH totals AS (
  SELECT COALESCE(a.user_id::text,s.actor_key) AS identity_key,
         a.user_id,
         count(*)::bigint AS correct_answer_count
  FROM quizcraft_practice_attempts a
  LEFT JOIN quizcraft_practice_sessions s ON s.id=a.session_id
  WHERE a.correct AND COALESCE(a.user_id::text,s.actor_key) IS NOT NULL AND a.bank_id=$1 AND a.submitted_at >= $2
  GROUP BY identity_key,a.user_id
)
SELECT rank() OVER (ORDER BY t.correct_answer_count DESC)::bigint AS rank, t.user_id,
       CASE WHEN t.user_id IS NULL THEN t.identity_key ELSE '' END AS guest_key,
       t.correct_answer_count
FROM totals t
ORDER BY t.correct_answer_count DESC, t.identity_key
LIMIT 100
`

type ListBankRankingParams struct {
	BankID      uuid.UUID          `json:"bank_id"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
}

type ListBankRankingRow struct {
	Rank               int64         `json:"rank"`
	UserID             uuid.NullUUID `json:"user_id"`
	GuestKey           string        `json:"guest_key"`
	CorrectAnswerCount int64         `json:"correct_answer_count"`
}

func (q *Queries) ListBankRanking(ctx context.Context, arg ListBankRankingParams) ([]ListBankRankingRow, error) {
	rows, err := q.db.Query(ctx, listBankRanking, arg.BankID, arg.SubmittedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankRankingRow{}
	for rows.Next() {
		var i ListBankRankingRow
		if err := rows.Scan(
			&i.Rank,
			&i.UserID,
			&i.GuestKey,
			&i.CorrectAnswerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankRankingWindow = `-- name: ListBankRankingWindow :many
WITH totals AS (
  SELECT COALESCE(a.user_id::text,s.actor_key) AS identity_key,
         a.user_id,
         count(*)::bigint AS correct_answer_count
  FROM quizcraft_practice_attempts a
  LEFT JOIN quizcraft_practice_sessions s ON s.id=a.session_id
  WHERE a.correct AND COALESCE(a.user_id::text,s.actor_key) IS NOT NULL AND a.bank_id=$1 AND a.submitted_at >= $2 AND a.submitted_at < $3
  GROUP BY identity_key,a.user_id
)
SELECT user_id,rank() OVER (ORDER BY correct_answer_count DESC)::bigint AS rank,correct_answer_count
FROM totals ORDER BY correct_answer_count DESC,identity_key LIMIT 100
`

type ListBankRankingWindowParams struct {
	BankID        uuid.UUID          `json:"bank_id"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	SubmittedAt_2 pgtype.Timestamptz `json:"submitted_at_2"`
}

type ListBankRankingWindowRow struct {
	UserID             uuid.NullUUID `json:"user_id"`
	Rank               int64         `json:"rank"`
	CorrectAnswerCount int64         `json:"correct_answer_count"`
}

func (q *Queries) ListBankRankingWindow(ctx context.Context, arg ListBankRankingWindowParams) ([]ListBankRankingWindowRow, error) {
	rows, err := q.db.Query(ctx, listBankRankingWindow, arg.BankID, arg.SubmittedAt, arg.SubmittedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankRankingWindowRow{}
	for rows.Next() {
		var i ListBankRankingWindowRow
		if err := rows.Scan(&i.UserID, &i.Rank, &i.CorrectAnswerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteFolders = `-- name: ListFavoriteFolders :many
SELECT f.bank_id,b.name AS bank_name,
       count(*) FILTER (WHERE m.question_id IS NOT NULL)::bigint AS available_count,
       count(*) FILTER (WHERE m.question_id IS NULL)::bigint AS unavailable_count
FROM quizcraft_favorites f
JOIN quizcraft_banks b ON b.id=f.bank_id
LEFT JOIN quizcraft_bank_version_questions m
  ON m.bank_id=f.bank_id AND m.question_id=f.question_id AND m.bank_version_id=b.active_version_id
WHERE f.user_id=$1
GROUP BY f.bank_id,b.name
ORDER BY b.name,f.bank_id
`

type ListFavoriteFoldersRow struct {
	BankID           uuid.UUID `json:"bank_id"`
	BankName         string    `json:"bank_name"`
	AvailableCount   int64     `json:"available_count"`
	UnavailableCount int64     `json:"unavailable_count"`
}

func (q *Queries) ListFavoriteFolders(ctx context.Context, userID uuid.UUID) ([]ListFavoriteFoldersRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteFolders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoriteFoldersRow{}
	for rows.Next() {
		var i ListFavoriteFoldersRow
		if err := rows.Scan(
			&i.BankID,
			&i.BankName,
			&i.AvailableCount,
			&i.UnavailableCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoritePracticeQuestions = `-- name: ListFavoritePracticeQuestions :many
SELECT m.question_id,m.question_version_id,qv.type,qv.chapter_id,qv.chapter_name,qv.content,COALESCE(qv.options,'null'::jsonb) AS options
FROM quizcraft_favorites f
JOIN quizcraft_bank_version_questions m
  ON m.bank_id=f.bank_id AND m.question_id=f.question_id AND m.bank_version_id=$1
JOIN quizcraft_question_versions qv
  ON qv.id=m.question_version_id AND qv.question_id=m.question_id AND qv.bank_id=m.bank_id
WHERE f.user_id=$2 AND f.bank_id=$3
ORDER BY f.created_at,f.question_id
`

type ListFavoritePracticeQuestionsParams struct {
	BankVersionID uuid.UUID `json:"bank_version_id"`
	UserID        uuid.UUID `json:"user_id"`
	BankID        uuid.UUID `json:"bank_id"`
}

type ListFavoritePracticeQuestionsRow struct {
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Type              string    `json:"type"`
	ChapterID         string    `json:"chapter_id"`
	ChapterName       string    `json:"chapter_name"`
	Content           string    `json:"content"`
	Options           []byte    `json:"options"`
}

func (q *Queries) ListFavoritePracticeQuestions(ctx context.Context, arg ListFavoritePracticeQuestionsParams) ([]ListFavoritePracticeQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listFavoritePracticeQuestions, arg.BankVersionID, arg.UserID, arg.BankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoritePracticeQuestionsRow{}
	for rows.Next() {
		var i ListFavoritePracticeQuestionsRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.QuestionVersionID,
			&i.Type,
			&i.ChapterID,
			&i.ChapterName,
			&i.Content,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteQuestions = `-- name: ListFavoriteQuestions :many
SELECT f.bank_id,f.question_id,m.question_version_id
FROM quizcraft_favorites f
JOIN quizcraft_banks b ON b.id=f.bank_id
LEFT JOIN quizcraft_bank_version_questions m
  ON m.bank_id=f.bank_id AND m.question_id=f.question_id AND m.bank_version_id=b.active_version_id
WHERE f.user_id=$1 AND f.bank_id=$2
ORDER BY f.created_at,f.question_id
`

type ListFavoriteQuestionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	BankID uuid.UUID `json:"bank_id"`
}

type ListFavoriteQuestionsRow struct {
	BankID            uuid.UUID     `json:"bank_id"`
	QuestionID        uuid.UUID     `json:"question_id"`
	QuestionVersionID uuid.NullUUID `json:"question_version_id"`
}

func (q *Queries) ListFavoriteQuestions(ctx context.Context, arg ListFavoriteQuestionsParams) ([]ListFavoriteQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteQuestions, arg.UserID, arg.BankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoriteQuestionsRow{}
	for rows.Next() {
		var i ListFavoriteQuestionsRow
		if err := rows.Scan(&i.BankID, &i.QuestionID, &i.QuestionVersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningState = `-- name: ListLearningState :many
SELECT bank_id,question_id,question_version_id,wrong,attempt_count,correct_count,updated_at
FROM quizcraft_learning_state
WHERE user_id=$1
ORDER BY updated_at DESC
`

type ListLearningStateRow struct {
	BankID            uuid.UUID          `json:"bank_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	QuestionVersionID uuid.UUID          `json:"question_version_id"`
	Wrong             bool               `json:"wrong"`
	AttemptCount      int64              `json:"attempt_count"`
	CorrectCount      int64              `json:"correct_count"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLearningState(ctx context.Context, userID uuid.UUID) ([]ListLearningStateRow, error) {
	rows, err := q.db.Query(ctx, listLearningState, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningStateRow{}
	for rows.Next() {
		var i ListLearningStateRow
		if err := rows.Scan(
			&i.BankID,
			&i.QuestionID,
			&i.QuestionVersionID,
			&i.Wrong,
			&i.AttemptCount,
			&i.CorrectCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverallRanking = `-- name: ListOverallRanking :many
WITH totals AS (
  SELECT COALESCE(a.user_id::text,s.actor_key) AS identity_key,
         a.user_id,
         count(*)::bigint AS correct_answer_count
  FROM quizcraft_practice_attempts a
  LEFT JOIN quizcraft_practice_sessions s ON s.id=a.session_id
  WHERE a.correct AND COALESCE(a.user_id::text,s.actor_key) IS NOT NULL AND a.submitted_at >= $1
  GROUP BY identity_key,a.user_id
)
SELECT rank() OVER (ORDER BY t.correct_answer_count DESC)::bigint AS rank, t.user_id,
       CASE WHEN t.user_id IS NULL THEN t.identity_key ELSE '' END AS guest_key,
       t.correct_answer_count
FROM totals t
ORDER BY t.correct_answer_count DESC, t.identity_key
LIMIT 100
`

type ListOverallRankingRow struct {
	Rank               int64         `json:"rank"`
	UserID             uuid.NullUUID `json:"user_id"`
	GuestKey           string        `json:"guest_key"`
	CorrectAnswerCount int64         `json:"correct_answer_count"`
}

// Identity is the immutable per-attempt attribution key: the signed-in
// learner's user_id, or the session's immutable actor_key for guests
// (COALESCE(a.user_id::text, s.actor_key)). Rows with no attributable
// identity are excluded. Entries expose only the nullable user_id plus
// rank/count; display-name synthesis is the Portal Gateway's job.
// guest_key carries the stable anonymous identity key for guest learners
// (user_id null -> the text identity key; signed-in learners -> the empty
// string, which practice_http.go serializes as JSON null). It is an
// x-internal field: Portal Gateway uses it only to derive a stable 游客x
// display label and MUST never expose it (ADR-0038).
func (q *Queries) ListOverallRanking(ctx context.Context, submittedAt pgtype.Timestamptz) ([]ListOverallRankingRow, error) {
	rows, err := q.db.Query(ctx, listOverallRanking, submittedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverallRankingRow{}
	for rows.Next() {
		var i ListOverallRankingRow
		if err := rows.Scan(
			&i.Rank,
			&i.UserID,
			&i.GuestKey,
			&i.CorrectAnswerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverallRankingWindow = `-- name: ListOverallRankingWindow :many
WITH totals AS (
  SELECT COALESCE(a.user_id::text,s.actor_key) AS identity_key,
         a.user_id,
         count(*)::bigint AS correct_answer_count
  FROM quizcraft_practice_attempts a
  LEFT JOIN quizcraft_practice_sessions s ON s.id=a.session_id
  WHERE a.correct AND COALESCE(a.user_id::text,s.actor_key) IS NOT NULL AND a.submitted_at >= $1 AND a.submitted_at < $2
  GROUP BY identity_key,a.user_id
)
SELECT user_id,rank() OVER (ORDER BY correct_answer_count DESC)::bigint AS rank,correct_answer_count
FROM totals ORDER BY correct_answer_count DESC,identity_key LIMIT 100
`

type ListOverallRankingWindowParams struct {
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	SubmittedAt_2 pgtype.Timestamptz `json:"submitted_at_2"`
}

type ListOverallRankingWindowRow struct {
	UserID             uuid.NullUUID `json:"user_id"`
	Rank               int64         `json:"rank"`
	CorrectAnswerCount int64         `json:"correct_answer_count"`
}

func (q *Queries) ListOverallRankingWindow(ctx context.Context, arg ListOverallRankingWindowParams) ([]ListOverallRankingWindowRow, error) {
	rows, err := q.db.Query(ctx, listOverallRankingWindow, arg.SubmittedAt, arg.SubmittedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverallRankingWindowRow{}
	for rows.Next() {
		var i ListOverallRankingWindowRow
		if err := rows.Scan(&i.UserID, &i.Rank, &i.CorrectAnswerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalMasteryFacts = `-- name: ListPersonalMasteryFacts :many
WITH active_questions AS (
  SELECT b.id AS bank_id,b.name,m.question_id
  FROM quizcraft_banks b
  JOIN quizcraft_bank_versions bv ON bv.id=b.active_version_id AND bv.bank_id=b.id AND bv.sealed_at IS NOT NULL
  JOIN quizcraft_bank_version_questions m ON m.bank_id=b.id AND m.bank_version_id=bv.id
),
bank_totals AS (
  SELECT bank_id,name AS label,count(*)::bigint AS total_questions
  FROM active_questions
  GROUP BY bank_id,name
),
personal_activity AS (
  SELECT active.bank_id,
         count(DISTINCT active.question_id) FILTER (WHERE attempt.correct)::bigint AS correct_questions
  FROM active_questions active
  JOIN quizcraft_practice_attempts attempt
    ON attempt.bank_id=active.bank_id AND attempt.question_id=active.question_id
  WHERE attempt.user_id=$1
  GROUP BY active.bank_id
)
SELECT totals.bank_id,totals.label,totals.total_questions,activity.correct_questions
FROM bank_totals totals
JOIN personal_activity activity ON activity.bank_id=totals.bank_id
ORDER BY totals.label,totals.bank_id
`

type ListPersonalMasteryFactsRow struct {
	BankID           uuid.UUID `json:"bank_id"`
	Label            string    `json:"label"`
	TotalQuestions   int64     `json:"total_questions"`
	CorrectQuestions int64     `json:"correct_questions"`
}

func (q *Queries) ListPersonalMasteryFacts(ctx context.Context, userID uuid.NullUUID) ([]ListPersonalMasteryFactsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalMasteryFacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalMasteryFactsRow{}
	for rows.Next() {
		var i ListPersonalMasteryFactsRow
		if err := rows.Scan(
			&i.BankID,
			&i.Label,
			&i.TotalQuestions,
			&i.CorrectQuestions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalPracticeDays = `-- name: ListPersonalPracticeDays :many
SELECT DISTINCT ((submitted_at AT TIME ZONE 'Asia/Shanghai')::date)::text AS activity_day
FROM quizcraft_practice_attempts
WHERE user_id=$1
ORDER BY activity_day DESC
`

func (q *Queries) ListPersonalPracticeDays(ctx context.Context, userID uuid.NullUUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPersonalPracticeDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var activity_day string
		if err := rows.Scan(&activity_day); err != nil {
			return nil, err
		}
		items = append(items, activity_day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPracticeQuestions = `-- name: ListPracticeQuestions :many
SELECT m.question_id,m.question_version_id,qv.type,qv.chapter_id,qv.chapter_name,qv.content,COALESCE(qv.options,'null'::jsonb) AS options
FROM quizcraft_bank_version_questions m
JOIN quizcraft_question_versions qv ON qv.id=m.question_version_id AND qv.question_id=m.question_id AND qv.bank_id=m.bank_id
LEFT JOIN quizcraft_question_stats stats ON stats.question_id=m.question_id
WHERE m.bank_version_id=$1 AND ($2::text='' OR qv.chapter_id=$2 OR qv.chapter_name=$2)
ORDER BY
  CASE WHEN $3::boolean THEN CASE WHEN COALESCE(stats.attempt_count,0)=0 THEN 1 ELSE stats.correct_count::numeric/stats.attempt_count END END ASC,
  md5(m.question_id::text || $4::uuid::text)
LIMIT $5
`

type ListPracticeQuestionsParams struct {
	BankVersionID uuid.UUID `json:"bank_version_id"`
	ChapterID     string    `json:"chapter_id"`
	Difficult     bool      `json:"difficult"`
	SessionID     uuid.UUID `json:"session_id"`
	QuestionCount int32     `json:"question_count"`
}

type ListPracticeQuestionsRow struct {
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Type              string    `json:"type"`
	ChapterID         string    `json:"chapter_id"`
	ChapterName       string    `json:"chapter_name"`
	Content           string    `json:"content"`
	Options           []byte    `json:"options"`
}

func (q *Queries) ListPracticeQuestions(ctx context.Context, arg ListPracticeQuestionsParams) ([]ListPracticeQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listPracticeQuestions,
		arg.BankVersionID,
		arg.ChapterID,
		arg.Difficult,
		arg.SessionID,
		arg.QuestionCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPracticeQuestionsRow{}
	for rows.Next() {
		var i ListPracticeQuestionsRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.QuestionVersionID,
			&i.Type,
			&i.ChapterID,
			&i.ChapterName,
			&i.Content,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBanks = `-- name: ListPublishedBanks :many
SELECT b.id, b.active_version_id, b.bank_key, b.name, bv.content_sha256,
       count(m.question_id)::bigint AS question_count,
       COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id',qv.chapter_id,'name',qv.chapter_name)) FILTER (WHERE qv.id IS NOT NULL),'[]'::jsonb) AS chapters
FROM quizcraft_banks b
JOIN quizcraft_bank_versions bv ON bv.id=b.active_version_id AND bv.bank_id=b.id AND bv.sealed_at IS NOT NULL
LEFT JOIN quizcraft_bank_version_questions m ON m.bank_version_id=bv.id
LEFT JOIN quizcraft_question_versions qv ON qv.id=m.question_version_id
GROUP BY b.id,b.active_version_id,b.bank_key,b.name,bv.content_sha256
ORDER BY b.name,b.id
`

type ListPublishedBanksRow struct {
	ID              uuid.UUID     `json:"id"`
	ActiveVersionID uuid.NullUUID `json:"active_version_id"`
	BankKey         string        `json:"bank_key"`
	Name            string        `json:"name"`
	ContentSha256   string        `json:"content_sha256"`
	QuestionCount   int64         `json:"question_count"`
	Chapters        interface{}   `json:"chapters"`
}

func (q *Queries) ListPublishedBanks(ctx context.Context) ([]ListPublishedBanksRow, error) {
	rows, err := q.db.Query(ctx, listPublishedBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedBanksRow{}
	for rows.Next() {
		var i ListPublishedBanksRow
		if err := rows.Scan(
			&i.ID,
			&i.ActiveVersionID,
			&i.BankKey,
			&i.Name,
			&i.ContentSha256,
			&i.QuestionCount,
			&i.Chapters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoredBankIDsWindow = `-- name: ListScoredBankIDsWindow :many
SELECT DISTINCT a.bank_id
FROM quizcraft_practice_attempts a
LEFT JOIN quizcraft_practice_sessions s ON s.id=a.session_id
WHERE a.correct AND COALESCE(a.user_id::text,s.actor_key) IS NOT NULL AND a.submitted_at >= $1 AND a.submitted_at < $2
ORDER BY a.bank_id
`

type ListScoredBankIDsWindowParams struct {
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	SubmittedAt_2 pgtype.Timestamptz `json:"submitted_at_2"`
}

func (q *Queries) ListScoredBankIDsWindow(ctx context.Context, arg ListScoredBankIDsWindowParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listScoredBankIDsWindow, arg.SubmittedAt, arg.SubmittedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var bank_id uuid.UUID
		if err := rows.Scan(&bank_id); err != nil {
			return nil, err
		}
		items = append(items, bank_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFavorite = `-- name: LockFavorite :exec
SELECT pg_advisory_xact_lock(hashtextextended($1,0))
`

func (q *Queries) LockFavorite(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockFavorite, hashtextextended)
	return err
}

const lockIdempotency = `-- name: LockIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended($1,0))
`

func (q *Queries) LockIdempotency(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockIdempotency, hashtextextended)
	return err
}

const lockSubmission = `-- name: LockSubmission :exec
SELECT pg_advisory_xact_lock(hashtextextended($1,0))
`

func (q *Queries) LockSubmission(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockSubmission, hashtextextended)
	return err
}

const rebuildLearningStateFromAttempts = `-- name: RebuildLearningStateFromAttempts :exec
WITH aggregates AS (
  SELECT user_id,bank_id,question_id,
         count(*)::bigint AS attempt_count,
         count(*) FILTER (WHERE correct)::bigint AS correct_count,
         max(submitted_at) AS updated_at
  FROM quizcraft_practice_attempts
  WHERE user_id IS NOT NULL
  GROUP BY user_id,bank_id,question_id
),
latest AS (
  SELECT DISTINCT ON (user_id,bank_id,question_id)
         user_id,bank_id,question_id,id AS latest_attempt_id,question_version_id,(NOT correct) AS wrong
  FROM quizcraft_practice_attempts
  WHERE user_id IS NOT NULL
  ORDER BY user_id,bank_id,question_id,submitted_at DESC,id DESC
)
INSERT INTO quizcraft_learning_state(user_id,bank_id,question_id,question_version_id,wrong,attempt_count,correct_count,latest_attempt_id,updated_at)
SELECT aggregates.user_id,aggregates.bank_id,aggregates.question_id,latest.question_version_id,
       latest.wrong,aggregates.attempt_count,aggregates.correct_count,latest.latest_attempt_id,aggregates.updated_at
FROM aggregates
JOIN latest USING (user_id,bank_id,question_id)
`

func (q *Queries) RebuildLearningStateFromAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildLearningStateFromAttempts)
	return err
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM quizcraft_favorites
WHERE user_id=$1 AND bank_id=$2 AND question_id=$3
`

type RemoveFavoriteParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BankID     uuid.UUID `json:"bank_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.BankID, arg.QuestionID)
	return err
}

const storeIdempotencyResult = `-- name: StoreIdempotencyResult :exec
INSERT INTO quizcraft_idempotency_results(actor_key,operation_kind,idempotency_key,request_sha256,response_status,response_body,resource_id)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type StoreIdempotencyResultParams struct {
	ActorKey       string        `json:"actor_key"`
	OperationKind  string        `json:"operation_kind"`
	IdempotencyKey string        `json:"idempotency_key"`
	RequestSha256  string        `json:"request_sha256"`
	ResponseStatus int32         `json:"response_status"`
	ResponseBody   string        `json:"response_body"`
	ResourceID     uuid.NullUUID `json:"resource_id"`
}

func (q *Queries) StoreIdempotencyResult(ctx context.Context, arg StoreIdempotencyResultParams) error {
	_, err := q.db.Exec(ctx, storeIdempotencyResult,
		arg.ActorKey,
		arg.OperationKind,
		arg.IdempotencyKey,
		arg.RequestSha256,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResourceID,
	)
	return err
}

const updateLearningState = `-- name: UpdateLearningState :exec
INSERT INTO quizcraft_learning_state(user_id,bank_id,question_id,question_version_id,wrong,attempt_count,correct_count,latest_attempt_id,updated_at)
VALUES($1,$2,$3,$4,$5,1,$6,$7,$8)
ON CONFLICT(user_id,bank_id,question_id) DO UPDATE
SET question_version_id=CASE
        WHEN (EXCLUDED.updated_at,EXCLUDED.latest_attempt_id) > (quizcraft_learning_state.updated_at,quizcraft_learning_state.latest_attempt_id)
        THEN EXCLUDED.question_version_id
        ELSE quizcraft_learning_state.question_version_id
    END,
    wrong=CASE
        WHEN (EXCLUDED.updated_at,EXCLUDED.latest_attempt_id) > (quizcraft_learning_state.updated_at,quizcraft_learning_state.latest_attempt_id)
        THEN EXCLUDED.wrong
        ELSE quizcraft_learning_state.wrong
    END,
    attempt_count=quizcraft_learning_state.attempt_count+1,
    correct_count=quizcraft_learning_state.correct_count+EXCLUDED.correct_count,
    latest_attempt_id=CASE
        WHEN (EXCLUDED.updated_at,EXCLUDED.latest_attempt_id) > (quizcraft_learning_state.updated_at,quizcraft_learning_state.latest_attempt_id)
        THEN EXCLUDED.latest_attempt_id
        ELSE quizcraft_learning_state.latest_attempt_id
    END,
    updated_at=GREATEST(quizcraft_learning_state.updated_at,EXCLUDED.updated_at)
`

type UpdateLearningStateParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	BankID            uuid.UUID          `json:"bank_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	QuestionVersionID uuid.UUID          `json:"question_version_id"`
	Wrong             bool               `json:"wrong"`
	CorrectCount      int64              `json:"correct_count"`
	LatestAttemptID   uuid.UUID          `json:"latest_attempt_id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateLearningState(ctx context.Context, arg UpdateLearningStateParams) error {
	_, err := q.db.Exec(ctx, updateLearningState,
		arg.UserID,
		arg.BankID,
		arg.QuestionID,
		arg.QuestionVersionID,
		arg.Wrong,
		arg.CorrectCount,
		arg.LatestAttemptID,
		arg.UpdatedAt,
	)
	return err
}

const updateQuestionStats = `-- name: UpdateQuestionStats :exec
INSERT INTO quizcraft_question_stats(question_id,attempt_count,correct_count)
VALUES($1,1,$2)
ON CONFLICT(question_id) DO UPDATE
SET attempt_count=quizcraft_question_stats.attempt_count+1,
    correct_count=quizcraft_question_stats.correct_count+EXCLUDED.correct_count,
    updated_at=now()
`

type UpdateQuestionStatsParams struct {
	QuestionID   uuid.UUID `json:"question_id"`
	CorrectCount int64     `json:"correct_count"`
}

func (q *Queries) UpdateQuestionStats(ctx context.Context, arg UpdateQuestionStatsParams) error {
	_, err := q.db.Exec(ctx, updateQuestionStats, arg.QuestionID, arg.CorrectCount)
	return err
}
