// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: practice.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPracticeSessionQuestion = `-- name: AddPracticeSessionQuestion :exec
INSERT INTO quizcraft_practice_session_questions(session_id,bank_id,bank_version_id,question_id,question_version_id,position)
VALUES($1,$2,$3,$4,$5,$6)
`

type AddPracticeSessionQuestionParams struct {
	SessionID         uuid.UUID `json:"session_id"`
	BankID            uuid.UUID `json:"bank_id"`
	BankVersionID     uuid.UUID `json:"bank_version_id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Position          int32     `json:"position"`
}

func (q *Queries) AddPracticeSessionQuestion(ctx context.Context, arg AddPracticeSessionQuestionParams) error {
	_, err := q.db.Exec(ctx, addPracticeSessionQuestion,
		arg.SessionID,
		arg.BankID,
		arg.BankVersionID,
		arg.QuestionID,
		arg.QuestionVersionID,
		arg.Position,
	)
	return err
}

const createPracticeAttempt = `-- name: CreatePracticeAttempt :exec
INSERT INTO quizcraft_practice_attempts(id,session_id,bank_id,bank_version_id,question_id,question_version_id,user_id,submitted_answer,correct,expected_answer,analysis,response_body)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type CreatePracticeAttemptParams struct {
	ID                uuid.UUID     `json:"id"`
	SessionID         uuid.UUID     `json:"session_id"`
	BankID            uuid.UUID     `json:"bank_id"`
	BankVersionID     uuid.UUID     `json:"bank_version_id"`
	QuestionID        uuid.UUID     `json:"question_id"`
	QuestionVersionID uuid.UUID     `json:"question_version_id"`
	UserID            uuid.NullUUID `json:"user_id"`
	SubmittedAnswer   []byte        `json:"submitted_answer"`
	Correct           bool          `json:"correct"`
	ExpectedAnswer    []byte        `json:"expected_answer"`
	Analysis          string        `json:"analysis"`
	ResponseBody      string        `json:"response_body"`
}

func (q *Queries) CreatePracticeAttempt(ctx context.Context, arg CreatePracticeAttemptParams) error {
	_, err := q.db.Exec(ctx, createPracticeAttempt,
		arg.ID,
		arg.SessionID,
		arg.BankID,
		arg.BankVersionID,
		arg.QuestionID,
		arg.QuestionVersionID,
		arg.UserID,
		arg.SubmittedAnswer,
		arg.Correct,
		arg.ExpectedAnswer,
		arg.Analysis,
		arg.ResponseBody,
	)
	return err
}

const createPracticeSession = `-- name: CreatePracticeSession :exec
INSERT INTO quizcraft_practice_sessions(id,bank_id,bank_version_id,user_id,actor_key,mode,chapter_id)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type CreatePracticeSessionParams struct {
	ID            uuid.UUID     `json:"id"`
	BankID        uuid.UUID     `json:"bank_id"`
	BankVersionID uuid.UUID     `json:"bank_version_id"`
	UserID        uuid.NullUUID `json:"user_id"`
	ActorKey      string        `json:"actor_key"`
	Mode          string        `json:"mode"`
	ChapterID     pgtype.Text   `json:"chapter_id"`
}

func (q *Queries) CreatePracticeSession(ctx context.Context, arg CreatePracticeSessionParams) error {
	_, err := q.db.Exec(ctx, createPracticeSession,
		arg.ID,
		arg.BankID,
		arg.BankVersionID,
		arg.UserID,
		arg.ActorKey,
		arg.Mode,
		arg.ChapterID,
	)
	return err
}

const getIdempotencyResult = `-- name: GetIdempotencyResult :one
SELECT request_sha256,response_status,response_body
FROM quizcraft_idempotency_results
WHERE actor_key=$1 AND operation_kind=$2 AND idempotency_key=$3
`

type GetIdempotencyResultParams struct {
	ActorKey       string `json:"actor_key"`
	OperationKind  string `json:"operation_kind"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetIdempotencyResultRow struct {
	RequestSha256  string `json:"request_sha256"`
	ResponseStatus int32  `json:"response_status"`
	ResponseBody   string `json:"response_body"`
}

func (q *Queries) GetIdempotencyResult(ctx context.Context, arg GetIdempotencyResultParams) (GetIdempotencyResultRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyResult, arg.ActorKey, arg.OperationKind, arg.IdempotencyKey)
	var i GetIdempotencyResultRow
	err := row.Scan(&i.RequestSha256, &i.ResponseStatus, &i.ResponseBody)
	return i, err
}

const getOperationResult = `-- name: GetOperationResult :one
SELECT resource_id, response_body
FROM quizcraft_idempotency_results
WHERE actor_key = $1 AND operation_kind = $2 AND idempotency_key = $3
`

type GetOperationResultParams struct {
	ActorKey       string `json:"actor_key"`
	OperationKind  string `json:"operation_kind"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetOperationResultRow struct {
	ResourceID   uuid.NullUUID `json:"resource_id"`
	ResponseBody string        `json:"response_body"`
}

func (q *Queries) GetOperationResult(ctx context.Context, arg GetOperationResultParams) (GetOperationResultRow, error) {
	row := q.db.QueryRow(ctx, getOperationResult, arg.ActorKey, arg.OperationKind, arg.IdempotencyKey)
	var i GetOperationResultRow
	err := row.Scan(&i.ResourceID, &i.ResponseBody)
	return i, err
}

const getPracticeAttemptResponse = `-- name: GetPracticeAttemptResponse :one
SELECT response_body
FROM quizcraft_practice_attempts
WHERE session_id=$1 AND question_id=$2
`

type GetPracticeAttemptResponseParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetPracticeAttemptResponse(ctx context.Context, arg GetPracticeAttemptResponseParams) (string, error) {
	row := q.db.QueryRow(ctx, getPracticeAttemptResponse, arg.SessionID, arg.QuestionID)
	var response_body string
	err := row.Scan(&response_body)
	return response_body, err
}

const getSessionQuestion = `-- name: GetSessionQuestion :one
SELECT s.bank_id,s.bank_version_id,s.user_id,s.actor_key,qv.type,qv.answer,COALESCE(qv.options,'null'::jsonb) AS options,qv.analysis,b.bank_key,q.source_question_id
FROM quizcraft_practice_sessions s
JOIN quizcraft_practice_session_questions sq ON sq.session_id=s.id
JOIN quizcraft_question_versions qv ON qv.id=sq.question_version_id AND qv.question_id=sq.question_id
JOIN quizcraft_questions q ON q.id=sq.question_id
JOIN quizcraft_banks b ON b.id=s.bank_id
WHERE s.id=$1 AND sq.question_id=$2 AND sq.question_version_id=$3
`

type GetSessionQuestionParams struct {
	ID                uuid.UUID `json:"id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
}

type GetSessionQuestionRow struct {
	BankID           uuid.UUID     `json:"bank_id"`
	BankVersionID    uuid.UUID     `json:"bank_version_id"`
	UserID           uuid.NullUUID `json:"user_id"`
	ActorKey         string        `json:"actor_key"`
	Type             string        `json:"type"`
	Answer           []byte        `json:"answer"`
	Options          []byte        `json:"options"`
	Analysis         string        `json:"analysis"`
	BankKey          string        `json:"bank_key"`
	SourceQuestionID string        `json:"source_question_id"`
}

func (q *Queries) GetSessionQuestion(ctx context.Context, arg GetSessionQuestionParams) (GetSessionQuestionRow, error) {
	row := q.db.QueryRow(ctx, getSessionQuestion, arg.ID, arg.QuestionID, arg.QuestionVersionID)
	var i GetSessionQuestionRow
	err := row.Scan(
		&i.BankID,
		&i.BankVersionID,
		&i.UserID,
		&i.ActorKey,
		&i.Type,
		&i.Answer,
		&i.Options,
		&i.Analysis,
		&i.BankKey,
		&i.SourceQuestionID,
	)
	return i, err
}

const insertShadowComparison = `-- name: InsertShadowComparison :exec
INSERT INTO quizcraft_shadow_comparisons(id,session_id,question_id,new_response,legacy_response,outcome,detail)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertShadowComparisonParams struct {
	ID             uuid.UUID `json:"id"`
	SessionID      uuid.UUID `json:"session_id"`
	QuestionID     uuid.UUID `json:"question_id"`
	NewResponse    []byte    `json:"new_response"`
	LegacyResponse []byte    `json:"legacy_response"`
	Outcome        string    `json:"outcome"`
	Detail         string    `json:"detail"`
}

func (q *Queries) InsertShadowComparison(ctx context.Context, arg InsertShadowComparisonParams) error {
	_, err := q.db.Exec(ctx, insertShadowComparison,
		arg.ID,
		arg.SessionID,
		arg.QuestionID,
		arg.NewResponse,
		arg.LegacyResponse,
		arg.Outcome,
		arg.Detail,
	)
	return err
}

const isPublishedBankVersion = `-- name: IsPublishedBankVersion :one
SELECT true AS published
FROM quizcraft_banks b
JOIN quizcraft_bank_versions bv ON bv.id=$2 AND bv.bank_id=b.id
WHERE b.id=$1 AND b.active_version_id=$2 AND bv.sealed_at IS NOT NULL
`

type IsPublishedBankVersionParams struct {
	ID   uuid.UUID `json:"id"`
	ID_2 uuid.UUID `json:"id_2"`
}

func (q *Queries) IsPublishedBankVersion(ctx context.Context, arg IsPublishedBankVersionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPublishedBankVersion, arg.ID, arg.ID_2)
	var published bool
	err := row.Scan(&published)
	return published, err
}

const listLearningState = `-- name: ListLearningState :many
SELECT bank_id,question_id,question_version_id,wrong,attempt_count,correct_count,updated_at
FROM quizcraft_learning_state
WHERE user_id=$1
ORDER BY updated_at DESC
`

type ListLearningStateRow struct {
	BankID            uuid.UUID          `json:"bank_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	QuestionVersionID uuid.UUID          `json:"question_version_id"`
	Wrong             bool               `json:"wrong"`
	AttemptCount      int64              `json:"attempt_count"`
	CorrectCount      int64              `json:"correct_count"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLearningState(ctx context.Context, userID uuid.UUID) ([]ListLearningStateRow, error) {
	rows, err := q.db.Query(ctx, listLearningState, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningStateRow{}
	for rows.Next() {
		var i ListLearningStateRow
		if err := rows.Scan(
			&i.BankID,
			&i.QuestionID,
			&i.QuestionVersionID,
			&i.Wrong,
			&i.AttemptCount,
			&i.CorrectCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPracticeQuestions = `-- name: ListPracticeQuestions :many
SELECT m.question_id,m.question_version_id,qv.type,qv.chapter_id,qv.chapter_name,qv.content,COALESCE(qv.options,'null'::jsonb) AS options
FROM quizcraft_bank_version_questions m
JOIN quizcraft_question_versions qv ON qv.id=m.question_version_id AND qv.question_id=m.question_id AND qv.bank_id=m.bank_id
LEFT JOIN quizcraft_question_stats stats ON stats.question_id=m.question_id
WHERE m.bank_version_id=$1 AND ($2::text='' OR qv.chapter_id=$2 OR qv.chapter_name=$2)
ORDER BY
  CASE WHEN $3::boolean THEN CASE WHEN COALESCE(stats.attempt_count,0)=0 THEN 1 ELSE stats.correct_count::numeric/stats.attempt_count END END ASC,
  md5(m.question_id::text || $4::uuid::text)
LIMIT $5
`

type ListPracticeQuestionsParams struct {
	BankVersionID uuid.UUID `json:"bank_version_id"`
	ChapterID     string    `json:"chapter_id"`
	Difficult     bool      `json:"difficult"`
	SessionID     uuid.UUID `json:"session_id"`
	QuestionCount int32     `json:"question_count"`
}

type ListPracticeQuestionsRow struct {
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Type              string    `json:"type"`
	ChapterID         string    `json:"chapter_id"`
	ChapterName       string    `json:"chapter_name"`
	Content           string    `json:"content"`
	Options           []byte    `json:"options"`
}

func (q *Queries) ListPracticeQuestions(ctx context.Context, arg ListPracticeQuestionsParams) ([]ListPracticeQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listPracticeQuestions,
		arg.BankVersionID,
		arg.ChapterID,
		arg.Difficult,
		arg.SessionID,
		arg.QuestionCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPracticeQuestionsRow{}
	for rows.Next() {
		var i ListPracticeQuestionsRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.QuestionVersionID,
			&i.Type,
			&i.ChapterID,
			&i.ChapterName,
			&i.Content,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBanks = `-- name: ListPublishedBanks :many
SELECT b.id, b.active_version_id, b.bank_key, b.name, bv.content_sha256,
       count(m.question_id)::bigint AS question_count,
       COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id',qv.chapter_id,'name',qv.chapter_name)) FILTER (WHERE qv.id IS NOT NULL),'[]'::jsonb) AS chapters
FROM quizcraft_banks b
JOIN quizcraft_bank_versions bv ON bv.id=b.active_version_id AND bv.bank_id=b.id AND bv.sealed_at IS NOT NULL
LEFT JOIN quizcraft_bank_version_questions m ON m.bank_version_id=bv.id
LEFT JOIN quizcraft_question_versions qv ON qv.id=m.question_version_id
GROUP BY b.id,b.active_version_id,b.bank_key,b.name,bv.content_sha256
ORDER BY b.name,b.id
`

type ListPublishedBanksRow struct {
	ID              uuid.UUID     `json:"id"`
	ActiveVersionID uuid.NullUUID `json:"active_version_id"`
	BankKey         string        `json:"bank_key"`
	Name            string        `json:"name"`
	ContentSha256   string        `json:"content_sha256"`
	QuestionCount   int64         `json:"question_count"`
	Chapters        interface{}   `json:"chapters"`
}

func (q *Queries) ListPublishedBanks(ctx context.Context) ([]ListPublishedBanksRow, error) {
	rows, err := q.db.Query(ctx, listPublishedBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedBanksRow{}
	for rows.Next() {
		var i ListPublishedBanksRow
		if err := rows.Scan(
			&i.ID,
			&i.ActiveVersionID,
			&i.BankKey,
			&i.Name,
			&i.ContentSha256,
			&i.QuestionCount,
			&i.Chapters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIdempotency = `-- name: LockIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended($1,0))
`

func (q *Queries) LockIdempotency(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockIdempotency, hashtextextended)
	return err
}

const lockSubmission = `-- name: LockSubmission :exec
SELECT pg_advisory_xact_lock(hashtextextended($1,0))
`

func (q *Queries) LockSubmission(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockSubmission, hashtextextended)
	return err
}

const storeIdempotencyResult = `-- name: StoreIdempotencyResult :exec
INSERT INTO quizcraft_idempotency_results(actor_key,operation_kind,idempotency_key,request_sha256,response_status,response_body,resource_id)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type StoreIdempotencyResultParams struct {
	ActorKey       string        `json:"actor_key"`
	OperationKind  string        `json:"operation_kind"`
	IdempotencyKey string        `json:"idempotency_key"`
	RequestSha256  string        `json:"request_sha256"`
	ResponseStatus int32         `json:"response_status"`
	ResponseBody   string        `json:"response_body"`
	ResourceID     uuid.NullUUID `json:"resource_id"`
}

func (q *Queries) StoreIdempotencyResult(ctx context.Context, arg StoreIdempotencyResultParams) error {
	_, err := q.db.Exec(ctx, storeIdempotencyResult,
		arg.ActorKey,
		arg.OperationKind,
		arg.IdempotencyKey,
		arg.RequestSha256,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResourceID,
	)
	return err
}

const updateLearningState = `-- name: UpdateLearningState :exec
INSERT INTO quizcraft_learning_state(user_id,bank_id,question_id,question_version_id,wrong,attempt_count,correct_count)
VALUES($1,$2,$3,$4,$5,1,$6)
ON CONFLICT(user_id,bank_id,question_id) DO UPDATE
SET question_version_id=EXCLUDED.question_version_id,
    wrong=EXCLUDED.wrong,
    attempt_count=quizcraft_learning_state.attempt_count+1,
    correct_count=quizcraft_learning_state.correct_count+EXCLUDED.correct_count,
    updated_at=now()
`

type UpdateLearningStateParams struct {
	UserID            uuid.UUID `json:"user_id"`
	BankID            uuid.UUID `json:"bank_id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Wrong             bool      `json:"wrong"`
	CorrectCount      int64     `json:"correct_count"`
}

func (q *Queries) UpdateLearningState(ctx context.Context, arg UpdateLearningStateParams) error {
	_, err := q.db.Exec(ctx, updateLearningState,
		arg.UserID,
		arg.BankID,
		arg.QuestionID,
		arg.QuestionVersionID,
		arg.Wrong,
		arg.CorrectCount,
	)
	return err
}

const updateQuestionStats = `-- name: UpdateQuestionStats :exec
INSERT INTO quizcraft_question_stats(question_id,attempt_count,correct_count)
VALUES($1,1,$2)
ON CONFLICT(question_id) DO UPDATE
SET attempt_count=quizcraft_question_stats.attempt_count+1,
    correct_count=quizcraft_question_stats.correct_count+EXCLUDED.correct_count,
    updated_at=now()
`

type UpdateQuestionStatsParams struct {
	QuestionID   uuid.UUID `json:"question_id"`
	CorrectCount int64     `json:"correct_count"`
}

func (q *Queries) UpdateQuestionStats(ctx context.Context, arg UpdateQuestionStatsParams) error {
	_, err := q.db.Exec(ctx, updateQuestionStats, arg.QuestionID, arg.CorrectCount)
	return err
}
