// Code generated by cmd/contractgen from portal-gateway.yaml; DO NOT EDIT.
package contract

import "time"

const PortalSessionSourceSHA256 = "0d349a6f91fdcc8391a56ebac230937c677a80b1d92e0100a5e6ed7e59bfb77d"

type PortalSession struct {
	DisplayName *string   `json:"display_name,omitempty"`
	ExpiresAt   time.Time `json:"expires_at"`
	UserID      string    `json:"user_id"`
}
