// Code generated by cmd/contractgen from portal-gateway.yaml; DO NOT EDIT.
package contract

import "time"

const PortalSessionSourceSHA256 = "9d9b188aee2eb8c5716ea844e239ebb5975e64fb60e971d95d19264bb12e4d14"

type PortalSession struct {
	DisplayName *string   `json:"display_name,omitempty"`
	ExpiresAt   time.Time `json:"expires_at"`
	UserID      string    `json:"user_id"`
}
