// Code generated by cmd/quizcraftcontractgen from quizcraft.yaml; DO NOT EDIT.
package practice

const QuizCraftCatalogContractSHA256 = "d933ae03711c018cff95f8d20e5389f61fe9e887c41b53a94c23a238ed84cc33"
const ListPracticeBanksPath = "/api/v1/banks"

// BankListEnvelope is the generated read-only QuizCraft catalog response.
// Its data members are the published, and therefore available, bank versions.
type BankListEnvelope struct {
	RequestID string        `json:"request_id"`
	Data      []BankVersion `json:"data"`
}

// BankVersion is the stable published version of one QuizCraft bank.
type BankVersion struct {
	BankID        string    `json:"bank_id"`
	BankVersionID string    `json:"bank_version_id"`
	BankKey       string    `json:"bank_key"`
	Name          string    `json:"name"`
	ContentSHA256 string    `json:"content_sha256"`
	QuestionCount int       `json:"question_count"`
	Chapters      []Chapter `json:"chapters"`
}

// Chapter is a published QuizCraft bank chapter.
type Chapter struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
