// Code generated by cmd/quizcraftcontractgen from quizcraft.yaml; DO NOT EDIT.
package practice

const QuizCraftCatalogContractSHA256 = "2715c4751d8de7c415879210259bf119db84f56850ba54725db9af00e299e6dc"
const QuizCraftRankingContractSHA256 = QuizCraftCatalogContractSHA256
const ListPracticeBanksPath = "/api/v1/banks"
const GetPersonalPracticeStatsPath = "/api/v1/stats"
const GetPortalLearningStatePath = "/api/v1/portal/practice/learning-state"
const OverallRankingPath = "/api/v1/rankings/overall"
const BankRankingPath = "/api/v1/banks/{bank_id}/rankings"
const CreatePortalPracticeSessionPath = "/api/v1/portal/practice/sessions"
const SubmitPortalPracticeAnswerPath = "/api/v1/portal/practice/sessions/{session_id}/answers"
const CreatePortalPracticeFeedbackPath = "/api/v1/portal/practice/feedback"
const GetPortalPracticeFeedbackStatusPath = "/api/v1/portal/practice/feedback/{feedback_id}/status"
const GetPortalFavoritesOverviewPath = "/api/v1/portal/practice/favorites"
const ListPortalFavoriteQuestionsPath = "/api/v1/portal/practice/banks/{bank_id}/favorites"
const FavoritePortalQuestionPath = "/api/v1/portal/practice/banks/{bank_id}/favorites/{question_id}"
const UnfavoritePortalQuestionPath = "/api/v1/portal/practice/banks/{bank_id}/favorites/{question_id}"
const CreatePortalFavoritesSessionPath = "/api/v1/portal/practice/banks/{bank_id}/favorites/practice-sessions"

// BankListEnvelope is the generated read-only QuizCraft catalog response.
// Its data members are the published, and therefore available, bank versions.
type BankListEnvelope struct {
	RequestID string        `json:"request_id"`
	Data      []BankVersion `json:"data"`
}

// BankVersion is the stable published version of one QuizCraft bank.
type BankVersion struct {
	BankID        string    `json:"bank_id"`
	BankVersionID string    `json:"bank_version_id"`
	BankKey       string    `json:"bank_key"`
	Name          string    `json:"name"`
	ContentSHA256 string    `json:"content_sha256"`
	QuestionCount int       `json:"question_count"`
	Chapters      []Chapter `json:"chapters"`
}

// Chapter is a published QuizCraft bank chapter.
type Chapter struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RankingPeriod string

const (
	RankingPeriodWeekly   RankingPeriod = "weekly"
	RankingPeriodLifetime RankingPeriod = "lifetime"
)

// RankingEnvelope contains public fields only; internal account identifiers are
// deliberately absent from the Portal read contract.
type RankingEnvelope struct {
	RequestID string      `json:"request_id"`
	Data      RankingPage `json:"data"`
}

type RankingPage struct {
	Scope   string         `json:"scope"`
	BankID  string         `json:"bank_id,omitempty"`
	Period  RankingPeriod  `json:"period"`
	Metric  string         `json:"metric"`
	Entries []RankingEntry `json:"entries"`
}

type RankingEntry struct {
	Rank               int64  `json:"rank"`
	Nickname           string `json:"nickname"`
	SystemAvatar       string `json:"system_avatar"`
	CorrectAnswerCount int64  `json:"correct_answer_count"`
}

// PersonalPracticeStatsEnvelope is one authenticated Portal user's
// fact-derived QuizCraft statistics. It never represents a mock response.
type PersonalPracticeStatsEnvelope struct {
	RequestID string                `json:"request_id"`
	Data      PersonalPracticeStats `json:"data"`
}

type PersonalPracticeStats struct {
	TotalAnswers   int64            `json:"total_answers"`
	CorrectAnswers int64            `json:"correct_answers"`
	Accuracy       int              `json:"accuracy"`
	StreakDays     int              `json:"streak_days"`
	Mastery        []MasterySubject `json:"mastery"`
}

type MasterySubject struct {
	BankID           string `json:"bank_id"`
	Label            string `json:"label"`
	Value            int    `json:"value"`
	TotalQuestions   int64  `json:"total_questions"`
	CorrectQuestions int64  `json:"correct_questions"`
}

// LearningStateEnvelope contains only Core-derived facts for one signed-in
// Portal actor. Question content is deliberately absent.
type LearningStateEnvelope struct {
	RequestID string            `json:"request_id"`
	Data      LearningStatePage `json:"data"`
}

type LearningStatePage struct {
	Items      []LearningStateItem     `json:"items"`
	Pagination LearningStatePagination `json:"pagination"`
}

type LearningStatePagination struct {
	Page       int64 `json:"page"`
	PageSize   int64 `json:"page_size"`
	Total      int64 `json:"total"`
	TotalPages int64 `json:"total_pages"`
}

type LearningStateItem struct {
	BankID            string `json:"bank_id"`
	QuestionID        string `json:"question_id"`
	QuestionVersionID string `json:"question_version_id"`
	Wrong             bool   `json:"wrong"`
	AttemptCount      int64  `json:"attempt_count"`
	CorrectCount      int64  `json:"correct_count"`
	UpdatedAt         string `json:"updated_at"`
}

// FeedbackStatusEnvelope is one authenticated Portal user's persisted
// correction processing status. It never represents a mock response.
type FeedbackStatusEnvelope struct {
	RequestID string         `json:"request_id"`
	Data      FeedbackStatus `json:"data"`
}

type FeedbackStatus struct {
	FeedbackID        string `json:"feedback_id"`
	BankID            string `json:"bank_id"`
	QuestionID        string `json:"question_id"`
	QuestionVersionID string `json:"question_version_id"`
	Category          string `json:"category"`
	Status            string `json:"status"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

// FavoritesOverviewEnvelope lists one signed-in Portal user's automatic
// per-bank favorite folders. It never represents a mock response.
type FavoritesOverviewEnvelope struct {
	RequestID string           `json:"request_id"`
	Data      []FavoriteFolder `json:"data"`
}

type FavoriteFolder struct {
	BankID           string `json:"bank_id"`
	BankName         string `json:"bank_name"`
	AvailableCount   int    `json:"available_count"`
	UnavailableCount int    `json:"unavailable_count"`
}

// FavoriteListEnvelope lists one bank's favorite references for one user.
// Unavailable items expose references only; available items carry the content
// version id.
type FavoriteListEnvelope struct {
	RequestID string             `json:"request_id"`
	Data      []FavoriteQuestion `json:"data"`
}

type FavoriteQuestion struct {
	BankID            string `json:"bank_id"`
	QuestionID        string `json:"question_id"`
	Available         bool   `json:"available"`
	QuestionVersionID string `json:"question_version_id,omitempty"`
}
