// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthorizationAuditEvent = `-- name: CreateAuthorizationAuditEvent :exec
INSERT INTO authorization_audit_events (
    actor_user_id, session_id, request_id, service_id, permission_code,
    target_kind, target_product_code, target_resource_type, target_resource_id,
    decision, reason_code, grant_id, authorization_revision
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13
)
`

type CreateAuthorizationAuditEventParams struct {
	ActorUserID           pgtype.UUID `json:"actor_user_id"`
	SessionID             pgtype.UUID `json:"session_id"`
	RequestID             string      `json:"request_id"`
	ServiceID             string      `json:"service_id"`
	PermissionCode        string      `json:"permission_code"`
	TargetKind            string      `json:"target_kind"`
	TargetProductCode     pgtype.Text `json:"target_product_code"`
	TargetResourceType    pgtype.Text `json:"target_resource_type"`
	TargetResourceID      pgtype.Text `json:"target_resource_id"`
	Decision              string      `json:"decision"`
	ReasonCode            string      `json:"reason_code"`
	GrantID               pgtype.UUID `json:"grant_id"`
	AuthorizationRevision pgtype.Int8 `json:"authorization_revision"`
}

func (q *Queries) CreateAuthorizationAuditEvent(ctx context.Context, arg CreateAuthorizationAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuthorizationAuditEvent,
		arg.ActorUserID,
		arg.SessionID,
		arg.RequestID,
		arg.ServiceID,
		arg.PermissionCode,
		arg.TargetKind,
		arg.TargetProductCode,
		arg.TargetResourceType,
		arg.TargetResourceID,
		arg.Decision,
		arg.ReasonCode,
		arg.GrantID,
		arg.AuthorizationRevision,
	)
	return err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO authorization_codes (
    code_hash, user_id, client_id, core_session_id, redirect_uri, code_challenge, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateAuthorizationCodeParams struct {
	CodeHash      []byte             `json:"code_hash"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientID      string             `json:"client_id"`
	CoreSessionID pgtype.UUID        `json:"core_session_id"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.CodeHash,
		arg.UserID,
		arg.ClientID,
		arg.CoreSessionID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createExchangeSession = `-- name: CreateExchangeSession :one
INSERT INTO sessions (
    user_id, kind, token_hash, client_id, parent_session_id, expires_at
) VALUES ($1, 'client_exchange', $2, $3, $4, $5)
RETURNING id, expires_at
`

type CreateExchangeSessionParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	TokenHash       []byte             `json:"token_hash"`
	ClientID        pgtype.Text        `json:"client_id"`
	ParentSessionID pgtype.UUID        `json:"parent_session_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type CreateExchangeSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateExchangeSession(ctx context.Context, arg CreateExchangeSessionParams) (CreateExchangeSessionRow, error) {
	row := q.db.QueryRow(ctx, createExchangeSession,
		arg.UserID,
		arg.TokenHash,
		arg.ClientID,
		arg.ParentSessionID,
		arg.ExpiresAt,
	)
	var i CreateExchangeSessionRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const createOAuthExchangeIdempotency = `-- name: CreateOAuthExchangeIdempotency :exec
INSERT INTO oauth_exchange_idempotency (
    client_id, idempotency_key, request_hash, response_ciphertext, expires_at
) VALUES ($1, $2, $3, ''::bytea, $4)
ON CONFLICT (client_id, idempotency_key) DO UPDATE SET
    request_hash = EXCLUDED.request_hash,
    response_ciphertext = ''::bytea,
    expires_at = EXCLUDED.expires_at,
    created_at = now()
WHERE oauth_exchange_idempotency.expires_at <= now()
`

type CreateOAuthExchangeIdempotencyParams struct {
	ClientID       string             `json:"client_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    []byte             `json:"request_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthExchangeIdempotency(ctx context.Context, arg CreateOAuthExchangeIdempotencyParams) error {
	_, err := q.db.Exec(ctx, createOAuthExchangeIdempotency,
		arg.ClientID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	return err
}

const getActiveCoreSessionByTokenHash = `-- name: GetActiveCoreSessionByTokenHash :one
SELECT s.id, s.user_id, s.expires_at, u.email_verified, u.status, u.created_at AS user_created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.kind = 'core'
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
FOR UPDATE OF s, u
`

type GetActiveCoreSessionByTokenHashRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	EmailVerified bool               `json:"email_verified"`
	Status        string             `json:"status"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) GetActiveCoreSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetActiveCoreSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveCoreSessionByTokenHash, tokenHash)
	var i GetActiveCoreSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.EmailVerified,
		&i.Status,
		&i.UserCreatedAt,
	)
	return i, err
}

const getActiveCoreSessionForExchange = `-- name: GetActiveCoreSessionForExchange :one
SELECT s.id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.kind = 'core'
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.status = 'active'
FOR UPDATE OF s, u
`

func (q *Queries) GetActiveCoreSessionForExchange(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveCoreSessionForExchange, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getAuthorizationCodeForUpdate = `-- name: GetAuthorizationCodeForUpdate :one
SELECT id, user_id, client_id, core_session_id, redirect_uri, code_challenge, expires_at, used_at
FROM authorization_codes
WHERE code_hash = $1
FOR UPDATE
`

type GetAuthorizationCodeForUpdateRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientID      string             `json:"client_id"`
	CoreSessionID pgtype.UUID        `json:"core_session_id"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) GetAuthorizationCodeForUpdate(ctx context.Context, codeHash []byte) (GetAuthorizationCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCodeForUpdate, codeHash)
	var i GetAuthorizationCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.CoreSessionID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getAuthorizationGrant = `-- name: GetAuthorizationGrant :one
SELECT s.user_id, g.id AS grant_id,
       CAST(GREATEST(u.authorization_revision, r.revision, g.revision) AS bigint) AS authorization_revision
FROM sessions s
JOIN sessions parent ON parent.id = s.parent_session_id
JOIN users u ON u.id = s.user_id
JOIN user_role_grants g ON g.user_id = u.id AND g.status = 'active'
JOIN authorization_roles r ON r.id = g.role_id AND r.status = 'active'
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permission_codes p ON p.code = rp.permission_code AND p.status = 'active'
WHERE s.token_hash = $1
  AND s.kind = 'client_exchange'
  AND s.client_id = $2
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND parent.kind = 'core'
  AND parent.revoked_at IS NULL
  AND parent.expires_at > now()
  AND u.status = 'active'
  AND rp.permission_code = $3
  AND (
      (g.scope_kind = 'platform')
      OR
      (g.scope_kind = 'product'
       AND $4::text IN ('product', 'resource')
       AND g.product_code = $5::text)
      OR
      (g.scope_kind = 'resource'
       AND $4::text = 'resource'
       AND g.product_code = $5::text
       AND g.resource_type = $6::text
       AND g.resource_id = $7::text)
  )
ORDER BY CASE g.scope_kind WHEN 'resource' THEN 1 WHEN 'product' THEN 2 ELSE 3 END, g.created_at
LIMIT 1
`

type GetAuthorizationGrantParams struct {
	TokenHash      []byte      `json:"token_hash"`
	ClientID       pgtype.Text `json:"client_id"`
	PermissionCode string      `json:"permission_code"`
	ScopeKind      string      `json:"scope_kind"`
	ProductCode    string      `json:"product_code"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     string      `json:"resource_id"`
}

type GetAuthorizationGrantRow struct {
	UserID                pgtype.UUID `json:"user_id"`
	GrantID               pgtype.UUID `json:"grant_id"`
	AuthorizationRevision int64       `json:"authorization_revision"`
}

func (q *Queries) GetAuthorizationGrant(ctx context.Context, arg GetAuthorizationGrantParams) (GetAuthorizationGrantRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizationGrant,
		arg.TokenHash,
		arg.ClientID,
		arg.PermissionCode,
		arg.ScopeKind,
		arg.ProductCode,
		arg.ResourceType,
		arg.ResourceID,
	)
	var i GetAuthorizationGrantRow
	err := row.Scan(&i.UserID, &i.GrantID, &i.AuthorizationRevision)
	return i, err
}

const getExchangeSessionAuthorizationContext = `-- name: GetExchangeSessionAuthorizationContext :one
SELECT s.id, s.user_id, s.client_id,
       s.revoked_at AS session_revoked_at, s.expires_at AS session_expires_at,
       parent.revoked_at AS parent_revoked_at, parent.expires_at AS parent_expires_at,
       u.status AS user_status
FROM sessions s
JOIN sessions parent ON parent.id = s.parent_session_id
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.kind = 'client_exchange'
  AND parent.kind = 'core'
`

type GetExchangeSessionAuthorizationContextRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	ClientID         pgtype.Text        `json:"client_id"`
	SessionRevokedAt pgtype.Timestamptz `json:"session_revoked_at"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
	ParentRevokedAt  pgtype.Timestamptz `json:"parent_revoked_at"`
	ParentExpiresAt  pgtype.Timestamptz `json:"parent_expires_at"`
	UserStatus       string             `json:"user_status"`
}

func (q *Queries) GetExchangeSessionAuthorizationContext(ctx context.Context, tokenHash []byte) (GetExchangeSessionAuthorizationContextRow, error) {
	row := q.db.QueryRow(ctx, getExchangeSessionAuthorizationContext, tokenHash)
	var i GetExchangeSessionAuthorizationContextRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.SessionRevokedAt,
		&i.SessionExpiresAt,
		&i.ParentRevokedAt,
		&i.ParentExpiresAt,
		&i.UserStatus,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, redirect_uris FROM oauth_clients WHERE id = $1
`

type GetOAuthClientRow struct {
	ID           string   `json:"id"`
	RedirectUris []string `json:"redirect_uris"`
}

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (GetOAuthClientRow, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i GetOAuthClientRow
	err := row.Scan(&i.ID, &i.RedirectUris)
	return i, err
}

const getOAuthClientKey = `-- name: GetOAuthClientKey :one
SELECT client_id, key_id, secret_hash, status
FROM oauth_client_keys
WHERE client_id = $1 AND key_id = $2 AND status IN ('active', 'retiring')
`

type GetOAuthClientKeyParams struct {
	ClientID string `json:"client_id"`
	KeyID    string `json:"key_id"`
}

type GetOAuthClientKeyRow struct {
	ClientID   string `json:"client_id"`
	KeyID      string `json:"key_id"`
	SecretHash []byte `json:"secret_hash"`
	Status     string `json:"status"`
}

func (q *Queries) GetOAuthClientKey(ctx context.Context, arg GetOAuthClientKeyParams) (GetOAuthClientKeyRow, error) {
	row := q.db.QueryRow(ctx, getOAuthClientKey, arg.ClientID, arg.KeyID)
	var i GetOAuthClientKeyRow
	err := row.Scan(
		&i.ClientID,
		&i.KeyID,
		&i.SecretHash,
		&i.Status,
	)
	return i, err
}

const getOAuthExchangeIdempotency = `-- name: GetOAuthExchangeIdempotency :one
SELECT request_hash, expires_at
FROM oauth_exchange_idempotency
WHERE client_id = $1 AND idempotency_key = $2 AND expires_at > now()
`

type GetOAuthExchangeIdempotencyParams struct {
	ClientID       string `json:"client_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetOAuthExchangeIdempotencyRow struct {
	RequestHash []byte             `json:"request_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetOAuthExchangeIdempotency(ctx context.Context, arg GetOAuthExchangeIdempotencyParams) (GetOAuthExchangeIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getOAuthExchangeIdempotency, arg.ClientID, arg.IdempotencyKey)
	var i GetOAuthExchangeIdempotencyRow
	err := row.Scan(&i.RequestHash, &i.ExpiresAt)
	return i, err
}

const getPlatformUser = `-- name: GetPlatformUser :one
SELECT id, email_verified, status, created_at FROM users WHERE id = $1
`

type GetPlatformUserRow struct {
	ID            pgtype.UUID        `json:"id"`
	EmailVerified bool               `json:"email_verified"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPlatformUser(ctx context.Context, id pgtype.UUID) (GetPlatformUserRow, error) {
	row := q.db.QueryRow(ctx, getPlatformUser, id)
	var i GetPlatformUserRow
	err := row.Scan(
		&i.ID,
		&i.EmailVerified,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthorizationCodeUsed = `-- name: MarkAuthorizationCodeUsed :execrows
UPDATE authorization_codes SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkAuthorizationCodeUsed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAuthorizationCodeUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchCoreSession = `-- name: TouchCoreSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1 AND kind = 'core'
`

func (q *Queries) TouchCoreSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCoreSession, id)
	return err
}
