// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO authorization_codes (
    code_hash, user_id, client_id, core_session_id, redirect_uri, code_challenge, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateAuthorizationCodeParams struct {
	CodeHash      []byte             `json:"code_hash"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientID      string             `json:"client_id"`
	CoreSessionID pgtype.UUID        `json:"core_session_id"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.CodeHash,
		arg.UserID,
		arg.ClientID,
		arg.CoreSessionID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createExchangeSession = `-- name: CreateExchangeSession :one
INSERT INTO sessions (
    user_id, kind, token_hash, client_id, parent_session_id, expires_at
) VALUES ($1, 'client_exchange', $2, $3, $4, $5)
RETURNING id, expires_at
`

type CreateExchangeSessionParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	TokenHash       []byte             `json:"token_hash"`
	ClientID        pgtype.Text        `json:"client_id"`
	ParentSessionID pgtype.UUID        `json:"parent_session_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type CreateExchangeSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateExchangeSession(ctx context.Context, arg CreateExchangeSessionParams) (CreateExchangeSessionRow, error) {
	row := q.db.QueryRow(ctx, createExchangeSession,
		arg.UserID,
		arg.TokenHash,
		arg.ClientID,
		arg.ParentSessionID,
		arg.ExpiresAt,
	)
	var i CreateExchangeSessionRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const getActiveCoreSessionByTokenHash = `-- name: GetActiveCoreSessionByTokenHash :one
SELECT s.id, s.user_id, s.expires_at, u.email_verified, u.status, u.created_at AS user_created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.kind = 'core'
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
FOR UPDATE OF s, u
`

type GetActiveCoreSessionByTokenHashRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	EmailVerified bool               `json:"email_verified"`
	Status        string             `json:"status"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) GetActiveCoreSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetActiveCoreSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveCoreSessionByTokenHash, tokenHash)
	var i GetActiveCoreSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.EmailVerified,
		&i.Status,
		&i.UserCreatedAt,
	)
	return i, err
}

const getActiveCoreSessionForExchange = `-- name: GetActiveCoreSessionForExchange :one
SELECT s.id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.kind = 'core'
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.status = 'active'
FOR UPDATE OF s, u
`

func (q *Queries) GetActiveCoreSessionForExchange(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveCoreSessionForExchange, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getAuthorizationCodeForUpdate = `-- name: GetAuthorizationCodeForUpdate :one
SELECT id, user_id, client_id, core_session_id, redirect_uri, code_challenge, expires_at, used_at
FROM authorization_codes
WHERE code_hash = $1
FOR UPDATE
`

type GetAuthorizationCodeForUpdateRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientID      string             `json:"client_id"`
	CoreSessionID pgtype.UUID        `json:"core_session_id"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) GetAuthorizationCodeForUpdate(ctx context.Context, codeHash []byte) (GetAuthorizationCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCodeForUpdate, codeHash)
	var i GetAuthorizationCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.CoreSessionID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, secret_hash, redirect_uris FROM oauth_clients WHERE id = $1
`

type GetOAuthClientRow struct {
	ID           string   `json:"id"`
	SecretHash   []byte   `json:"secret_hash"`
	RedirectUris []string `json:"redirect_uris"`
}

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (GetOAuthClientRow, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i GetOAuthClientRow
	err := row.Scan(&i.ID, &i.SecretHash, &i.RedirectUris)
	return i, err
}

const getPlatformUser = `-- name: GetPlatformUser :one
SELECT id, email_verified, status, created_at FROM users WHERE id = $1
`

func (q *Queries) GetPlatformUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getPlatformUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailVerified,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthorizationCodeUsed = `-- name: MarkAuthorizationCodeUsed :execrows
UPDATE authorization_codes SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkAuthorizationCodeUsed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAuthorizationCodeUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchCoreSession = `-- name: TouchCoreSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1 AND kind = 'core'
`

func (q *Queries) TouchCoreSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCoreSession, id)
	return err
}
