// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizationAuditEvent struct {
	ID                    pgtype.UUID        `json:"id"`
	ActorUserID           pgtype.UUID        `json:"actor_user_id"`
	SessionID             pgtype.UUID        `json:"session_id"`
	RequestID             string             `json:"request_id"`
	ServiceID             string             `json:"service_id"`
	PermissionCode        string             `json:"permission_code"`
	TargetKind            string             `json:"target_kind"`
	TargetProductCode     pgtype.Text        `json:"target_product_code"`
	TargetResourceType    pgtype.Text        `json:"target_resource_type"`
	TargetResourceID      pgtype.Text        `json:"target_resource_id"`
	Decision              string             `json:"decision"`
	ReasonCode            string             `json:"reason_code"`
	GrantID               pgtype.UUID        `json:"grant_id"`
	AuthorizationRevision pgtype.Int8        `json:"authorization_revision"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type AuthorizationCode struct {
	ID            pgtype.UUID        `json:"id"`
	CodeHash      []byte             `json:"code_hash"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientID      string             `json:"client_id"`
	CoreSessionID pgtype.UUID        `json:"core_session_id"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuthorizationRole struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	Revision    int64              `json:"revision"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MailOutbox struct {
	ID                  pgtype.UUID        `json:"id"`
	VerificationCodeID  pgtype.UUID        `json:"verification_code_id"`
	DedupeKey           string             `json:"dedupe_key"`
	RequestID           string             `json:"request_id"`
	Kind                string             `json:"kind"`
	Priority            string             `json:"priority"`
	RecipientCiphertext []byte             `json:"recipient_ciphertext"`
	PayloadCiphertext   []byte             `json:"payload_ciphertext"`
	Status              string             `json:"status"`
	AttemptCount        int32              `json:"attempt_count"`
	MaxAttempts         int32              `json:"max_attempts"`
	AvailableAt         pgtype.Timestamptz `json:"available_at"`
	LockedAt            pgtype.Timestamptz `json:"locked_at"`
	LockedBy            pgtype.Text        `json:"locked_by"`
	ProviderMessageID   pgtype.Text        `json:"provider_message_id"`
	AcceptedAt          pgtype.Timestamptz `json:"accepted_at"`
	DeliveredAt         pgtype.Timestamptz `json:"delivered_at"`
	FailedAt            pgtype.Timestamptz `json:"failed_at"`
	LastErrorCode       pgtype.Text        `json:"last_error_code"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type OauthClient struct {
	ID           string             `json:"id"`
	RedirectUris []string           `json:"redirect_uris"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OauthClientKey struct {
	ClientID   string             `json:"client_id"`
	KeyID      string             `json:"key_id"`
	SecretHash []byte             `json:"secret_hash"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OauthExchangeIdempotency struct {
	ClientID           string             `json:"client_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestHash        []byte             `json:"request_hash"`
	ResponseCiphertext []byte             `json:"response_ciphertext"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type PermissionCode struct {
	Code        string             `json:"code"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID         pgtype.UUID        `json:"role_id"`
	PermissionCode string             `json:"permission_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Kind            string             `json:"kind"`
	TokenHash       []byte             `json:"token_hash"`
	ClientID        pgtype.Text        `json:"client_id"`
	ParentSessionID pgtype.UUID        `json:"parent_session_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                    pgtype.UUID        `json:"id"`
	EmailVerified         bool               `json:"email_verified"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	AuthorizationRevision int64              `json:"authorization_revision"`
}

type UserRoleGrant struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RoleID       pgtype.UUID        `json:"role_id"`
	ScopeKind    string             `json:"scope_kind"`
	ProductCode  pgtype.Text        `json:"product_code"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Status       string             `json:"status"`
	Revision     int64              `json:"revision"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VerificationCode struct {
	ID                         pgtype.UUID        `json:"id"`
	EmailLookupHash            []byte             `json:"email_lookup_hash"`
	Purpose                    string             `json:"purpose"`
	RequestKey                 string             `json:"request_key"`
	RequestFingerprint         []byte             `json:"request_fingerprint"`
	CodeNonce                  []byte             `json:"code_nonce"`
	CodeHash                   []byte             `json:"code_hash"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
	UsedAt                     pgtype.Timestamptz `json:"used_at"`
	ConsumedRequestKey         pgtype.Text        `json:"consumed_request_key"`
	ConsumedRequestFingerprint []byte             `json:"consumed_request_fingerprint"`
	RevokedAt                  pgtype.Timestamptz `json:"revoked_at"`
	FailedAttempts             int32              `json:"failed_attempts"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}
