// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizationCode struct {
	ID            pgtype.UUID        `json:"id"`
	CodeHash      []byte             `json:"code_hash"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientID      string             `json:"client_id"`
	CoreSessionID pgtype.UUID        `json:"core_session_id"`
	RedirectUri   string             `json:"redirect_uri"`
	CodeChallenge string             `json:"code_challenge"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OauthClient struct {
	ID           string             `json:"id"`
	RedirectUris []string           `json:"redirect_uris"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OauthClientKey struct {
	ClientID   string             `json:"client_id"`
	KeyID      string             `json:"key_id"`
	SecretHash []byte             `json:"secret_hash"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OauthExchangeIdempotency struct {
	ClientID           string             `json:"client_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestHash        []byte             `json:"request_hash"`
	ResponseCiphertext []byte             `json:"response_ciphertext"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Kind            string             `json:"kind"`
	TokenHash       []byte             `json:"token_hash"`
	ClientID        pgtype.Text        `json:"client_id"`
	ParentSessionID pgtype.UUID        `json:"parent_session_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	EmailVerified bool               `json:"email_verified"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
