// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations_inbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperationsInboxAudit = `-- name: CreateOperationsInboxAudit :exec
INSERT INTO operations_inbox_audit_events (
    item_id, actor_user_id, request_id, action, from_version, to_version, item_snapshot
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOperationsInboxAuditParams struct {
	ItemID       pgtype.UUID `json:"item_id"`
	ActorUserID  pgtype.UUID `json:"actor_user_id"`
	RequestID    string      `json:"request_id"`
	Action       string      `json:"action"`
	FromVersion  pgtype.Int8 `json:"from_version"`
	ToVersion    int64       `json:"to_version"`
	ItemSnapshot []byte      `json:"item_snapshot"`
}

func (q *Queries) CreateOperationsInboxAudit(ctx context.Context, arg CreateOperationsInboxAuditParams) error {
	_, err := q.db.Exec(ctx, createOperationsInboxAudit,
		arg.ItemID,
		arg.ActorUserID,
		arg.RequestID,
		arg.Action,
		arg.FromVersion,
		arg.ToVersion,
		arg.ItemSnapshot,
	)
	return err
}

const createOperationsInboxIdempotency = `-- name: CreateOperationsInboxIdempotency :exec
INSERT INTO operations_inbox_idempotency (
    service_id, actor_user_id, operation, idempotency_key, request_hash, item_id, response_version, response_payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOperationsInboxIdempotencyParams struct {
	ServiceID       string      `json:"service_id"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	Operation       string      `json:"operation"`
	IdempotencyKey  string      `json:"idempotency_key"`
	RequestHash     []byte      `json:"request_hash"`
	ItemID          pgtype.UUID `json:"item_id"`
	ResponseVersion int64       `json:"response_version"`
	ResponsePayload []byte      `json:"response_payload"`
}

func (q *Queries) CreateOperationsInboxIdempotency(ctx context.Context, arg CreateOperationsInboxIdempotencyParams) error {
	_, err := q.db.Exec(ctx, createOperationsInboxIdempotency,
		arg.ServiceID,
		arg.ActorUserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ItemID,
		arg.ResponseVersion,
		arg.ResponsePayload,
	)
	return err
}

const createOperationsInboxItem = `-- name: CreateOperationsInboxItem :one
INSERT INTO operations_inbox_items (
    source_product_code, source_resource_type, source_resource_id, source_resource_url,
    owner_user_id, priority, sla_due_at, status, created_by, updated_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $9
)
RETURNING id, source_product_code, source_resource_type, source_resource_id, source_resource_url, owner_user_id, priority, sla_due_at, status, version, created_by, updated_by, created_at, updated_at
`

type CreateOperationsInboxItemParams struct {
	SourceProductCode  string             `json:"source_product_code"`
	SourceResourceType string             `json:"source_resource_type"`
	SourceResourceID   string             `json:"source_resource_id"`
	SourceResourceUrl  pgtype.Text        `json:"source_resource_url"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	Priority           string             `json:"priority"`
	SlaDueAt           pgtype.Timestamptz `json:"sla_due_at"`
	Status             string             `json:"status"`
	ActorUserID        pgtype.UUID        `json:"actor_user_id"`
}

func (q *Queries) CreateOperationsInboxItem(ctx context.Context, arg CreateOperationsInboxItemParams) (OperationsInboxItem, error) {
	row := q.db.QueryRow(ctx, createOperationsInboxItem,
		arg.SourceProductCode,
		arg.SourceResourceType,
		arg.SourceResourceID,
		arg.SourceResourceUrl,
		arg.OwnerUserID,
		arg.Priority,
		arg.SlaDueAt,
		arg.Status,
		arg.ActorUserID,
	)
	var i OperationsInboxItem
	err := row.Scan(
		&i.ID,
		&i.SourceProductCode,
		&i.SourceResourceType,
		&i.SourceResourceID,
		&i.SourceResourceUrl,
		&i.OwnerUserID,
		&i.Priority,
		&i.SlaDueAt,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationsInboxIdempotency = `-- name: GetOperationsInboxIdempotency :one
SELECT request_hash, item_id, response_version, response_payload
FROM operations_inbox_idempotency
WHERE service_id = $1 AND actor_user_id = $2 AND operation = $3 AND idempotency_key = $4
`

type GetOperationsInboxIdempotencyParams struct {
	ServiceID      string      `json:"service_id"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	Operation      string      `json:"operation"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type GetOperationsInboxIdempotencyRow struct {
	RequestHash     []byte      `json:"request_hash"`
	ItemID          pgtype.UUID `json:"item_id"`
	ResponseVersion int64       `json:"response_version"`
	ResponsePayload []byte      `json:"response_payload"`
}

func (q *Queries) GetOperationsInboxIdempotency(ctx context.Context, arg GetOperationsInboxIdempotencyParams) (GetOperationsInboxIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getOperationsInboxIdempotency,
		arg.ServiceID,
		arg.ActorUserID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i GetOperationsInboxIdempotencyRow
	err := row.Scan(
		&i.RequestHash,
		&i.ItemID,
		&i.ResponseVersion,
		&i.ResponsePayload,
	)
	return i, err
}

const getOperationsInboxItem = `-- name: GetOperationsInboxItem :one
SELECT id, source_product_code, source_resource_type, source_resource_id, source_resource_url, owner_user_id, priority, sla_due_at, status, version, created_by, updated_by, created_at, updated_at FROM operations_inbox_items WHERE id = $1
`

func (q *Queries) GetOperationsInboxItem(ctx context.Context, id pgtype.UUID) (OperationsInboxItem, error) {
	row := q.db.QueryRow(ctx, getOperationsInboxItem, id)
	var i OperationsInboxItem
	err := row.Scan(
		&i.ID,
		&i.SourceProductCode,
		&i.SourceResourceType,
		&i.SourceResourceID,
		&i.SourceResourceUrl,
		&i.OwnerUserID,
		&i.Priority,
		&i.SlaDueAt,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationsInboxOperationStatus = `-- name: GetOperationsInboxOperationStatus :one
SELECT response_payload
FROM operations_inbox_idempotency
WHERE service_id = $1 AND actor_user_id = $2 AND operation = $3 AND idempotency_key = $4
`

type GetOperationsInboxOperationStatusParams struct {
	ServiceID      string      `json:"service_id"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	Operation      string      `json:"operation"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetOperationsInboxOperationStatus(ctx context.Context, arg GetOperationsInboxOperationStatusParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOperationsInboxOperationStatus,
		arg.ServiceID,
		arg.ActorUserID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var response_payload []byte
	err := row.Scan(&response_payload)
	return response_payload, err
}

const listOperationsInboxItems = `-- name: ListOperationsInboxItems :many
SELECT id, source_product_code, source_resource_type, source_resource_id, source_resource_url, owner_user_id, priority, sla_due_at, status, version, created_by, updated_by, created_at, updated_at FROM operations_inbox_items
WHERE source_product_code = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY updated_at DESC, id
LIMIT $4
OFFSET $3
`

type ListOperationsInboxItemsParams struct {
	SourceProductCode string      `json:"source_product_code"`
	Status            pgtype.Text `json:"status"`
	PageOffset        int32       `json:"page_offset"`
	PageSize          int32       `json:"page_size"`
}

func (q *Queries) ListOperationsInboxItems(ctx context.Context, arg ListOperationsInboxItemsParams) ([]OperationsInboxItem, error) {
	rows, err := q.db.Query(ctx, listOperationsInboxItems,
		arg.SourceProductCode,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationsInboxItem{}
	for rows.Next() {
		var i OperationsInboxItem
		if err := rows.Scan(
			&i.ID,
			&i.SourceProductCode,
			&i.SourceResourceType,
			&i.SourceResourceID,
			&i.SourceResourceUrl,
			&i.OwnerUserID,
			&i.Priority,
			&i.SlaDueAt,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOperationsInboxItem = `-- name: UpdateOperationsInboxItem :one
UPDATE operations_inbox_items SET
    owner_user_id = CASE WHEN $1::boolean THEN $2 ELSE owner_user_id END,
    priority = COALESCE($3::text, priority),
    sla_due_at = CASE WHEN $4::boolean THEN $5 ELSE sla_due_at END,
    status = COALESCE($6::text, status),
    version = version + 1,
    updated_by = $7,
    updated_at = now()
WHERE id = $8 AND version = $9
RETURNING id, source_product_code, source_resource_type, source_resource_id, source_resource_url, owner_user_id, priority, sla_due_at, status, version, created_by, updated_by, created_at, updated_at
`

type UpdateOperationsInboxItemParams struct {
	SetOwner        bool               `json:"set_owner"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	Priority        pgtype.Text        `json:"priority"`
	SetSla          bool               `json:"set_sla"`
	SlaDueAt        pgtype.Timestamptz `json:"sla_due_at"`
	Status          pgtype.Text        `json:"status"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	ID              pgtype.UUID        `json:"id"`
	ExpectedVersion int64              `json:"expected_version"`
}

func (q *Queries) UpdateOperationsInboxItem(ctx context.Context, arg UpdateOperationsInboxItemParams) (OperationsInboxItem, error) {
	row := q.db.QueryRow(ctx, updateOperationsInboxItem,
		arg.SetOwner,
		arg.OwnerUserID,
		arg.Priority,
		arg.SetSla,
		arg.SlaDueAt,
		arg.Status,
		arg.ActorUserID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i OperationsInboxItem
	err := row.Scan(
		&i.ID,
		&i.SourceProductCode,
		&i.SourceResourceType,
		&i.SourceResourceID,
		&i.SourceResourceUrl,
		&i.OwnerUserID,
		&i.Priority,
		&i.SlaDueAt,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
