// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_operations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlatformOperationMailStatuses = `-- name: CountPlatformOperationMailStatuses :one
SELECT
    count(*) FILTER (WHERE status = 'pending')::bigint AS pending,
    count(*) FILTER (WHERE status = 'processing')::bigint AS processing,
    count(*) FILTER (WHERE status = 'retry_due')::bigint AS retry_due,
    count(*) FILTER (WHERE status = 'accepted')::bigint AS accepted,
    count(*) FILTER (WHERE status = 'delivered')::bigint AS delivered,
    count(*) FILTER (WHERE status = 'failed')::bigint AS failed,
    (SELECT count(*)::bigint FROM mail_dead_letters WHERE requeued_at IS NULL) AS dead_letters
FROM mail_outbox
`

type CountPlatformOperationMailStatusesRow struct {
	Pending     int64 `json:"pending"`
	Processing  int64 `json:"processing"`
	RetryDue    int64 `json:"retry_due"`
	Accepted    int64 `json:"accepted"`
	Delivered   int64 `json:"delivered"`
	Failed      int64 `json:"failed"`
	DeadLetters int64 `json:"dead_letters"`
}

func (q *Queries) CountPlatformOperationMailStatuses(ctx context.Context) (CountPlatformOperationMailStatusesRow, error) {
	row := q.db.QueryRow(ctx, countPlatformOperationMailStatuses)
	var i CountPlatformOperationMailStatusesRow
	err := row.Scan(
		&i.Pending,
		&i.Processing,
		&i.RetryDue,
		&i.Accepted,
		&i.Delivered,
		&i.Failed,
		&i.DeadLetters,
	)
	return i, err
}

const createPlatformOperationAudit = `-- name: CreatePlatformOperationAudit :exec
INSERT INTO platform_operations_audit_events (
    actor_user_id, request_id, operation, resource_kind, resource_id, result_payload
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePlatformOperationAuditParams struct {
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	RequestID     string      `json:"request_id"`
	Operation     string      `json:"operation"`
	ResourceKind  string      `json:"resource_kind"`
	ResourceID    pgtype.UUID `json:"resource_id"`
	ResultPayload []byte      `json:"result_payload"`
}

func (q *Queries) CreatePlatformOperationAudit(ctx context.Context, arg CreatePlatformOperationAuditParams) error {
	_, err := q.db.Exec(ctx, createPlatformOperationAudit,
		arg.ActorUserID,
		arg.RequestID,
		arg.Operation,
		arg.ResourceKind,
		arg.ResourceID,
		arg.ResultPayload,
	)
	return err
}

const createPlatformOperationIdempotency = `-- name: CreatePlatformOperationIdempotency :exec
INSERT INTO platform_operations_idempotency (
    service_id, actor_user_id, operation, idempotency_key, request_hash, response_payload
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePlatformOperationIdempotencyParams struct {
	ServiceID       string      `json:"service_id"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	Operation       string      `json:"operation"`
	IdempotencyKey  string      `json:"idempotency_key"`
	RequestHash     []byte      `json:"request_hash"`
	ResponsePayload []byte      `json:"response_payload"`
}

func (q *Queries) CreatePlatformOperationIdempotency(ctx context.Context, arg CreatePlatformOperationIdempotencyParams) error {
	_, err := q.db.Exec(ctx, createPlatformOperationIdempotency,
		arg.ServiceID,
		arg.ActorUserID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResponsePayload,
	)
	return err
}

const createPlatformOperationUserGrant = `-- name: CreatePlatformOperationUserGrant :exec
INSERT INTO user_role_grants (
    user_id, role_id, scope_kind, product_code, resource_type, resource_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreatePlatformOperationUserGrantParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	RoleID       pgtype.UUID `json:"role_id"`
	ScopeKind    string      `json:"scope_kind"`
	ProductCode  pgtype.Text `json:"product_code"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
}

func (q *Queries) CreatePlatformOperationUserGrant(ctx context.Context, arg CreatePlatformOperationUserGrantParams) error {
	_, err := q.db.Exec(ctx, createPlatformOperationUserGrant,
		arg.UserID,
		arg.RoleID,
		arg.ScopeKind,
		arg.ProductCode,
		arg.ResourceType,
		arg.ResourceID,
	)
	return err
}

const getPlatformOperationAccountByEmailLookupHash = `-- name: GetPlatformOperationAccountByEmailLookupHash :one
SELECT users.id, users.display_name, users.status
FROM email_identities
JOIN users ON users.id = email_identities.user_id
WHERE email_identities.email_lookup_hash = $1
`

type GetPlatformOperationAccountByEmailLookupHashRow struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Status      string      `json:"status"`
}

func (q *Queries) GetPlatformOperationAccountByEmailLookupHash(ctx context.Context, emailLookupHash []byte) (GetPlatformOperationAccountByEmailLookupHashRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOperationAccountByEmailLookupHash, emailLookupHash)
	var i GetPlatformOperationAccountByEmailLookupHashRow
	err := row.Scan(&i.ID, &i.DisplayName, &i.Status)
	return i, err
}

const getPlatformOperationIdempotency = `-- name: GetPlatformOperationIdempotency :one
SELECT request_hash, response_payload
FROM platform_operations_idempotency
WHERE service_id = $1 AND actor_user_id = $2 AND operation = $3 AND idempotency_key = $4
`

type GetPlatformOperationIdempotencyParams struct {
	ServiceID      string      `json:"service_id"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	Operation      string      `json:"operation"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type GetPlatformOperationIdempotencyRow struct {
	RequestHash     []byte `json:"request_hash"`
	ResponsePayload []byte `json:"response_payload"`
}

func (q *Queries) GetPlatformOperationIdempotency(ctx context.Context, arg GetPlatformOperationIdempotencyParams) (GetPlatformOperationIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOperationIdempotency,
		arg.ServiceID,
		arg.ActorUserID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i GetPlatformOperationIdempotencyRow
	err := row.Scan(&i.RequestHash, &i.ResponsePayload)
	return i, err
}

const getPlatformOperationRoleByCode = `-- name: GetPlatformOperationRoleByCode :one
SELECT id
FROM authorization_roles
WHERE code = $1 AND status = 'active'
`

func (q *Queries) GetPlatformOperationRoleByCode(ctx context.Context, code string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPlatformOperationRoleByCode, code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPlatformOperationSession = `-- name: GetPlatformOperationSession :one
SELECT id, user_id, revoked_at, expires_at
FROM sessions
WHERE id = $1
`

type GetPlatformOperationSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetPlatformOperationSession(ctx context.Context, id pgtype.UUID) (GetPlatformOperationSessionRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOperationSession, id)
	var i GetPlatformOperationSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPlatformOperationUser = `-- name: GetPlatformOperationUser :one
SELECT id, authorization_revision
FROM users
WHERE id = $1
`

type GetPlatformOperationUserRow struct {
	ID                    pgtype.UUID `json:"id"`
	AuthorizationRevision int64       `json:"authorization_revision"`
}

func (q *Queries) GetPlatformOperationUser(ctx context.Context, id pgtype.UUID) (GetPlatformOperationUserRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOperationUser, id)
	var i GetPlatformOperationUserRow
	err := row.Scan(&i.ID, &i.AuthorizationRevision)
	return i, err
}

const listPlatformOperationAccountGrants = `-- name: ListPlatformOperationAccountGrants :many
SELECT grants.user_id, roles.code AS role_code, grants.scope_kind,
       grants.product_code, grants.resource_type, grants.resource_id
FROM user_role_grants AS grants
JOIN authorization_roles AS roles ON roles.id = grants.role_id
WHERE grants.status = 'active'
  AND grants.user_id IN (
      SELECT id FROM users ORDER BY created_at DESC, id LIMIT 20
  )
ORDER BY grants.user_id, roles.code, grants.scope_kind,
         grants.product_code NULLS FIRST, grants.resource_type NULLS FIRST,
         grants.resource_id NULLS FIRST
`

type ListPlatformOperationAccountGrantsRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	RoleCode     string      `json:"role_code"`
	ScopeKind    string      `json:"scope_kind"`
	ProductCode  pgtype.Text `json:"product_code"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
}

func (q *Queries) ListPlatformOperationAccountGrants(ctx context.Context) ([]ListPlatformOperationAccountGrantsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformOperationAccountGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformOperationAccountGrantsRow{}
	for rows.Next() {
		var i ListPlatformOperationAccountGrantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.RoleCode,
			&i.ScopeKind,
			&i.ProductCode,
			&i.ResourceType,
			&i.ResourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformOperationAccounts = `-- name: ListPlatformOperationAccounts :many
SELECT id, display_name, email_verified, status, authorization_revision, created_at
FROM users
ORDER BY created_at DESC, id
LIMIT 20
`

type ListPlatformOperationAccountsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	DisplayName           pgtype.Text        `json:"display_name"`
	EmailVerified         bool               `json:"email_verified"`
	Status                string             `json:"status"`
	AuthorizationRevision int64              `json:"authorization_revision"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPlatformOperationAccounts(ctx context.Context) ([]ListPlatformOperationAccountsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformOperationAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformOperationAccountsRow{}
	for rows.Next() {
		var i ListPlatformOperationAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.EmailVerified,
			&i.Status,
			&i.AuthorizationRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformOperationAuditEvents = `-- name: ListPlatformOperationAuditEvents :many
SELECT events.request_id, events.actor_user_id, users.display_name,
       events.permission_code, events.target_kind,
       events.target_product_code, events.target_resource_type,
       events.target_resource_id, events.decision, events.reason_code,
       events.created_at
FROM (
    SELECT request_id, actor_user_id, permission_code, target_kind,
           target_product_code, target_resource_type, target_resource_id,
           decision, reason_code, created_at
    FROM authorization_audit_events
    UNION ALL
    SELECT request_id, actor_user_id, 'platform.operations.write'::text,
           'resource'::text, NULL::text, resource_kind,
           resource_id::text, 'allowed'::text, operation || '_succeeded', created_at
    FROM platform_operations_audit_events
) AS events
LEFT JOIN users ON users.id = events.actor_user_id
ORDER BY events.created_at DESC, events.request_id
LIMIT 20
`

type ListPlatformOperationAuditEventsRow struct {
	RequestID          string             `json:"request_id"`
	ActorUserID        pgtype.UUID        `json:"actor_user_id"`
	DisplayName        pgtype.Text        `json:"display_name"`
	PermissionCode     string             `json:"permission_code"`
	TargetKind         string             `json:"target_kind"`
	TargetProductCode  pgtype.Text        `json:"target_product_code"`
	TargetResourceType pgtype.Text        `json:"target_resource_type"`
	TargetResourceID   pgtype.Text        `json:"target_resource_id"`
	Decision           string             `json:"decision"`
	ReasonCode         string             `json:"reason_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPlatformOperationAuditEvents(ctx context.Context) ([]ListPlatformOperationAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformOperationAuditEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformOperationAuditEventsRow{}
	for rows.Next() {
		var i ListPlatformOperationAuditEventsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.ActorUserID,
			&i.DisplayName,
			&i.PermissionCode,
			&i.TargetKind,
			&i.TargetProductCode,
			&i.TargetResourceType,
			&i.TargetResourceID,
			&i.Decision,
			&i.ReasonCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformOperationInboxItems = `-- name: ListPlatformOperationInboxItems :many
SELECT id, source_product_code, source_resource_type, source_resource_id,
       source_resource_url, owner_user_id, priority, sla_due_at, status,
       version, created_at, updated_at
FROM operations_inbox_items
ORDER BY updated_at DESC, id
LIMIT 20
`

type ListPlatformOperationInboxItemsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SourceProductCode  string             `json:"source_product_code"`
	SourceResourceType string             `json:"source_resource_type"`
	SourceResourceID   string             `json:"source_resource_id"`
	SourceResourceUrl  pgtype.Text        `json:"source_resource_url"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	Priority           string             `json:"priority"`
	SlaDueAt           pgtype.Timestamptz `json:"sla_due_at"`
	Status             string             `json:"status"`
	Version            int64              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlatformOperationInboxItems(ctx context.Context) ([]ListPlatformOperationInboxItemsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformOperationInboxItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformOperationInboxItemsRow{}
	for rows.Next() {
		var i ListPlatformOperationInboxItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceProductCode,
			&i.SourceResourceType,
			&i.SourceResourceID,
			&i.SourceResourceUrl,
			&i.OwnerUserID,
			&i.Priority,
			&i.SlaDueAt,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformOperationSessions = `-- name: ListPlatformOperationSessions :many
SELECT sessions.id, sessions.user_id, users.display_name, sessions.kind,
       sessions.client_id, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at
FROM sessions
LEFT JOIN users ON users.id = sessions.user_id
ORDER BY sessions.created_at DESC, sessions.id
LIMIT 20
`

type ListPlatformOperationSessionsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	DisplayName pgtype.Text        `json:"display_name"`
	Kind        string             `json:"kind"`
	ClientID    pgtype.Text        `json:"client_id"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListPlatformOperationSessions(ctx context.Context) ([]ListPlatformOperationSessionsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformOperationSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformOperationSessionsRow{}
	for rows.Next() {
		var i ListPlatformOperationSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Kind,
			&i.ClientID,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePlatformOperationSession = `-- name: RevokePlatformOperationSession :one
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL AND expires_at > now()
RETURNING id
`

func (q *Queries) RevokePlatformOperationSession(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, revokePlatformOperationSession, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const revokePlatformOperationUserGrants = `-- name: RevokePlatformOperationUserGrants :exec
UPDATE user_role_grants
SET status = 'revoked', revision = revision + 1, revoked_at = now(), updated_at = now()
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) RevokePlatformOperationUserGrants(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokePlatformOperationUserGrants, userID)
	return err
}

const updatePlatformOperationUser = `-- name: UpdatePlatformOperationUser :one
UPDATE users
SET status = $1, authorization_revision = authorization_revision + 1
WHERE id = $2 AND authorization_revision = $3
RETURNING authorization_revision
`

type UpdatePlatformOperationUserParams struct {
	Status           string      `json:"status"`
	UserID           pgtype.UUID `json:"user_id"`
	ExpectedRevision int64       `json:"expected_revision"`
}

func (q *Queries) UpdatePlatformOperationUser(ctx context.Context, arg UpdatePlatformOperationUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, updatePlatformOperationUser, arg.Status, arg.UserID, arg.ExpectedRevision)
	var authorization_revision int64
	err := row.Scan(&authorization_revision)
	return authorization_revision, err
}
