// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_mail.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptMailOutbox = `-- name: AcceptMailOutbox :execrows
WITH transitioned AS (
    UPDATE mail_outbox AS job
    SET status = 'accepted', locked_at = NULL, locked_by = NULL,
        provider_message_id = $2, accepted_at = now(),
        last_error_code = NULL, updated_at = now()
    WHERE job.id = $3 AND job.status = 'processing' AND job.locked_by = $1
    RETURNING job.id, job.request_id, job.attempt_count
)
INSERT INTO mail_outbox_audit_events (
    outbox_id, request_id, actor_kind, actor_id, action, attempt_count
)
SELECT id, request_id, 'worker', $1, 'accepted', attempt_count
FROM transitioned
`

type AcceptMailOutboxParams struct {
	WorkerID          string      `json:"worker_id"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
	OutboxID          pgtype.UUID `json:"outbox_id"`
}

func (q *Queries) AcceptMailOutbox(ctx context.Context, arg AcceptMailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptMailOutbox, arg.WorkerID, arg.ProviderMessageID, arg.OutboxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyAllPendingMailDeliveryReceipts = `-- name: ApplyAllPendingMailDeliveryReceipts :exec
WITH candidates AS (
    SELECT receipt.message_id, receipt.request_id, receipt.actor_id
    FROM mail_delivery_receipts AS receipt
    JOIN mail_outbox AS job ON job.provider_message_id = receipt.message_id
    WHERE receipt.applied_at IS NULL AND job.status = 'accepted'
    ORDER BY receipt.received_at
    FOR UPDATE OF receipt SKIP LOCKED
    LIMIT 50
), transitioned AS (
    UPDATE mail_outbox AS job
    SET status = 'delivered', delivered_at = now(), updated_at = now()
    FROM candidates
    WHERE candidates.message_id = job.provider_message_id AND job.status = 'accepted'
    RETURNING job.id, job.attempt_count, candidates.message_id, candidates.request_id, candidates.actor_id
), audited AS (
    INSERT INTO mail_outbox_audit_events (
        outbox_id, request_id, actor_kind, actor_id, action, attempt_count
    )
    SELECT id, request_id, 'provider', actor_id, 'delivered', attempt_count
    FROM transitioned
    RETURNING outbox_id
)
UPDATE mail_delivery_receipts AS receipt
SET applied_outbox_id = transitioned.id, applied_at = now()
FROM transitioned
JOIN audited ON audited.outbox_id = transitioned.id
WHERE receipt.message_id = transitioned.message_id
`

func (q *Queries) ApplyAllPendingMailDeliveryReceipts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, applyAllPendingMailDeliveryReceipts)
	return err
}

const applyPendingMailDeliveryReceipt = `-- name: ApplyPendingMailDeliveryReceipt :execrows
WITH transitioned AS (
    UPDATE mail_outbox AS job
    SET status = 'delivered', delivered_at = now(), updated_at = now()
    FROM mail_delivery_receipts AS receipt
    WHERE job.provider_message_id = $1
      AND receipt.message_id = job.provider_message_id
      AND receipt.applied_at IS NULL AND job.status = 'accepted'
    RETURNING job.id, job.attempt_count, receipt.message_id, receipt.request_id, receipt.actor_id
), audited AS (
    INSERT INTO mail_outbox_audit_events (
        outbox_id, request_id, actor_kind, actor_id, action, attempt_count
    )
    SELECT id, request_id, 'provider', actor_id, 'delivered', attempt_count
    FROM transitioned
    RETURNING outbox_id
)
UPDATE mail_delivery_receipts AS receipt
SET applied_outbox_id = transitioned.id, applied_at = now()
FROM transitioned
JOIN audited ON audited.outbox_id = transitioned.id
WHERE receipt.message_id = transitioned.message_id
`

func (q *Queries) ApplyPendingMailDeliveryReceipt(ctx context.Context, messageID pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, applyPendingMailDeliveryReceipt, messageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const attachLoginSessionToVerification = `-- name: AttachLoginSessionToVerification :execrows
UPDATE verification_codes
SET login_session_id = $2, login_session_token_ciphertext = ''::bytea
WHERE id = $1 AND used_at IS NOT NULL AND purpose IN ('register', 'login') AND login_session_id IS NULL
`

type AttachLoginSessionToVerificationParams struct {
	ID             pgtype.UUID `json:"id"`
	LoginSessionID pgtype.UUID `json:"login_session_id"`
}

func (q *Queries) AttachLoginSessionToVerification(ctx context.Context, arg AttachLoginSessionToVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachLoginSessionToVerification, arg.ID, arg.LoginSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimMailOutbox = `-- name: ClaimMailOutbox :one
WITH candidate AS (
    SELECT candidate_job.id
    FROM mail_outbox AS candidate_job
    WHERE (
        (candidate_job.status IN ('pending', 'retry_due') AND candidate_job.available_at <= now())
        OR (candidate_job.status = 'processing' AND candidate_job.locked_at < $1)
    )
      AND candidate_job.attempt_count < candidate_job.max_attempts
    ORDER BY CASE candidate_job.priority WHEN 'critical' THEN 1 ELSE 2 END, candidate_job.available_at, candidate_job.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
), claimed AS (
    UPDATE mail_outbox AS job
    SET status = 'processing', attempt_count = attempt_count + 1,
        locked_at = now(), locked_by = $2, updated_at = now()
    FROM candidate
    WHERE job.id = candidate.id
    RETURNING job.id, job.dedupe_key, job.request_id, job.recipient_ciphertext, job.payload_ciphertext,
              job.attempt_count, job.max_attempts
), audited AS (
    INSERT INTO mail_outbox_audit_events (
        outbox_id, request_id, actor_kind, actor_id, action, attempt_count
    )
    SELECT id, request_id, 'worker', $2, 'claimed', attempt_count
    FROM claimed
    RETURNING outbox_id
)
SELECT claimed.id, claimed.dedupe_key, claimed.request_id,
       claimed.recipient_ciphertext, claimed.payload_ciphertext,
       claimed.attempt_count, claimed.max_attempts
FROM claimed
JOIN audited ON audited.outbox_id = claimed.id
`

type ClaimMailOutboxParams struct {
	ReclaimBefore pgtype.Timestamptz `json:"reclaim_before"`
	WorkerID      pgtype.Text        `json:"worker_id"`
}

type ClaimMailOutboxRow struct {
	ID                  pgtype.UUID `json:"id"`
	DedupeKey           string      `json:"dedupe_key"`
	RequestID           string      `json:"request_id"`
	RecipientCiphertext []byte      `json:"recipient_ciphertext"`
	PayloadCiphertext   []byte      `json:"payload_ciphertext"`
	AttemptCount        int32       `json:"attempt_count"`
	MaxAttempts         int32       `json:"max_attempts"`
}

func (q *Queries) ClaimMailOutbox(ctx context.Context, arg ClaimMailOutboxParams) (ClaimMailOutboxRow, error) {
	row := q.db.QueryRow(ctx, claimMailOutbox, arg.ReclaimBefore, arg.WorkerID)
	var i ClaimMailOutboxRow
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.RequestID,
		&i.RecipientCiphertext,
		&i.PayloadCiphertext,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}

const consumeVerificationCode = `-- name: ConsumeVerificationCode :execrows
UPDATE verification_codes
SET used_at = now(), consumed_request_key = $2, consumed_request_fingerprint = $3
WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

type ConsumeVerificationCodeParams struct {
	ID                         pgtype.UUID `json:"id"`
	ConsumedRequestKey         pgtype.Text `json:"consumed_request_key"`
	ConsumedRequestFingerprint []byte      `json:"consumed_request_fingerprint"`
}

func (q *Queries) ConsumeVerificationCode(ctx context.Context, arg ConsumeVerificationCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerificationCode, arg.ID, arg.ConsumedRequestKey, arg.ConsumedRequestFingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCoreSession = `-- name: CreateCoreSession :one
INSERT INTO sessions (user_id, kind, token_hash, expires_at)
VALUES ($1, 'core', $2, $3)
RETURNING id, expires_at
`

type CreateCoreSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateCoreSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCoreSession(ctx context.Context, arg CreateCoreSessionParams) (CreateCoreSessionRow, error) {
	row := q.db.QueryRow(ctx, createCoreSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i CreateCoreSessionRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const createEmailIdentity = `-- name: CreateEmailIdentity :exec
INSERT INTO email_identities (user_id, email_lookup_hash, email_ciphertext, verified_at)
VALUES ($1, $2, $3, now())
`

type CreateEmailIdentityParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	EmailLookupHash []byte      `json:"email_lookup_hash"`
	EmailCiphertext []byte      `json:"email_ciphertext"`
}

func (q *Queries) CreateEmailIdentity(ctx context.Context, arg CreateEmailIdentityParams) error {
	_, err := q.db.Exec(ctx, createEmailIdentity, arg.UserID, arg.EmailLookupHash, arg.EmailCiphertext)
	return err
}

const createEmailLoginUser = `-- name: CreateEmailLoginUser :one
INSERT INTO users (email_verified, status)
VALUES (true, 'active')
RETURNING id, email_verified, status, created_at
`

type CreateEmailLoginUserRow struct {
	ID            pgtype.UUID        `json:"id"`
	EmailVerified bool               `json:"email_verified"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEmailLoginUser(ctx context.Context) (CreateEmailLoginUserRow, error) {
	row := q.db.QueryRow(ctx, createEmailLoginUser)
	var i CreateEmailLoginUserRow
	err := row.Scan(
		&i.ID,
		&i.EmailVerified,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordCredential = `-- name: CreatePasswordCredential :exec
INSERT INTO password_credentials (user_id, verifier, policy_version)
VALUES ($1, $2, $3)
`

type CreatePasswordCredentialParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Verifier      string      `json:"verifier"`
	PolicyVersion int32       `json:"policy_version"`
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, createPasswordCredential, arg.UserID, arg.Verifier, arg.PolicyVersion)
	return err
}

const createRegisteredUser = `-- name: CreateRegisteredUser :one
INSERT INTO users (email_verified, status, display_name)
VALUES (true, 'active', $1)
RETURNING id, email_verified, status, created_at, display_name
`

type CreateRegisteredUserRow struct {
	ID            pgtype.UUID        `json:"id"`
	EmailVerified bool               `json:"email_verified"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DisplayName   pgtype.Text        `json:"display_name"`
}

func (q *Queries) CreateRegisteredUser(ctx context.Context, displayName pgtype.Text) (CreateRegisteredUserRow, error) {
	row := q.db.QueryRow(ctx, createRegisteredUser, displayName)
	var i CreateRegisteredUserRow
	err := row.Scan(
		&i.ID,
		&i.EmailVerified,
		&i.Status,
		&i.CreatedAt,
		&i.DisplayName,
	)
	return i, err
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (
    email_lookup_hash, purpose, request_key, request_fingerprint,
    code_nonce, code_hash, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, expires_at, created_at
`

type CreateVerificationCodeParams struct {
	EmailLookupHash    []byte             `json:"email_lookup_hash"`
	Purpose            string             `json:"purpose"`
	RequestKey         pgtype.Text        `json:"request_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	CodeNonce          []byte             `json:"code_nonce"`
	CodeHash           []byte             `json:"code_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

type CreateVerificationCodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (CreateVerificationCodeRow, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.EmailLookupHash,
		arg.Purpose,
		arg.RequestKey,
		arg.RequestFingerprint,
		arg.CodeNonce,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i CreateVerificationCodeRow
	err := row.Scan(&i.ID, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const createVerificationMailOutbox = `-- name: CreateVerificationMailOutbox :one
INSERT INTO mail_outbox (
    verification_code_id, dedupe_key, request_id, kind, priority,
    recipient_ciphertext, payload_ciphertext
) VALUES ($1, $2, $3, 'verification_code', 'critical', $4, $5)
RETURNING id
`

type CreateVerificationMailOutboxParams struct {
	VerificationCodeID  pgtype.UUID `json:"verification_code_id"`
	DedupeKey           string      `json:"dedupe_key"`
	RequestID           string      `json:"request_id"`
	RecipientCiphertext []byte      `json:"recipient_ciphertext"`
	PayloadCiphertext   []byte      `json:"payload_ciphertext"`
}

func (q *Queries) CreateVerificationMailOutbox(ctx context.Context, arg CreateVerificationMailOutboxParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createVerificationMailOutbox,
		arg.VerificationCodeID,
		arg.DedupeKey,
		arg.RequestID,
		arg.RecipientCiphertext,
		arg.PayloadCiphertext,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredOAuthExchangeIdempotency = `-- name: DeleteExpiredOAuthExchangeIdempotency :execrows
DELETE FROM oauth_exchange_idempotency
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredOAuthExchangeIdempotency(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthExchangeIdempotency, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failExhaustedOutboxLeases = `-- name: FailExhaustedOutboxLeases :exec
WITH transitioned AS (
    UPDATE mail_outbox AS job
    SET status = 'failed', locked_at = NULL, locked_by = NULL,
        failed_at = now(), last_error_code = 'WORKER_LEASE_EXHAUSTED', updated_at = now()
    WHERE job.status = 'processing' AND job.locked_at < $1 AND job.attempt_count >= job.max_attempts
    RETURNING job.id, job.request_id, job.attempt_count
), dead_lettered AS (
    INSERT INTO mail_dead_letters (outbox_id, attempt_count, error_code)
    SELECT id, attempt_count, 'WORKER_LEASE_EXHAUSTED' FROM transitioned
    RETURNING outbox_id
)
INSERT INTO mail_outbox_audit_events (
    outbox_id, request_id, actor_kind, actor_id, action, attempt_count, reason_code
)
SELECT transitioned.id, transitioned.request_id, 'system', 'lease-recovery', 'failed',
       transitioned.attempt_count, 'WORKER_LEASE_EXHAUSTED'
FROM transitioned
JOIN dead_lettered ON dead_lettered.outbox_id = transitioned.id
`

func (q *Queries) FailExhaustedOutboxLeases(ctx context.Context, lockedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, failExhaustedOutboxLeases, lockedAt)
	return err
}

const failMailOutbox = `-- name: FailMailOutbox :execrows
WITH transitioned AS (
    UPDATE mail_outbox AS job
    SET status = 'failed', locked_at = NULL, locked_by = NULL,
        failed_at = now(), last_error_code = $2, updated_at = now()
    WHERE job.id = $3 AND job.status = 'processing' AND job.locked_by = $1
    RETURNING job.id, job.request_id, job.attempt_count, job.last_error_code
), dead_lettered AS (
    INSERT INTO mail_dead_letters (outbox_id, attempt_count, error_code)
    SELECT id, attempt_count, last_error_code FROM transitioned
    RETURNING outbox_id
)
INSERT INTO mail_outbox_audit_events (
    outbox_id, request_id, actor_kind, actor_id, action, attempt_count, reason_code
)
SELECT transitioned.id, transitioned.request_id, 'worker', $1, 'failed',
       transitioned.attempt_count, transitioned.last_error_code
FROM transitioned
JOIN dead_lettered ON dead_lettered.outbox_id = transitioned.id
`

type FailMailOutboxParams struct {
	WorkerID      string      `json:"worker_id"`
	LastErrorCode pgtype.Text `json:"last_error_code"`
	OutboxID      pgtype.UUID `json:"outbox_id"`
}

func (q *Queries) FailMailOutbox(ctx context.Context, arg FailMailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, failMailOutbox, arg.WorkerID, arg.LastErrorCode, arg.OutboxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConsumedVerificationReplay = `-- name: GetConsumedVerificationReplay :one
SELECT verification_codes.id, verification_codes.consumed_request_fingerprint,
       sessions.expires_at AS login_session_expires_at,
       users.id AS login_user_id, users.email_verified AS login_user_email_verified,
       users.status AS login_user_status, users.created_at AS login_user_created_at
FROM verification_codes
LEFT JOIN sessions ON sessions.id = verification_codes.login_session_id
LEFT JOIN users ON users.id = sessions.user_id
WHERE consumed_request_key = $1 AND used_at IS NOT NULL
`

type GetConsumedVerificationReplayRow struct {
	ID                         pgtype.UUID        `json:"id"`
	ConsumedRequestFingerprint []byte             `json:"consumed_request_fingerprint"`
	LoginSessionExpiresAt      pgtype.Timestamptz `json:"login_session_expires_at"`
	LoginUserID                pgtype.UUID        `json:"login_user_id"`
	LoginUserEmailVerified     pgtype.Bool        `json:"login_user_email_verified"`
	LoginUserStatus            pgtype.Text        `json:"login_user_status"`
	LoginUserCreatedAt         pgtype.Timestamptz `json:"login_user_created_at"`
}

func (q *Queries) GetConsumedVerificationReplay(ctx context.Context, consumedRequestKey pgtype.Text) (GetConsumedVerificationReplayRow, error) {
	row := q.db.QueryRow(ctx, getConsumedVerificationReplay, consumedRequestKey)
	var i GetConsumedVerificationReplayRow
	err := row.Scan(
		&i.ID,
		&i.ConsumedRequestFingerprint,
		&i.LoginSessionExpiresAt,
		&i.LoginUserID,
		&i.LoginUserEmailVerified,
		&i.LoginUserStatus,
		&i.LoginUserCreatedAt,
	)
	return i, err
}

const getCoreSessionByTokenHash = `-- name: GetCoreSessionByTokenHash :one
SELECT sessions.id, sessions.user_id, sessions.expires_at, users.status
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.kind = 'core' AND sessions.token_hash = $1 AND sessions.revoked_at IS NULL
`

type GetCoreSessionByTokenHashRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Status    string             `json:"status"`
}

func (q *Queries) GetCoreSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetCoreSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getCoreSessionByTokenHash, tokenHash)
	var i GetCoreSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
	)
	return i, err
}

const getCoreSessionForUpdate = `-- name: GetCoreSessionForUpdate :one
SELECT sessions.id, sessions.user_id, sessions.expires_at, users.status
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.kind = 'core' AND sessions.token_hash = $1 AND sessions.revoked_at IS NULL
FOR UPDATE OF sessions, users
`

type GetCoreSessionForUpdateRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Status    string             `json:"status"`
}

func (q *Queries) GetCoreSessionForUpdate(ctx context.Context, tokenHash []byte) (GetCoreSessionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCoreSessionForUpdate, tokenHash)
	var i GetCoreSessionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
	)
	return i, err
}

const getEmailIdentityForUpdate = `-- name: GetEmailIdentityForUpdate :one
SELECT identity.user_id, users.email_verified, users.status, users.created_at
FROM email_identities AS identity
JOIN users ON users.id = identity.user_id
WHERE identity.email_lookup_hash = $1
FOR UPDATE OF identity, users
`

type GetEmailIdentityForUpdateRow struct {
	UserID        pgtype.UUID        `json:"user_id"`
	EmailVerified bool               `json:"email_verified"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEmailIdentityForUpdate(ctx context.Context, emailLookupHash []byte) (GetEmailIdentityForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getEmailIdentityForUpdate, emailLookupHash)
	var i GetEmailIdentityForUpdateRow
	err := row.Scan(
		&i.UserID,
		&i.EmailVerified,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMailOutboxByVerificationCode = `-- name: GetMailOutboxByVerificationCode :one
SELECT id, status, attempt_count, max_attempts, provider_message_id,
       accepted_at, delivered_at, failed_at, last_error_code
FROM mail_outbox
WHERE verification_code_id = $1
`

type GetMailOutboxByVerificationCodeRow struct {
	ID                pgtype.UUID        `json:"id"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	MaxAttempts       int32              `json:"max_attempts"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	FailedAt          pgtype.Timestamptz `json:"failed_at"`
	LastErrorCode     pgtype.Text        `json:"last_error_code"`
}

func (q *Queries) GetMailOutboxByVerificationCode(ctx context.Context, verificationCodeID pgtype.UUID) (GetMailOutboxByVerificationCodeRow, error) {
	row := q.db.QueryRow(ctx, getMailOutboxByVerificationCode, verificationCodeID)
	var i GetMailOutboxByVerificationCodeRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.AcceptedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.LastErrorCode,
	)
	return i, err
}

const getPasswordCredentialForUpdate = `-- name: GetPasswordCredentialForUpdate :one
SELECT verifier, policy_version
FROM password_credentials
WHERE user_id = $1
FOR UPDATE
`

type GetPasswordCredentialForUpdateRow struct {
	Verifier      string `json:"verifier"`
	PolicyVersion int32  `json:"policy_version"`
}

func (q *Queries) GetPasswordCredentialForUpdate(ctx context.Context, userID pgtype.UUID) (GetPasswordCredentialForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialForUpdate, userID)
	var i GetPasswordCredentialForUpdateRow
	err := row.Scan(&i.Verifier, &i.PolicyVersion)
	return i, err
}

const getPasswordLoginCredential = `-- name: GetPasswordLoginCredential :one
SELECT identity.user_id, users.email_verified, users.status, users.created_at,
       credential.verifier, credential.policy_version
FROM email_identities AS identity
JOIN users ON users.id = identity.user_id
JOIN password_credentials AS credential ON credential.user_id = users.id
WHERE identity.email_lookup_hash = $1
`

type GetPasswordLoginCredentialRow struct {
	UserID        pgtype.UUID        `json:"user_id"`
	EmailVerified bool               `json:"email_verified"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Verifier      string             `json:"verifier"`
	PolicyVersion int32              `json:"policy_version"`
}

func (q *Queries) GetPasswordLoginCredential(ctx context.Context, emailLookupHash []byte) (GetPasswordLoginCredentialRow, error) {
	row := q.db.QueryRow(ctx, getPasswordLoginCredential, emailLookupHash)
	var i GetPasswordLoginCredentialRow
	err := row.Scan(
		&i.UserID,
		&i.EmailVerified,
		&i.Status,
		&i.CreatedAt,
		&i.Verifier,
		&i.PolicyVersion,
	)
	return i, err
}

const getVerificationCodeForUpdate = `-- name: GetVerificationCodeForUpdate :one
SELECT id, code_nonce, code_hash, expires_at, used_at, revoked_at, failed_attempts,
       consumed_request_key, consumed_request_fingerprint
FROM verification_codes
WHERE email_lookup_hash = $1 AND purpose = $2
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

type GetVerificationCodeForUpdateParams struct {
	EmailLookupHash []byte `json:"email_lookup_hash"`
	Purpose         string `json:"purpose"`
}

type GetVerificationCodeForUpdateRow struct {
	ID                         pgtype.UUID        `json:"id"`
	CodeNonce                  []byte             `json:"code_nonce"`
	CodeHash                   []byte             `json:"code_hash"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
	UsedAt                     pgtype.Timestamptz `json:"used_at"`
	RevokedAt                  pgtype.Timestamptz `json:"revoked_at"`
	FailedAttempts             int32              `json:"failed_attempts"`
	ConsumedRequestKey         pgtype.Text        `json:"consumed_request_key"`
	ConsumedRequestFingerprint []byte             `json:"consumed_request_fingerprint"`
}

func (q *Queries) GetVerificationCodeForUpdate(ctx context.Context, arg GetVerificationCodeForUpdateParams) (GetVerificationCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVerificationCodeForUpdate, arg.EmailLookupHash, arg.Purpose)
	var i GetVerificationCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CodeNonce,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.FailedAttempts,
		&i.ConsumedRequestKey,
		&i.ConsumedRequestFingerprint,
	)
	return i, err
}

const getVerificationRequestByKey = `-- name: GetVerificationRequestByKey :one
SELECT id, request_fingerprint, expires_at, created_at
FROM verification_codes
WHERE request_key = $1
`

type GetVerificationRequestByKeyRow struct {
	ID                 pgtype.UUID        `json:"id"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetVerificationRequestByKey(ctx context.Context, requestKey pgtype.Text) (GetVerificationRequestByKeyRow, error) {
	row := q.db.QueryRow(ctx, getVerificationRequestByKey, requestKey)
	var i GetVerificationRequestByKeyRow
	err := row.Scan(
		&i.ID,
		&i.RequestFingerprint,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const grantRegisteredUserPortalNoticeRead = `-- name: GrantRegisteredUserPortalNoticeRead :execrows
INSERT INTO user_role_grants (user_id, role_id, scope_kind, product_code)
SELECT users.id, roles.id, 'product', 'portal'
FROM users
JOIN authorization_roles AS roles ON roles.code = 'portal-notice-reader' AND roles.status = 'active'
JOIN role_permissions AS permissions ON permissions.role_id = roles.id AND permissions.permission_code = 'portal.notice.read'
JOIN permission_codes AS codes ON codes.code = permissions.permission_code AND codes.status = 'active'
WHERE users.id = $1
  AND users.email_verified
  AND users.status = 'active'
  AND NOT EXISTS (
      SELECT 1
      FROM role_permissions AS extra_permissions
      WHERE extra_permissions.role_id = roles.id
        AND extra_permissions.permission_code <> 'portal.notice.read'
  )
  AND NOT EXISTS (
      SELECT 1
      FROM user_role_grants AS existing
      WHERE existing.user_id = users.id
        AND existing.role_id = roles.id
        AND existing.scope_kind = 'product'
        AND existing.product_code = 'portal'
  )
`

func (q *Queries) GrantRegisteredUserPortalNoticeRead(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, grantRegisteredUserPortalNoticeRead, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMailOutboxAuditEvents = `-- name: ListMailOutboxAuditEvents :many
SELECT request_id, actor_kind, actor_id, action, attempt_count, reason_code, created_at
FROM mail_outbox_audit_events
WHERE outbox_id = $1
ORDER BY created_at, id
`

type ListMailOutboxAuditEventsRow struct {
	RequestID    string             `json:"request_id"`
	ActorKind    string             `json:"actor_kind"`
	ActorID      string             `json:"actor_id"`
	Action       string             `json:"action"`
	AttemptCount int32              `json:"attempt_count"`
	ReasonCode   pgtype.Text        `json:"reason_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMailOutboxAuditEvents(ctx context.Context, outboxID pgtype.UUID) ([]ListMailOutboxAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listMailOutboxAuditEvents, outboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMailOutboxAuditEventsRow{}
	for rows.Next() {
		var i ListMailOutboxAuditEventsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.ActorKind,
			&i.ActorID,
			&i.Action,
			&i.AttemptCount,
			&i.ReasonCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailOutboxDelivered = `-- name: MarkMailOutboxDelivered :execrows
WITH transitioned AS (
    UPDATE mail_outbox
    SET status = 'delivered', delivered_at = now(), updated_at = now()
    WHERE provider_message_id = $3 AND status = 'accepted'
    RETURNING id, attempt_count
)
INSERT INTO mail_outbox_audit_events (
    outbox_id, request_id, actor_kind, actor_id, action, attempt_count
)
SELECT id, $1, 'provider', $2, 'delivered', attempt_count
FROM transitioned
`

type MarkMailOutboxDeliveredParams struct {
	RequestID         string      `json:"request_id"`
	ActorID           string      `json:"actor_id"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
}

func (q *Queries) MarkMailOutboxDelivered(ctx context.Context, arg MarkMailOutboxDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMailOutboxDelivered, arg.RequestID, arg.ActorID, arg.ProviderMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordMailDeliveryReceipt = `-- name: RecordMailDeliveryReceipt :execrows
WITH receipt AS (
    INSERT INTO mail_delivery_receipts (message_id, request_id, actor_id)
    VALUES ($1, $2, $3)
    ON CONFLICT (message_id) DO UPDATE SET message_id = EXCLUDED.message_id
    RETURNING message_id, request_id, actor_id
), transitioned AS (
    UPDATE mail_outbox AS job
    SET status = 'delivered', delivered_at = now(), updated_at = now()
    FROM receipt
    WHERE job.provider_message_id = receipt.message_id AND job.status = 'accepted'
    RETURNING job.id, job.attempt_count, receipt.message_id, receipt.request_id, receipt.actor_id
), audited AS (
    INSERT INTO mail_outbox_audit_events (
        outbox_id, request_id, actor_kind, actor_id, action, attempt_count
    )
    SELECT id, request_id, 'provider', actor_id, 'delivered', attempt_count
    FROM transitioned
    RETURNING outbox_id
)
UPDATE mail_delivery_receipts AS receipt
SET applied_outbox_id = transitioned.id, applied_at = now()
FROM transitioned
JOIN audited ON audited.outbox_id = transitioned.id
WHERE receipt.message_id = transitioned.message_id AND receipt.applied_at IS NULL
`

type RecordMailDeliveryReceiptParams struct {
	MessageID string `json:"message_id"`
	RequestID string `json:"request_id"`
	ActorID   string `json:"actor_id"`
}

func (q *Queries) RecordMailDeliveryReceipt(ctx context.Context, arg RecordMailDeliveryReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordMailDeliveryReceipt, arg.MessageID, arg.RequestID, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerFailedVerificationAttempt = `-- name: RegisterFailedVerificationAttempt :one
UPDATE verification_codes
SET failed_attempts = failed_attempts + 1,
    revoked_at = CASE WHEN failed_attempts + 1 >= 5 THEN now() ELSE revoked_at END
WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL AND failed_attempts < 5
RETURNING failed_attempts, revoked_at
`

type RegisterFailedVerificationAttemptRow struct {
	FailedAttempts int32              `json:"failed_attempts"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RegisterFailedVerificationAttempt(ctx context.Context, id pgtype.UUID) (RegisterFailedVerificationAttemptRow, error) {
	row := q.db.QueryRow(ctx, registerFailedVerificationAttempt, id)
	var i RegisterFailedVerificationAttemptRow
	err := row.Scan(&i.FailedAttempts, &i.RevokedAt)
	return i, err
}

const replacePasswordCredential = `-- name: ReplacePasswordCredential :execrows
UPDATE password_credentials
SET verifier = $2, policy_version = $3, updated_at = now()
WHERE user_id = $1
`

type ReplacePasswordCredentialParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Verifier      string      `json:"verifier"`
	PolicyVersion int32       `json:"policy_version"`
}

func (q *Queries) ReplacePasswordCredential(ctx context.Context, arg ReplacePasswordCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, replacePasswordCredential, arg.UserID, arg.Verifier, arg.PolicyVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueMailOutbox = `-- name: RequeueMailOutbox :one
WITH target AS (
    SELECT dead_letter.id AS dead_letter_id, job.id AS outbox_id
    FROM mail_outbox AS job
    JOIN mail_dead_letters AS dead_letter ON dead_letter.outbox_id = job.id
    WHERE job.id = $1 AND job.status = 'failed'
      AND dead_letter.requeued_at IS NULL
    ORDER BY dead_letter.dead_lettered_at DESC
    FOR UPDATE OF job, dead_letter
    LIMIT 1
), transitioned AS (
    UPDATE mail_outbox AS job
    SET status = 'pending', attempt_count = 0, available_at = now(),
        locked_at = NULL, locked_by = NULL, provider_message_id = NULL,
        accepted_at = NULL, delivered_at = NULL, failed_at = NULL,
        last_error_code = NULL, updated_at = now()
    FROM target
    WHERE job.id = target.outbox_id
    RETURNING job.id, job.request_id, job.attempt_count
), closed_dead_letter AS (
    UPDATE mail_dead_letters AS dead_letter
    SET requeued_at = now(), requeued_by = $2, requeue_reason = $3
    FROM target
    WHERE dead_letter.id = target.dead_letter_id
    RETURNING dead_letter.outbox_id
), audited AS (
    INSERT INTO mail_outbox_audit_events (
        outbox_id, request_id, actor_kind, actor_id, action, attempt_count, reason_code
    )
    SELECT transitioned.id, $4, 'operator', $2,
           'requeued', transitioned.attempt_count, 'MANUAL_REQUEUE'
    FROM transitioned
    JOIN closed_dead_letter ON closed_dead_letter.outbox_id = transitioned.id
    RETURNING outbox_id
)
SELECT transitioned.id
FROM transitioned
JOIN audited ON audited.outbox_id = transitioned.id
`

type RequeueMailOutboxParams struct {
	OutboxID  pgtype.UUID `json:"outbox_id"`
	ActorID   pgtype.Text `json:"actor_id"`
	Reason    pgtype.Text `json:"reason"`
	RequestID string      `json:"request_id"`
}

func (q *Queries) RequeueMailOutbox(ctx context.Context, arg RequeueMailOutboxParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, requeueMailOutbox,
		arg.OutboxID,
		arg.ActorID,
		arg.Reason,
		arg.RequestID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const retryMailOutbox = `-- name: RetryMailOutbox :execrows
WITH transitioned AS (
    UPDATE mail_outbox AS job
    SET status = 'retry_due', locked_at = NULL, locked_by = NULL,
        available_at = $2, last_error_code = $3, updated_at = now()
    WHERE job.id = $4 AND job.status = 'processing' AND job.locked_by = $1
      AND job.attempt_count < job.max_attempts
    RETURNING job.id, job.request_id, job.attempt_count, job.last_error_code
)
INSERT INTO mail_outbox_audit_events (
    outbox_id, request_id, actor_kind, actor_id, action, attempt_count, reason_code
)
SELECT id, request_id, 'worker', $1, 'retry_scheduled', attempt_count, last_error_code
FROM transitioned
`

type RetryMailOutboxParams struct {
	WorkerID      string             `json:"worker_id"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	OutboxID      pgtype.UUID        `json:"outbox_id"`
}

func (q *Queries) RetryMailOutbox(ctx context.Context, arg RetryMailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryMailOutbox,
		arg.WorkerID,
		arg.AvailableAt,
		arg.LastErrorCode,
		arg.OutboxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherUserSessionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubExpiredVerificationOutboxPayloads = `-- name: ScrubExpiredVerificationOutboxPayloads :execrows
UPDATE mail_outbox AS job
SET payload_ciphertext = NULL,
    payload_cleared_at = now(),
    updated_at = now()
FROM verification_codes AS verification
WHERE job.verification_code_id = verification.id
  AND verification.created_at <= $1
  AND job.payload_cleared_at IS NULL
`

func (q *Queries) ScrubExpiredVerificationOutboxPayloads(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, scrubExpiredVerificationOutboxPayloads, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubExpiredVerificationSecrets = `-- name: ScrubExpiredVerificationSecrets :execrows
UPDATE verification_codes
SET request_key = NULL,
    request_fingerprint = NULL,
    code_nonce = NULL,
    code_hash = NULL,
    consumed_request_key = NULL,
    consumed_request_fingerprint = NULL,
    sensitive_cleared_at = now()
WHERE created_at <= $1
  AND sensitive_cleared_at IS NULL
`

func (q *Queries) ScrubExpiredVerificationSecrets(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, scrubExpiredVerificationSecrets, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upgradePasswordCredential = `-- name: UpgradePasswordCredential :execrows
UPDATE password_credentials
SET verifier = $1, policy_version = $2, updated_at = now()
WHERE user_id = $3 AND verifier = $4
`

type UpgradePasswordCredentialParams struct {
	NewVerifier   string      `json:"new_verifier"`
	PolicyVersion int32       `json:"policy_version"`
	UserID        pgtype.UUID `json:"user_id"`
	OldVerifier   string      `json:"old_verifier"`
}

func (q *Queries) UpgradePasswordCredential(ctx context.Context, arg UpgradePasswordCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, upgradePasswordCredential,
		arg.NewVerifier,
		arg.PolicyVersion,
		arg.UserID,
		arg.OldVerifier,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
