// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_mail.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptMailOutbox = `-- name: AcceptMailOutbox :execrows
UPDATE mail_outbox
SET status = 'accepted', locked_at = NULL, locked_by = NULL,
    provider_message_id = $3, accepted_at = now(), last_error_code = NULL, updated_at = now()
WHERE id = $1 AND status = 'processing' AND locked_by = $2
`

type AcceptMailOutboxParams struct {
	ID                pgtype.UUID `json:"id"`
	LockedBy          pgtype.Text `json:"locked_by"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
}

func (q *Queries) AcceptMailOutbox(ctx context.Context, arg AcceptMailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptMailOutbox, arg.ID, arg.LockedBy, arg.ProviderMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimMailOutbox = `-- name: ClaimMailOutbox :one
WITH candidate AS (
    SELECT candidate_job.id
    FROM mail_outbox AS candidate_job
    WHERE (
        (candidate_job.status IN ('pending', 'retry_due') AND candidate_job.available_at <= now())
        OR (candidate_job.status = 'processing' AND candidate_job.locked_at < $2)
    )
      AND candidate_job.attempt_count < candidate_job.max_attempts
    ORDER BY CASE candidate_job.priority WHEN 'critical' THEN 1 ELSE 2 END, candidate_job.available_at, candidate_job.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE mail_outbox AS job
SET status = 'processing', attempt_count = attempt_count + 1,
    locked_at = now(), locked_by = $1, updated_at = now()
FROM candidate
WHERE job.id = candidate.id
RETURNING job.id, job.dedupe_key, job.request_id, job.recipient_ciphertext, job.payload_ciphertext,
          job.attempt_count, job.max_attempts
`

type ClaimMailOutboxParams struct {
	WorkerID      pgtype.Text        `json:"worker_id"`
	ReclaimBefore pgtype.Timestamptz `json:"reclaim_before"`
}

type ClaimMailOutboxRow struct {
	ID                  pgtype.UUID `json:"id"`
	DedupeKey           string      `json:"dedupe_key"`
	RequestID           string      `json:"request_id"`
	RecipientCiphertext []byte      `json:"recipient_ciphertext"`
	PayloadCiphertext   []byte      `json:"payload_ciphertext"`
	AttemptCount        int32       `json:"attempt_count"`
	MaxAttempts         int32       `json:"max_attempts"`
}

func (q *Queries) ClaimMailOutbox(ctx context.Context, arg ClaimMailOutboxParams) (ClaimMailOutboxRow, error) {
	row := q.db.QueryRow(ctx, claimMailOutbox, arg.WorkerID, arg.ReclaimBefore)
	var i ClaimMailOutboxRow
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.RequestID,
		&i.RecipientCiphertext,
		&i.PayloadCiphertext,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}

const consumeVerificationCode = `-- name: ConsumeVerificationCode :execrows
UPDATE verification_codes
SET used_at = now(), consumed_request_key = $2, consumed_request_fingerprint = $3
WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

type ConsumeVerificationCodeParams struct {
	ID                         pgtype.UUID `json:"id"`
	ConsumedRequestKey         pgtype.Text `json:"consumed_request_key"`
	ConsumedRequestFingerprint []byte      `json:"consumed_request_fingerprint"`
}

func (q *Queries) ConsumeVerificationCode(ctx context.Context, arg ConsumeVerificationCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerificationCode, arg.ID, arg.ConsumedRequestKey, arg.ConsumedRequestFingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (
    email_lookup_hash, purpose, request_key, request_fingerprint,
    code_nonce, code_hash, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, expires_at, created_at
`

type CreateVerificationCodeParams struct {
	EmailLookupHash    []byte             `json:"email_lookup_hash"`
	Purpose            string             `json:"purpose"`
	RequestKey         string             `json:"request_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	CodeNonce          []byte             `json:"code_nonce"`
	CodeHash           []byte             `json:"code_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

type CreateVerificationCodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (CreateVerificationCodeRow, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.EmailLookupHash,
		arg.Purpose,
		arg.RequestKey,
		arg.RequestFingerprint,
		arg.CodeNonce,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i CreateVerificationCodeRow
	err := row.Scan(&i.ID, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const createVerificationMailOutbox = `-- name: CreateVerificationMailOutbox :one
INSERT INTO mail_outbox (
    verification_code_id, dedupe_key, request_id, kind, priority,
    recipient_ciphertext, payload_ciphertext
) VALUES ($1, $2, $3, 'verification_code', 'critical', $4, $5)
RETURNING id
`

type CreateVerificationMailOutboxParams struct {
	VerificationCodeID  pgtype.UUID `json:"verification_code_id"`
	DedupeKey           string      `json:"dedupe_key"`
	RequestID           string      `json:"request_id"`
	RecipientCiphertext []byte      `json:"recipient_ciphertext"`
	PayloadCiphertext   []byte      `json:"payload_ciphertext"`
}

func (q *Queries) CreateVerificationMailOutbox(ctx context.Context, arg CreateVerificationMailOutboxParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createVerificationMailOutbox,
		arg.VerificationCodeID,
		arg.DedupeKey,
		arg.RequestID,
		arg.RecipientCiphertext,
		arg.PayloadCiphertext,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const failExhaustedOutboxLeases = `-- name: FailExhaustedOutboxLeases :exec
UPDATE mail_outbox
SET status = 'failed', locked_at = NULL, locked_by = NULL,
    failed_at = now(), last_error_code = 'WORKER_LEASE_EXHAUSTED', updated_at = now()
WHERE status = 'processing' AND locked_at < $1 AND attempt_count >= max_attempts
`

func (q *Queries) FailExhaustedOutboxLeases(ctx context.Context, lockedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, failExhaustedOutboxLeases, lockedAt)
	return err
}

const failMailOutbox = `-- name: FailMailOutbox :execrows
UPDATE mail_outbox
SET status = 'failed', locked_at = NULL, locked_by = NULL,
    failed_at = now(), last_error_code = $3, updated_at = now()
WHERE id = $1 AND status = 'processing' AND locked_by = $2
`

type FailMailOutboxParams struct {
	ID            pgtype.UUID `json:"id"`
	LockedBy      pgtype.Text `json:"locked_by"`
	LastErrorCode pgtype.Text `json:"last_error_code"`
}

func (q *Queries) FailMailOutbox(ctx context.Context, arg FailMailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, failMailOutbox, arg.ID, arg.LockedBy, arg.LastErrorCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMailOutboxByVerificationCode = `-- name: GetMailOutboxByVerificationCode :one
SELECT id, status, attempt_count, max_attempts, provider_message_id,
       accepted_at, delivered_at, failed_at, last_error_code
FROM mail_outbox
WHERE verification_code_id = $1
`

type GetMailOutboxByVerificationCodeRow struct {
	ID                pgtype.UUID        `json:"id"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	MaxAttempts       int32              `json:"max_attempts"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	FailedAt          pgtype.Timestamptz `json:"failed_at"`
	LastErrorCode     pgtype.Text        `json:"last_error_code"`
}

func (q *Queries) GetMailOutboxByVerificationCode(ctx context.Context, verificationCodeID pgtype.UUID) (GetMailOutboxByVerificationCodeRow, error) {
	row := q.db.QueryRow(ctx, getMailOutboxByVerificationCode, verificationCodeID)
	var i GetMailOutboxByVerificationCodeRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.AcceptedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.LastErrorCode,
	)
	return i, err
}

const getVerificationCodeForUpdate = `-- name: GetVerificationCodeForUpdate :one
SELECT id, code_nonce, code_hash, expires_at, used_at, revoked_at, failed_attempts,
       consumed_request_key, consumed_request_fingerprint
FROM verification_codes
WHERE email_lookup_hash = $1 AND purpose = $2
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

type GetVerificationCodeForUpdateParams struct {
	EmailLookupHash []byte `json:"email_lookup_hash"`
	Purpose         string `json:"purpose"`
}

type GetVerificationCodeForUpdateRow struct {
	ID                         pgtype.UUID        `json:"id"`
	CodeNonce                  []byte             `json:"code_nonce"`
	CodeHash                   []byte             `json:"code_hash"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
	UsedAt                     pgtype.Timestamptz `json:"used_at"`
	RevokedAt                  pgtype.Timestamptz `json:"revoked_at"`
	FailedAttempts             int32              `json:"failed_attempts"`
	ConsumedRequestKey         pgtype.Text        `json:"consumed_request_key"`
	ConsumedRequestFingerprint []byte             `json:"consumed_request_fingerprint"`
}

func (q *Queries) GetVerificationCodeForUpdate(ctx context.Context, arg GetVerificationCodeForUpdateParams) (GetVerificationCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVerificationCodeForUpdate, arg.EmailLookupHash, arg.Purpose)
	var i GetVerificationCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CodeNonce,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.FailedAttempts,
		&i.ConsumedRequestKey,
		&i.ConsumedRequestFingerprint,
	)
	return i, err
}

const getVerificationRequestByKey = `-- name: GetVerificationRequestByKey :one
SELECT id, request_fingerprint, expires_at, created_at
FROM verification_codes
WHERE request_key = $1
`

type GetVerificationRequestByKeyRow struct {
	ID                 pgtype.UUID        `json:"id"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetVerificationRequestByKey(ctx context.Context, requestKey string) (GetVerificationRequestByKeyRow, error) {
	row := q.db.QueryRow(ctx, getVerificationRequestByKey, requestKey)
	var i GetVerificationRequestByKeyRow
	err := row.Scan(
		&i.ID,
		&i.RequestFingerprint,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMailOutboxDelivered = `-- name: MarkMailOutboxDelivered :execrows
UPDATE mail_outbox
SET status = 'delivered', delivered_at = now(), updated_at = now()
WHERE provider_message_id = $1 AND status = 'accepted'
`

func (q *Queries) MarkMailOutboxDelivered(ctx context.Context, providerMessageID pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, markMailOutboxDelivered, providerMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerFailedVerificationAttempt = `-- name: RegisterFailedVerificationAttempt :one
UPDATE verification_codes
SET failed_attempts = failed_attempts + 1,
    revoked_at = CASE WHEN failed_attempts + 1 >= 5 THEN now() ELSE revoked_at END
WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL AND failed_attempts < 5
RETURNING failed_attempts, revoked_at
`

type RegisterFailedVerificationAttemptRow struct {
	FailedAttempts int32              `json:"failed_attempts"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RegisterFailedVerificationAttempt(ctx context.Context, id pgtype.UUID) (RegisterFailedVerificationAttemptRow, error) {
	row := q.db.QueryRow(ctx, registerFailedVerificationAttempt, id)
	var i RegisterFailedVerificationAttemptRow
	err := row.Scan(&i.FailedAttempts, &i.RevokedAt)
	return i, err
}

const retryMailOutbox = `-- name: RetryMailOutbox :execrows
UPDATE mail_outbox
SET status = 'retry_due', locked_at = NULL, locked_by = NULL,
    available_at = $3, last_error_code = $4, updated_at = now()
WHERE id = $1 AND status = 'processing' AND locked_by = $2 AND attempt_count < max_attempts
`

type RetryMailOutboxParams struct {
	ID            pgtype.UUID        `json:"id"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
}

func (q *Queries) RetryMailOutbox(ctx context.Context, arg RetryMailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryMailOutbox,
		arg.ID,
		arg.LockedBy,
		arg.AvailableAt,
		arg.LastErrorCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
