packages:
  - "apps/*"
  - "products/quizcraft/web-app"

overrides:
  "nanoid@3": "3.3.18"
  postcss: "8.5.23"

packageExtensions:
  "element-plus@2.13.0":
    dependencies:
      "@vue/shared": "3.5.25"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
