// Code generated by cmd/contractgen from console-gateway.yaml; DO NOT EDIT.
package contract

const (
	HealthRoute   = "/api/v1/healthz"
	LoginRoute    = "/api/v1/auth/login"
	CallbackRoute = "/api/v1/auth/callback"
	SessionRoute  = "/api/v1/session"
	LogoutRoute   = "/api/v1/session/logout"
	SourceSHA256  = "780f86a12079eb465ebdcf4750a0ecbbbdb8ee9c33c65a35b9e7664197b895d1"
)
