// Code generated by cmd/contractgen from console-gateway.yaml; DO NOT EDIT.
package contract

import "time"

const (
	HealthRoute                         = "/api/v1/healthz"
	LoginRoute                          = "/api/v1/auth/login"
	CallbackRoute                       = "/api/v1/auth/callback"
	SessionRoute                        = "/api/v1/session"
	OverviewRoute                       = "/api/v1/overview"
	OperationsRoute                     = "/api/v1/operations"
	RevokeSessionRoute                  = "/api/v1/operations/sessions/{session_id}/revocations"
	UpdateAccessRoute                   = "/api/v1/operations/users/{user_id}/access-updates"
	OperationStatusRoute                = "/api/v1/operations/results/{operation}"
	AccountLookupRoute                  = "/api/v1/operations/account-lookups"
	NoticeSnapshotRoute                 = "/api/v1/notices"
	NoticeSourceRoute                   = "/api/v1/notices/sources"
	NoticeVersionRoute                  = "/api/v1/notices/sources/{source_id}/versions"
	NoticeReviewRoute                   = "/api/v1/notices/versions/{version_id}/reviews"
	NoticeDistributionRoute             = "/api/v1/notices/versions/{version_id}/distributions"
	NoticeOperationRoute                = "/api/v1/notices/operations/{operation}"
	LibraryWorkspaceRoute               = "/api/v1/library"
	LibraryCommandRoute                 = "/api/v1/library/commands"
	LibraryOperationRoute               = "/api/v1/library/operations/{operation}"
	FoodWorkspaceRoute                  = "/api/v1/food"
	FoodCommandRoute                    = "/api/v1/food/commands"
	FoodOperationRoute                  = "/api/v1/food/operations/{operation}"
	AccountMembershipRoute              = "/api/v1/account/memberships/{user_id}"
	AccountMembershipGrantsRoute        = "/api/v1/account/memberships/{user_id}/grants"
	AccountMembershipRevocationsRoute   = "/api/v1/account/memberships/{user_id}/revocations"
	AccountPointAdjustmentsRoute        = "/api/v1/account/points/adjustments"
	AccountTicketsRoute                 = "/api/v1/account/tickets"
	AccountTicketRoute                  = "/api/v1/account/tickets/{ticket_id}"
	AccountTicketRepliesRoute           = "/api/v1/account/tickets/{ticket_id}/replies"
	AccountTicketTransitionsRoute       = "/api/v1/account/tickets/{ticket_id}/transitions"
	AccountMembershipOrderClosuresRoute = "/api/v1/account/membership-orders/{order_id}/closures"
	AccountMembershipOrderRefundsRoute  = "/api/v1/account/membership-orders/{order_id}/refunds"
	AccountMembershipOrderRefundRoute   = "/api/v1/account/membership-orders/{order_id}/refunds/{refund_id}"
	LogoutRoute                         = "/api/v1/session/logout"
	SourceSHA256                        = "90b526ae5a6ff24fd407c41f46165e0283f204ea2f350a6181bba2b300380915"
)

type ConsoleAccessContext struct {
	Permissions []string       `json:"permissions"`
	Scopes      []ConsoleScope `json:"scopes"`
	VerifiedAt  time.Time      `json:"verified_at"`
}

type ConsoleAccountLookupRequest struct {
	Email string `json:"email"`
}

type ConsoleAccountLookupResult struct {
	Account any `json:"account"`
}

type ConsoleAccountMembership struct {
	Lifetime bool   `json:"lifetime"`
	Plan     string `json:"plan"`
	Version  int64  `json:"version"`
}

type ConsoleAccountMembershipEnvelope struct {
	Membership ConsoleAccountMembership `json:"membership"`
}

type ConsoleAccountPointAdjustmentResult struct {
	Balance int64                   `json:"balance"`
	Entry   ConsolePointLedgerEntry `json:"entry"`
}

type ConsoleAccountTicket struct {
	Category  string    `json:"category"`
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
	Reference string    `json:"reference"`
	Status    string    `json:"status"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	Version   int64     `json:"version"`
}

type ConsoleAccountTicketCommandResult struct {
	Ticket ConsoleAccountTicket `json:"ticket"`
}

type ConsoleAccountTicketDetail struct {
	Events   []ConsoleAccountTicketEvent   `json:"events"`
	Messages []ConsoleAccountTicketMessage `json:"messages"`
	Ticket   ConsoleAccountTicket          `json:"ticket"`
}

type ConsoleAccountTicketEvent struct {
	CreatedAt  time.Time `json:"created_at"`
	FromStatus string    `json:"from_status"`
	ID         string    `json:"id"`
	Kind       string    `json:"kind"`
	ToStatus   string    `json:"to_status"`
}

type ConsoleAccountTicketMessage struct {
	AuthorKind string    `json:"author_kind"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"created_at"`
	ID         string    `json:"id"`
}

type ConsoleAccountTicketQueue struct {
	Tickets []ConsoleAccountTicket `json:"tickets"`
}

type ConsoleLookedUpAccount struct {
	DisplayName *string `json:"display_name,omitempty"`
	ID          string  `json:"id"`
	Status      string  `json:"status"`
}

type ConsoleMembershipMutationRequest struct {
	ExpectedVersion int64  `json:"expected_version"`
	Reason          string `json:"reason"`
}

type ConsoleMembershipOrder struct {
	AmountCents int64     `json:"amount_cents"`
	CreatedAt   time.Time `json:"created_at"`
	ID          string    `json:"id"`
	Plan        string    `json:"plan"`
	Status      string    `json:"status"`
	UpdatedAt   time.Time `json:"updated_at"`
	Version     int64     `json:"version"`
}

type ConsoleMembershipOrderCommandRequest struct {
	ExpectedVersion int64  `json:"expected_version"`
	Reason          string `json:"reason"`
}

type ConsoleMembershipOrderRefund struct {
	AmountCents int64  `json:"amount_cents"`
	ID          string `json:"id"`
	Status      string `json:"status"`
}

type ConsoleMembershipOrderRefundResult struct {
	Order  ConsoleMembershipOrder       `json:"order"`
	Refund ConsoleMembershipOrderRefund `json:"refund"`
}

type ConsoleMembershipOrderResult struct {
	Order ConsoleMembershipOrder `json:"order"`
}

type ConsoleModuleMetric struct {
	Hint  *string `json:"hint,omitempty"`
	Label string  `json:"label"`
	Value string  `json:"value"`
}

type ConsoleModuleSummary struct {
	AsOf          *time.Time            `json:"as_of,omitempty"`
	ID            string                `json:"id"`
	LastSuccessAt *time.Time            `json:"last_success_at,omitempty"`
	Metrics       []ConsoleModuleMetric `json:"metrics"`
	RequestID     string                `json:"request_id"`
	Status        string                `json:"status"`
	StatusMessage string                `json:"status_message"`
}

type ConsoleOperatorReplyRequest struct {
	Body            string `json:"body"`
	ExpectedVersion int64  `json:"expected_version"`
}

type ConsoleOverview struct {
	GeneratedAt time.Time              `json:"generated_at"`
	Modules     []ConsoleModuleSummary `json:"modules"`
}

type ConsolePointAdjustmentRequest struct {
	Amount int64  `json:"amount"`
	Reason string `json:"reason"`
	UserID string `json:"user_id"`
}

type ConsolePointLedgerEntry struct {
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
	Reason    string    `json:"reason"`
}

type ConsoleScope struct {
	Kind        string  `json:"kind"`
	ProductCode *string `json:"product_code,omitempty"`
}

type ConsoleSession struct {
	AccessContext ConsoleAccessContext `json:"access_context"`
	ExpiresAt     time.Time            `json:"expires_at"`
	User          struct {
		ID string `json:"id"`
	} `json:"user"`
}

type ConsoleTicketTransitionRequest struct {
	ExpectedVersion int64  `json:"expected_version"`
	Status          string `json:"status"`
}

type CorrectionReviewCommand struct {
	ExpectedVersion time.Time     `json:"expected_version"`
	Kind            string        `json:"kind"`
	Payload         ReviewPayload `json:"payload"`
	ResourceID      string        `json:"resource_id"`
}

type CourseArchiveCommand struct {
	ExpectedVersion time.Time    `json:"expected_version"`
	Kind            string       `json:"kind"`
	Payload         EmptyPayload `json:"payload"`
	ResourceID      string       `json:"resource_id"`
}

type CourseCreateCommand struct {
	Kind    string              `json:"kind"`
	Payload CourseCreatePayload `json:"payload"`
}

type CourseCreatePayload struct {
	CollegeID   string  `json:"collegeId"`
	Description *string `json:"description,omitempty"`
	ExamScope   *string `json:"examScope,omitempty"`
	Grade       string  `json:"grade"`
	MajorID     string  `json:"majorId"`
	Name        string  `json:"name"`
	SchoolID    string  `json:"schoolId"`
	Slug        string  `json:"slug"`
	Status      *string `json:"status,omitempty"`
}

type CourseMutationPayload struct {
	CollegeID   *string `json:"collegeId,omitempty"`
	Description *string `json:"description,omitempty"`
	ExamScope   *string `json:"examScope,omitempty"`
	Grade       *string `json:"grade,omitempty"`
	MajorID     *string `json:"majorId,omitempty"`
	Name        *string `json:"name,omitempty"`
	SchoolID    *string `json:"schoolId,omitempty"`
	Slug        *string `json:"slug,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type CourseUpdateCommand struct {
	ExpectedVersion time.Time             `json:"expected_version"`
	Kind            string                `json:"kind"`
	Payload         CourseMutationPayload `json:"payload"`
	ResourceID      string                `json:"resource_id"`
}

type CreateNoticeSourceRequest struct {
	CanonicalUrl string `json:"canonical_url"`
	Code         string `json:"code"`
	Name         string `json:"name"`
}

type CreateNoticeVersionRequest struct {
	Body              string     `json:"body"`
	SourcePublishedAt *time.Time `json:"source_published_at,omitempty"`
	SourceUrl         string     `json:"source_url"`
	Title             string     `json:"title"`
}

type EmptyPayload struct {
}

type ErrorEnvelope struct {
	Error     ErrorObject `json:"error"`
	RequestID string      `json:"request_id"`
}

type ErrorObject struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type FoodAnomalyTicket struct {
	CreatedAt time.Time `json:"created_at"`
	Details   string    `json:"details"`
	ID        string    `json:"id"`
	Kind      string    `json:"kind"`
	Severity  string    `json:"severity"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	VenueName string    `json:"venue_name"`
	Version   int64     `json:"version"`
}

type FoodCommand struct {
	ExpectedVersion int64           `json:"expected_version"`
	Kind            FoodCommandKind `json:"kind"`
	Payload         struct {
		Note string `json:"note"`
	} `json:"payload"`
	ResourceID string `json:"resource_id"`
}

type FoodCommandKind string

type FoodOperationResult struct {
	Operation  FoodCommandKind `json:"operation"`
	ResourceID *string         `json:"resource_id,omitempty"`
	State      string          `json:"state"`
	Version    *int64          `json:"version,omitempty"`
}

type FoodSubmission struct {
	Description string    `json:"description"`
	ID          string    `json:"id"`
	ItemName    string    `json:"item_name"`
	Status      string    `json:"status"`
	SubmittedAt time.Time `json:"submitted_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	VenueName   string    `json:"venue_name"`
	Version     int64     `json:"version"`
}

type FoodTierAdjustment struct {
	CreatedAt    time.Time `json:"created_at"`
	CurrentTier  string    `json:"current_tier"`
	ID           string    `json:"id"`
	ProposedTier string    `json:"proposed_tier"`
	Reason       string    `json:"reason"`
	Status       string    `json:"status"`
	UpdatedAt    time.Time `json:"updated_at"`
	VenueName    string    `json:"venue_name"`
	Version      int64     `json:"version"`
}

type FoodWorkspace struct {
	AnomalyTickets  []FoodAnomalyTicket  `json:"anomaly_tickets"`
	AsOf            time.Time            `json:"as_of"`
	Stale           bool                 `json:"stale"`
	Status          string               `json:"status"`
	StatusMessage   string               `json:"status_message"`
	Submissions     []FoodSubmission     `json:"submissions"`
	TierAdjustments []FoodTierAdjustment `json:"tier_adjustments"`
}

type LibraryCommand any

type LibraryCommandKind string

type LibraryCorrection struct {
	Description string    `json:"description"`
	ID          string    `json:"id"`
	Reason      string    `json:"reason"`
	Status      string    `json:"status"`
	TargetID    string    `json:"target_id"`
	TargetType  string    `json:"target_type"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type LibraryCourse struct {
	Grade     string    `json:"grade"`
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

type LibraryDownload struct {
	AccessLevel   string    `json:"access_level"`
	DownloadedAt  time.Time `json:"downloaded_at"`
	ID            string    `json:"id"`
	MaterialID    string    `json:"material_id"`
	MaterialTitle string    `json:"material_title"`
}

type LibraryMaterial struct {
	AccessLevel string    `json:"access_level"`
	CourseID    string    `json:"course_id"`
	FileName    string    `json:"file_name"`
	FileSize    int64     `json:"file_size"`
	ID          string    `json:"id"`
	Status      string    `json:"status"`
	Title       string    `json:"title"`
	Type        string    `json:"type"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type LibraryOperationResult struct {
	Operation  LibraryCommandKind `json:"operation"`
	ResourceID *string            `json:"resource_id,omitempty"`
	State      string             `json:"state"`
}

type LibraryWorkspace struct {
	Corrections   []LibraryCorrection `json:"corrections"`
	Courses       []LibraryCourse     `json:"courses"`
	Degraded      bool                `json:"degraded"`
	Downloads     []LibraryDownload   `json:"downloads"`
	GeneratedAt   time.Time           `json:"generated_at"`
	Materials     []LibraryMaterial   `json:"materials"`
	Status        string              `json:"status"`
	StatusMessage string              `json:"status_message"`
	Submissions   []LibraryMaterial   `json:"submissions"`
}

type MaterialArchiveCommand struct {
	ExpectedVersion time.Time    `json:"expected_version"`
	Kind            string       `json:"kind"`
	Payload         EmptyPayload `json:"payload"`
	ResourceID      string       `json:"resource_id"`
}

type MaterialCreateCommand struct {
	Kind    string                `json:"kind"`
	Payload MaterialCreatePayload `json:"payload"`
}

type MaterialCreatePayload struct {
	AccessLevel    *string `json:"accessLevel,omitempty"`
	CourseID       string  `json:"courseId"`
	Description    *string `json:"description,omitempty"`
	FileName       *string `json:"fileName,omitempty"`
	FileSize       *int64  `json:"fileSize,omitempty"`
	PreviewContent *string `json:"previewContent,omitempty"`
	Status         *string `json:"status,omitempty"`
	StorageKey     string  `json:"storageKey"`
	Title          string  `json:"title"`
	Type           *string `json:"type,omitempty"`
}

type MaterialUpdateCommand struct {
	ExpectedVersion time.Time             `json:"expected_version"`
	Kind            string                `json:"kind"`
	Payload         MaterialUpdatePayload `json:"payload"`
	ResourceID      string                `json:"resource_id"`
}

type MaterialUpdatePayload struct {
	AccessLevel    *string `json:"accessLevel,omitempty"`
	CourseID       *string `json:"courseId,omitempty"`
	Description    *string `json:"description,omitempty"`
	PreviewContent *string `json:"previewContent,omitempty"`
	Status         *string `json:"status,omitempty"`
	Title          *string `json:"title,omitempty"`
	Type           *string `json:"type,omitempty"`
}

type NoticeAudience struct {
	Kind  *string `json:"kind,omitempty"`
	Value *string `json:"value,omitempty"`
}

type NoticeDistributionRequest struct {
	Audience         NoticeAudience `json:"audience"`
	Channel          string         `json:"channel"`
	ExpectedRevision int64          `json:"expected_revision"`
}

type NoticeReviewRequest struct {
	Decision         string  `json:"decision"`
	ExpectedRevision int64   `json:"expected_revision"`
	Note             *string `json:"note,omitempty"`
}

type NoticeSnapshot struct {
	GeneratedAt time.Time       `json:"generated_at"`
	Items       []NoticeVersion `json:"items"`
}

type NoticeSource struct {
	Code string `json:"code"`
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NoticeVersion struct {
	Body               string       `json:"body"`
	ContentHash        string       `json:"content_hash"`
	CreatedAt          time.Time    `json:"created_at"`
	DistributionCount  int64        `json:"distribution_count"`
	DistributionStatus *string      `json:"distribution_status,omitempty"`
	ID                 string       `json:"id"`
	Revision           int64        `json:"revision"`
	Source             NoticeSource `json:"source"`
	SourcePublishedAt  *time.Time   `json:"source_published_at,omitempty"`
	SourceUrl          string       `json:"source_url"`
	State              string       `json:"state"`
	Title              string       `json:"title"`
	Version            int64        `json:"version"`
}

type PlatformAccessGrantInput struct {
	RoleCode string        `json:"role_code"`
	Scope    PlatformScope `json:"scope"`
}

type PlatformOperationResult struct {
	Operation       string  `json:"operation"`
	ResourceID      *string `json:"resource_id,omitempty"`
	ResourceVersion *int64  `json:"resource_version,omitempty"`
	Status          string  `json:"status"`
}

type PlatformOperationsAccount struct {
	AuthorizationRevision int64                      `json:"authorization_revision"`
	CreatedAt             time.Time                  `json:"created_at"`
	EmailVerified         bool                       `json:"email_verified"`
	Grants                []PlatformAccessGrantInput `json:"grants"`
	ID                    string                     `json:"id"`
	Status                string                     `json:"status"`
}

type PlatformOperationsAuditEvent struct {
	ActorUserID        string    `json:"actor_user_id"`
	CreatedAt          time.Time `json:"created_at"`
	Decision           string    `json:"decision"`
	PermissionCode     string    `json:"permission_code"`
	ReasonCode         string    `json:"reason_code"`
	RequestID          string    `json:"request_id"`
	TargetKind         string    `json:"target_kind"`
	TargetProductCode  *string   `json:"target_product_code,omitempty"`
	TargetResourceID   *string   `json:"target_resource_id,omitempty"`
	TargetResourceType *string   `json:"target_resource_type,omitempty"`
}

type PlatformOperationsDependencies struct {
	Postgres string `json:"postgres"`
	Redis    string `json:"redis"`
}

type PlatformOperationsInboxItem struct {
	CreatedAt          time.Time  `json:"created_at"`
	ID                 string     `json:"id"`
	OwnerUserID        *string    `json:"owner_user_id,omitempty"`
	Priority           string     `json:"priority"`
	SlaDueAt           *time.Time `json:"sla_due_at,omitempty"`
	SourceProductCode  string     `json:"source_product_code"`
	SourceResourceID   string     `json:"source_resource_id"`
	SourceResourceType string     `json:"source_resource_type"`
	SourceResourceUrl  *string    `json:"source_resource_url,omitempty"`
	Status             string     `json:"status"`
	UpdatedAt          time.Time  `json:"updated_at"`
	Version            int64      `json:"version"`
}

type PlatformOperationsMailStatus struct {
	Accepted    int64 `json:"accepted"`
	DeadLetters int64 `json:"dead_letters"`
	Delivered   int64 `json:"delivered"`
	Failed      int64 `json:"failed"`
	Pending     int64 `json:"pending"`
	Processing  int64 `json:"processing"`
	RetryDue    int64 `json:"retry_due"`
}

type PlatformOperationsSession struct {
	ClientID   *string    `json:"client_id,omitempty"`
	ExpiresAt  time.Time  `json:"expires_at"`
	ID         string     `json:"id"`
	Kind       string     `json:"kind"`
	LastSeenAt time.Time  `json:"last_seen_at"`
	RevokedAt  *time.Time `json:"revoked_at,omitempty"`
	UserID     string     `json:"user_id"`
}

type PlatformOperationsSnapshot struct {
	AccessContext ConsoleAccessContext           `json:"access_context"`
	Accounts      []PlatformOperationsAccount    `json:"accounts"`
	Audit         []PlatformOperationsAuditEvent `json:"audit"`
	Dependencies  PlatformOperationsDependencies `json:"dependencies"`
	GeneratedAt   time.Time                      `json:"generated_at"`
	InboxItems    []PlatformOperationsInboxItem  `json:"inbox_items"`
	Mail          PlatformOperationsMailStatus   `json:"mail"`
	Sessions      []PlatformOperationsSession    `json:"sessions"`
}

type PlatformScope struct {
	Kind         string  `json:"kind"`
	ProductCode  *string `json:"product_code,omitempty"`
	ResourceID   *string `json:"resource_id,omitempty"`
	ResourceType *string `json:"resource_type,omitempty"`
}

type ReviewPayload struct {
	ReviewReason *string `json:"reviewReason,omitempty"`
}

type RevokePlatformSessionRequest struct {
	ExpectedActive bool `json:"expected_active"`
}

type SubmissionReviewCommand struct {
	ExpectedVersion time.Time     `json:"expected_version"`
	Kind            string        `json:"kind"`
	Payload         ReviewPayload `json:"payload"`
	ResourceID      string        `json:"resource_id"`
}

type SuccessEnvelope struct {
	Data      any    `json:"data"`
	RequestID string `json:"request_id"`
}

type UpdatePlatformAccessRequest struct {
	ExpectedRevision int64                      `json:"expected_revision"`
	Grants           []PlatformAccessGrantInput `json:"grants"`
	Status           string                     `json:"status"`
}
