DROP TRIGGER account_operator_role_grant_audit_events_immutable ON account_operator_role_grant_audit_events;
DROP FUNCTION reject_account_operator_role_grant_audit_mutation();
DROP TABLE account_operator_role_grant_audit_events;
