// Code generated by cmd/contractgen from platform-core.yaml; DO NOT EDIT.
package contract

import (
	"fmt"
	"net/http"
	"net/url"
	"time"
)

const (
	AuthorizeRoute = "/api/v1/oauth/authorize"
	TokenRoute     = "/api/v1/oauth/token"
	SourceSHA256   = "fae4d59e3f5221a19f43bf2f9447c6260ea6c177d3fdccab7b5c66e14bd04c32"
)

const (
	IdempotencyKeyHeader = "Idempotency-Key"
	ServiceIDHeader      = "X-Service-Id"
	KeyIDHeader          = "X-Key-Id"
	TimestampHeader      = "X-Timestamp"
	NonceHeader          = "X-Nonce"
	SignatureHeader      = "X-Signature"
)

type ExchangeHeaders struct {
	IdempotencyKey string
	ServiceID      string
	KeyID          string
	Timestamp      string
	Nonce          string
	Signature      string
}

func ParseExchangeHeaders(values http.Header) (ExchangeHeaders, error) {
	var result ExchangeHeaders
	result.IdempotencyKey = values.Get(IdempotencyKeyHeader)
	if result.IdempotencyKey == "" {
		return ExchangeHeaders{}, fmt.Errorf("Idempotency-Key is required")
	}
	if len(result.IdempotencyKey) < 8 {
		return ExchangeHeaders{}, fmt.Errorf("Idempotency-Key is too short")
	}
	if len(result.IdempotencyKey) > 200 {
		return ExchangeHeaders{}, fmt.Errorf("Idempotency-Key is too long")
	}
	result.ServiceID = values.Get(ServiceIDHeader)
	if result.ServiceID == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Service-Id is required")
	}
	result.KeyID = values.Get(KeyIDHeader)
	if result.KeyID == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Key-Id is required")
	}
	result.Timestamp = values.Get(TimestampHeader)
	if result.Timestamp == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Timestamp is required")
	}
	result.Nonce = values.Get(NonceHeader)
	if result.Nonce == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Nonce is required")
	}
	result.Signature = values.Get(SignatureHeader)
	if result.Signature == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Signature is required")
	}
	return result, nil
}

type AuthorizeOAuthClientQuery struct {
	ResponseType        string
	ClientID            string
	RedirectURI         string
	State               string
	CodeChallenge       string
	CodeChallengeMethod string
}

func ParseAuthorizeOAuthClientQuery(values url.Values) (AuthorizeOAuthClientQuery, error) {
	var result AuthorizeOAuthClientQuery
	result.ResponseType = values.Get("response_type")
	if result.ResponseType == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("response_type is required")
	}
	if result.ResponseType != "code" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("response_type has an invalid value")
	}
	result.ClientID = values.Get("client_id")
	if result.ClientID == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("client_id is required")
	}
	result.RedirectURI = values.Get("redirect_uri")
	if result.RedirectURI == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("redirect_uri is required")
	}
	if _, err := url.ParseRequestURI(result.RedirectURI); err != nil {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("redirect_uri must be a URI")
	}
	result.State = values.Get("state")
	if result.State == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("state is required")
	}
	if len(result.State) < 8 {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("state is too short")
	}
	result.CodeChallenge = values.Get("code_challenge")
	if result.CodeChallenge == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge is required")
	}
	if len(result.CodeChallenge) < 43 {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge is too short")
	}
	if len(result.CodeChallenge) > 43 {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge is too long")
	}
	result.CodeChallengeMethod = values.Get("code_challenge_method")
	if result.CodeChallengeMethod == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge_method is required")
	}
	if result.CodeChallengeMethod != "S256" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge_method has an invalid value")
	}
	return result, nil
}

type ExchangeAuthorizationCodeRequest struct {
	GrantType    string `json:"grant_type"`
	Code         string `json:"code"`
	RedirectURI  string `json:"redirect_uri"`
	ClientID     string `json:"client_id"`
	CodeVerifier string `json:"code_verifier"`
}

type PlatformUser struct {
	UserID        string    `json:"user_id"`
	EmailVerified bool      `json:"email_verified"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
}

type ExchangeAuthorizationCodeResponse struct {
	User                 PlatformUser `json:"user"`
	SessionExchangeToken string       `json:"session_exchange_token"`
	ExpiresAt            time.Time    `json:"expires_at"`
}

type SuccessEnvelope[T any] struct {
	Data      T      `json:"data"`
	RequestID string `json:"request_id"`
}

type ErrorObject struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Details *map[string]any `json:"details,omitempty"`
}

type ErrorEnvelope struct {
	Error     ErrorObject `json:"error"`
	RequestID string      `json:"request_id"`
}
