// Code generated by cmd/contractgen from platform-core.yaml; DO NOT EDIT.
package contract

import "time"

const (
	AuthorizeRoute = "/api/v1/oauth/authorize"
	TokenRoute     = "/api/v1/oauth/token"
	SourceSHA256   = "fae4d59e3f5221a19f43bf2f9447c6260ea6c177d3fdccab7b5c66e14bd04c32"
)

type ExchangeAuthorizationCodeRequest struct {
	GrantType    string `json:"grant_type"`
	Code         string `json:"code"`
	RedirectURI  string `json:"redirect_uri"`
	ClientID     string `json:"client_id"`
	CodeVerifier string `json:"code_verifier"`
}

type PlatformUser struct {
	UserID        string    `json:"user_id"`
	EmailVerified bool      `json:"email_verified"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
}

type ExchangeAuthorizationCodeResponse struct {
	User                 PlatformUser `json:"user"`
	SessionExchangeToken string       `json:"session_exchange_token"`
	ExpiresAt            time.Time    `json:"expires_at"`
}
