// Code generated by cmd/contractgen from platform-core.yaml; DO NOT EDIT.
package contract

import (
	"fmt"
	"net/http"
	"net/url"
	"time"
)

const (
	AuthorizeRoute                       = "/api/v1/oauth/authorize"
	TokenRoute                           = "/api/v1/oauth/token"
	AuthorizationCheckRoute              = "/api/v1/authorization/check"
	RequestVerificationCodeRoute         = "/api/v1/auth/email-codes"
	VerifyVerificationCodeRoute          = "/api/v1/auth/email-codes/verify"
	RecordMailDeliveryRoute              = "/api/v1/mail/deliveries"
	ListOperationsInboxRoute             = "/api/v1/operations-inbox/items"
	GetOperationsInboxRoute              = "/api/v1/operations-inbox/items/{item_id}"
	CreateOperationsInboxRoute           = "/api/v1/operations-inbox/items"
	UpdateOperationsInboxRoute           = "/api/v1/operations-inbox/items/{item_id}/updates"
	OperationsInboxOperationStatusRoute  = "/api/v1/operations-inbox/operations/{operation}"
	PlatformOperationsRoute              = "/api/v1/platform-operations"
	RevokePlatformOperationSessionRoute  = "/api/v1/platform-operations/sessions/{session_id}/revocations"
	UpdatePlatformOperationAccessRoute   = "/api/v1/platform-operations/users/{user_id}/access-updates"
	PlatformOperationStatusRoute         = "/api/v1/platform-operations/operations/{operation}"
	PlatformOperationsAccountLookupRoute = "/api/v1/platform-operations/account-lookups"
	ConsoleUserIdentityResolutionRoute   = "/api/v1/console-user-identities/resolutions"
	SourceSHA256                         = "85e4df71c133c4019204356a7f63da3f1341a87926b679d5ae98bc6c5a730c17"
)

const SessionExchangeTokenHeader = "X-Session-Exchange-Token"

const (
	IdempotencyKeyHeader = "Idempotency-Key"
	ServiceIDHeader      = "X-Service-Id"
	KeyIDHeader          = "X-Key-Id"
	TimestampHeader      = "X-Timestamp"
	NonceHeader          = "X-Nonce"
	SignatureHeader      = "X-Signature"
)

type ExchangeHeaders struct {
	IdempotencyKey string
	ServiceID      string
	KeyID          string
	Timestamp      string
	Nonce          string
	Signature      string
}

func ParseExchangeHeaders(values http.Header) (ExchangeHeaders, error) {
	var result ExchangeHeaders
	result.IdempotencyKey = values.Get(IdempotencyKeyHeader)
	if result.IdempotencyKey == "" {
		return ExchangeHeaders{}, fmt.Errorf("Idempotency-Key is required")
	}
	if len(result.IdempotencyKey) < 8 {
		return ExchangeHeaders{}, fmt.Errorf("Idempotency-Key is too short")
	}
	if len(result.IdempotencyKey) > 200 {
		return ExchangeHeaders{}, fmt.Errorf("Idempotency-Key is too long")
	}
	result.ServiceID = values.Get(ServiceIDHeader)
	if result.ServiceID == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Service-Id is required")
	}
	result.KeyID = values.Get(KeyIDHeader)
	if result.KeyID == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Key-Id is required")
	}
	result.Timestamp = values.Get(TimestampHeader)
	if result.Timestamp == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Timestamp is required")
	}
	result.Nonce = values.Get(NonceHeader)
	if result.Nonce == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Nonce is required")
	}
	result.Signature = values.Get(SignatureHeader)
	if result.Signature == "" {
		return ExchangeHeaders{}, fmt.Errorf("X-Signature is required")
	}
	return result, nil
}

type AuthorizeOAuthClientQuery struct {
	ResponseType        string
	ClientID            string
	RedirectURI         string
	State               string
	CodeChallenge       string
	CodeChallengeMethod string
}

func ParseAuthorizeOAuthClientQuery(values url.Values) (AuthorizeOAuthClientQuery, error) {
	var result AuthorizeOAuthClientQuery
	result.ResponseType = values.Get("response_type")
	if result.ResponseType == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("response_type is required")
	}
	if result.ResponseType != "code" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("response_type has an invalid value")
	}
	result.ClientID = values.Get("client_id")
	if result.ClientID == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("client_id is required")
	}
	result.RedirectURI = values.Get("redirect_uri")
	if result.RedirectURI == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("redirect_uri is required")
	}
	if _, err := url.ParseRequestURI(result.RedirectURI); err != nil {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("redirect_uri must be a URI")
	}
	result.State = values.Get("state")
	if result.State == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("state is required")
	}
	if len(result.State) < 8 {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("state is too short")
	}
	result.CodeChallenge = values.Get("code_challenge")
	if result.CodeChallenge == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge is required")
	}
	if len(result.CodeChallenge) < 43 {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge is too short")
	}
	if len(result.CodeChallenge) > 43 {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge is too long")
	}
	result.CodeChallengeMethod = values.Get("code_challenge_method")
	if result.CodeChallengeMethod == "" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge_method is required")
	}
	if result.CodeChallengeMethod != "S256" {
		return AuthorizeOAuthClientQuery{}, fmt.Errorf("code_challenge_method has an invalid value")
	}
	return result, nil
}

type ExchangeAuthorizationCodeRequest struct {
	GrantType    string `json:"grant_type"`
	Code         string `json:"code"`
	RedirectURI  string `json:"redirect_uri"`
	ClientID     string `json:"client_id"`
	CodeVerifier string `json:"code_verifier"`
}

type PlatformUser struct {
	UserID        string    `json:"user_id"`
	EmailVerified bool      `json:"email_verified"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	DisplayName   *string   `json:"display_name,omitempty"`
}

type ExchangeAuthorizationCodeResponse struct {
	User                 PlatformUser `json:"user"`
	SessionExchangeToken string       `json:"session_exchange_token"`
	ExpiresAt            time.Time    `json:"expires_at"`
}

type AuthorizationScope struct {
	Kind         string  `json:"kind"`
	ProductCode  *string `json:"product_code,omitempty"`
	ResourceID   *string `json:"resource_id,omitempty"`
	ResourceType *string `json:"resource_type,omitempty"`
}

type AuthorizationCheckRequest struct {
	SessionExchangeToken string             `json:"session_exchange_token"`
	PermissionCode       string             `json:"permission_code"`
	Scope                AuthorizationScope `json:"scope"`
}

type AuthorizationDecision struct {
	Allowed               bool               `json:"allowed"`
	ActorUserID           string             `json:"actor_user_id"`
	PermissionCode        string             `json:"permission_code"`
	Scope                 AuthorizationScope `json:"scope"`
	GrantID               string             `json:"grant_id"`
	AuthorizationRevision int64              `json:"authorization_revision"`
	CheckedAt             time.Time          `json:"checked_at"`
}

type SuccessEnvelope[T any] struct {
	Data      T      `json:"data"`
	RequestID string `json:"request_id"`
}

type ErrorObject struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Details *map[string]any `json:"details,omitempty"`
}

type ErrorEnvelope struct {
	Error     ErrorObject `json:"error"`
	RequestID string      `json:"request_id"`
}

type RequestVerificationCodeRequest struct {
	Email    string  `json:"email"`
	Purpose  string  `json:"purpose"`
	ClientID *string `json:"client_id,omitempty"`
}

type VerificationCodeAccepted struct {
	ExpiresAt   time.Time `json:"expires_at"`
	ResendAfter time.Time `json:"resend_after"`
}

type VerifyVerificationCodeRequest struct {
	Email         string  `json:"email"`
	Code          string  `json:"code"`
	Purpose       string  `json:"purpose"`
	LoginIntentID *string `json:"login_intent_id,omitempty"`
}

type VerificationCodeVerified struct {
	VerificationID   string        `json:"verification_id"`
	SessionExpiresAt *time.Time    `json:"session_expires_at,omitempty"`
	User             *PlatformUser `json:"user,omitempty"`
}

type RecordMailDeliveryRequest struct {
	MessageID string `json:"message_id"`
	Status    string `json:"status"`
}

type MailDeliveryAccepted struct {
	Accepted bool `json:"accepted"`
}

type OperationsInboxItem struct {
	ID                 string     `json:"id"`
	SourceProductCode  string     `json:"source_product_code"`
	SourceResourceType string     `json:"source_resource_type"`
	SourceResourceID   string     `json:"source_resource_id"`
	Priority           string     `json:"priority"`
	Status             string     `json:"status"`
	Version            int64      `json:"version"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	OwnerUserID        *string    `json:"owner_user_id,omitempty"`
	SlaDueAt           *time.Time `json:"sla_due_at,omitempty"`
	SourceResourceURL  *string    `json:"source_resource_url,omitempty"`
}

type CreateOperationsInboxItemRequest struct {
	SourceProductCode  string     `json:"source_product_code"`
	SourceResourceType string     `json:"source_resource_type"`
	SourceResourceID   string     `json:"source_resource_id"`
	Priority           string     `json:"priority"`
	OwnerUserID        *string    `json:"owner_user_id,omitempty"`
	SlaDueAt           *time.Time `json:"sla_due_at,omitempty"`
	SourceResourceURL  *string    `json:"source_resource_url,omitempty"`
	Status             *string    `json:"status,omitempty"`
}

type UpdateOperationsInboxItemRequest struct {
	SourceProductCode  string     `json:"source_product_code"`
	SourceResourceType string     `json:"source_resource_type"`
	SourceResourceID   string     `json:"source_resource_id"`
	ExpectedVersion    int64      `json:"expected_version"`
	ClearOwner         *bool      `json:"clear_owner,omitempty"`
	ClearSla           *bool      `json:"clear_sla,omitempty"`
	OwnerUserID        *string    `json:"owner_user_id,omitempty"`
	Priority           *string    `json:"priority,omitempty"`
	SlaDueAt           *time.Time `json:"sla_due_at,omitempty"`
	Status             *string    `json:"status,omitempty"`
}

type OperationsInboxOperationStatus struct {
	Status string               `json:"status"`
	Item   *OperationsInboxItem `json:"item,omitempty"`
}

type PlatformOperationsAccountLookupRequest struct {
	Email string `json:"email"`
}

type PlatformOperationsAccountLookupAccount struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	Status      string  `json:"status"`
	DisplayName *string `json:"display_name,omitempty"`
}

type PlatformOperationsAccountLookupResult struct {
	Account *PlatformOperationsAccountLookupAccount `json:"account"`
}
