// Code generated by portal-gateway/cmd/contractgen from portal-gateway.yaml (SHA256 56d95a241ee121f7abaf9aee47703a48a428785b0c1bc014471bbd42e2eda695); DO NOT EDIT.
export interface PortalSession {
  display_name?: string;
  expires_at: string;
  user_id: string;
}

export interface MasterySubject {
  bank_id: string;
  label: string;
  value: number;
  total_questions: number;
  correct_questions: number;
}

export interface PersonalPracticeStats {
  total_answers: number;
  correct_answers: number;
  accuracy: number;
  streak_days: number;
  mastery: MasterySubject[];
}

export interface PersonalPracticeStatsEnvelope {
  request_id: string;
  data: PersonalPracticeStats;
}
