// Code generated by portal-gateway/cmd/contractgen from portal-gateway.yaml (SHA256 4cc511563e8f674e29520348697d9ce3720ff716903fd9c8604c4c762634b9ca); DO NOT EDIT.
export interface PortalSession {
  display_name?: string;
  expires_at: string;
  user_id: string;
}

export interface MasterySubject {
  bank_id: string;
  label: string;
  value: number;
  total_questions: number;
  correct_questions: number;
}

export interface PersonalPracticeStats {
  total_answers: number;
  correct_answers: number;
  accuracy: number;
  streak_days: number;
  mastery: MasterySubject[];
}

export interface PersonalPracticeStatsEnvelope {
  request_id: string;
  data: PersonalPracticeStats;
}

export interface PortalNoticeSource {
  name: string;
  url: string;
}

export interface PortalNotice {
  id: string;
  title: string;
  body: string;
  source: PortalNoticeSource;
  created_at: string;
}

export interface PortalNoticeFeed {
  notices: PortalNotice[];
}

export interface NoticeSummary {
  id: string;
  title: string;
  source: string;
  published_at: string;
}

export interface PortalNoticeFeedEnvelope {
  request_id: string;
  notices: NoticeSummary[];
  data?: PortalNoticeFeed;
}
