// Code generated by portal-gateway/cmd/contractgen from portal-gateway.yaml (SHA256 fdb76e0b4f559e3d39cb2486b5c986c31d0d9c51d5b40406babf167c3c586335); DO NOT EDIT.
export interface PortalSession {
  display_name?: string;
  expires_at: string;
  user_id: string;
}

export interface MasterySubject {
  bank_id: string;
  label: string;
  value: number;
  total_questions: number;
  correct_questions: number;
}

export interface PersonalPracticeStats {
  total_answers: number;
  correct_answers: number;
  accuracy: number;
  streak_days: number;
  mastery: MasterySubject[];
}

export interface PersonalPracticeStatsEnvelope {
  request_id: string;
  data: PersonalPracticeStats;
}

export interface QuizCraftCatalogChapter {
  id: string;
  name: string;
}

export interface QuizCraftCatalogBank {
  bank_id: string;
  bank_version_id: string;
  name: string;
  question_count: number;
  available: boolean;
  chapters: QuizCraftCatalogChapter[];
}

export interface QuizCraftCatalogResponse {
  banks: QuizCraftCatalogBank[];
  request_id: string;
}
