package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

type schema struct {
	Type       schemaType        `yaml:"type"`
	Format     string            `yaml:"format"`
	Required   []string          `yaml:"required"`
	Properties map[string]schema `yaml:"properties"`
}

// schemaType accepts the OpenAPI 3.1 scalar and union forms. This generator
// only emits PortalSession, but it must still parse the full public contract.
type schemaType []string

func (value *schemaType) UnmarshalYAML(node *yaml.Node) error {
	switch node.Kind {
	case yaml.ScalarNode:
		*value = schemaType{node.Value}
		return nil
	case yaml.SequenceNode:
		result := make(schemaType, 0, len(node.Content))
		for _, item := range node.Content {
			if item.Kind != yaml.ScalarNode {
				return fmt.Errorf("OpenAPI schema type item must be a scalar")
			}
			result = append(result, item.Value)
		}
		*value = result
		return nil
	default:
		return fmt.Errorf("OpenAPI schema type must be a scalar or sequence")
	}
}

func (value schemaType) isExactly(want string) bool {
	return len(value) == 1 && value[0] == want
}

type document struct {
	Components struct {
		Schemas map[string]schema `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	contractPath := flag.String("contract", "../../packages/api-contracts/openapi/portal-gateway.yaml", "OpenAPI contract")
	goOutput := flag.String("go-output", "internal/contract/portal_session.generated.go", "generated Go output")
	tsOutput := flag.String("ts-output", "../../apps/portal/src/lib/api/portal-session.generated.ts", "generated TypeScript output")
	flag.Parse()

	source, err := os.ReadFile(*contractPath)
	if err != nil {
		fail(err)
	}
	var spec document
	if err := yaml.Unmarshal(source, &spec); err != nil {
		fail(fmt.Errorf("parse OpenAPI: %w", err))
	}
	portalSession, ok := spec.Components.Schemas["PortalSession"]
	if !ok || !portalSession.Type.isExactly("object") {
		fail(fmt.Errorf("PortalSession object schema is missing"))
	}
	for _, property := range []string{"user_id", "display_name", "expires_at"} {
		if _, exists := portalSession.Properties[property]; !exists {
			fail(fmt.Errorf("PortalSession.%s is missing", property))
		}
	}

	digest := fmt.Sprintf("%x", sha256.Sum256(source))
	goSource, err := format.Source([]byte(renderGo(portalSession, digest)))
	if err != nil {
		fail(fmt.Errorf("format generated Go: %w", err))
	}
	write(*goOutput, goSource)
	write(*tsOutput, []byte(renderTypeScript(portalSession, digest)))
}

func renderGo(value schema, digest string) string {
	required := stringSet(value.Required)
	var fields strings.Builder
	for _, property := range sortedProperties(value.Properties) {
		fieldType := goType(value.Properties[property])
		tag := property
		if !required[property] {
			fieldType = "*" + fieldType
			tag += ",omitempty"
		}
		fmt.Fprintf(&fields, "\t%s %s `json:\"%s\"`\n", goName(property), fieldType, tag)
	}
	return fmt.Sprintf(`// Code generated by cmd/contractgen from portal-gateway.yaml; DO NOT EDIT.
package contract

import "time"

const PortalSessionSourceSHA256 = %q

type PortalSession struct {
%s}
`, digest, fields.String())
}

func renderTypeScript(value schema, digest string) string {
	required := stringSet(value.Required)
	var fields strings.Builder
	for _, property := range sortedProperties(value.Properties) {
		optional := ""
		if !required[property] {
			optional = "?"
		}
		fmt.Fprintf(&fields, "  %s%s: %s;\n", property, optional, tsType(value.Properties[property]))
	}
	return fmt.Sprintf(`// Code generated by portal-gateway/cmd/contractgen from portal-gateway.yaml (SHA256 %s); DO NOT EDIT.
export interface PortalSession {
%s}
`, digest, fields.String())
}

func goType(value schema) string {
	if value.Type.isExactly("string") && value.Format == "date-time" {
		return "time.Time"
	}
	if value.Type.isExactly("string") {
		return "string"
	}
	fail(fmt.Errorf("unsupported Go schema type %q format %q", []string(value.Type), value.Format))
	return ""
}

func tsType(value schema) string {
	if value.Type.isExactly("string") {
		return "string"
	}
	fail(fmt.Errorf("unsupported TypeScript schema type %q", []string(value.Type)))
	return ""
}

func sortedProperties(properties map[string]schema) []string {
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func stringSet(values []string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}

func goName(value string) string {
	var output []rune
	upper := true
	for _, char := range value {
		if char == '_' || char == '-' {
			upper = true
			continue
		}
		if upper {
			char = unicode.ToUpper(char)
			upper = false
		}
		output = append(output, char)
	}
	return strings.ReplaceAll(string(output), "Id", "ID")
}

func write(path string, content []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
