package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

type schema struct {
	Type       schemaType        `yaml:"type"`
	Format     string            `yaml:"format"`
	Required   []string          `yaml:"required"`
	Properties map[string]schema `yaml:"properties"`
	Items      *schema           `yaml:"items"`
	Ref        string            `yaml:"$ref"`
}

// schemaType accepts the OpenAPI 3.1 scalar and union forms. This generator
// only emits PortalSession, but it must still parse the full public contract.
type schemaType []string

func (value *schemaType) UnmarshalYAML(node *yaml.Node) error {
	switch node.Kind {
	case yaml.ScalarNode:
		*value = schemaType{node.Value}
		return nil
	case yaml.SequenceNode:
		result := make(schemaType, 0, len(node.Content))
		for _, item := range node.Content {
			if item.Kind != yaml.ScalarNode {
				return fmt.Errorf("OpenAPI schema type item must be a scalar")
			}
			result = append(result, item.Value)
		}
		*value = result
		return nil
	default:
		return fmt.Errorf("OpenAPI schema type must be a scalar or sequence")
	}
}

func (value schemaType) isExactly(want string) bool {
	return len(value) == 1 && value[0] == want
}

type document struct {
	Components struct {
		Schemas map[string]schema `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	contractPath := flag.String("contract", "../../packages/api-contracts/openapi/portal-gateway.yaml", "OpenAPI contract")
	goOutput := flag.String("go-output", "internal/contract/portal_session.generated.go", "generated Go output")
	tsOutput := flag.String("ts-output", "../../apps/portal/src/lib/api/portal-session.generated.ts", "generated TypeScript output")
	flag.Parse()

	source, err := os.ReadFile(*contractPath)
	if err != nil {
		fail(err)
	}
	var spec document
	if err := yaml.Unmarshal(source, &spec); err != nil {
		fail(fmt.Errorf("parse OpenAPI: %w", err))
	}
	portalSession, ok := spec.Components.Schemas["PortalSession"]
	if !ok || !portalSession.Type.isExactly("object") {
		fail(fmt.Errorf("PortalSession object schema is missing"))
	}
	for _, property := range []string{"user_id", "display_name", "expires_at"} {
		if _, exists := portalSession.Properties[property]; !exists {
			fail(fmt.Errorf("PortalSession.%s is missing", property))
		}
	}
	validatePersonalPracticeStats(spec.Components.Schemas)
	if err := validateQuizCraftCatalog(spec.Components.Schemas); err != nil {
		fail(err)
	}

	digest := fmt.Sprintf("%x", sha256.Sum256(source))
	goSource, err := format.Source([]byte(renderGo(portalSession, digest)))
	if err != nil {
		fail(fmt.Errorf("format generated Go: %w", err))
	}
	write(*goOutput, goSource)
	write(*tsOutput, []byte(renderTypeScript(portalSession, digest)))
}

func renderGo(value schema, digest string) string {
	required := stringSet(value.Required)
	var fields strings.Builder
	for _, property := range sortedProperties(value.Properties) {
		fieldType := goType(value.Properties[property])
		tag := property
		if !required[property] {
			fieldType = "*" + fieldType
			tag += ",omitempty"
		}
		fmt.Fprintf(&fields, "\t%s %s `json:\"%s\"`\n", goName(property), fieldType, tag)
	}
	return fmt.Sprintf(`// Code generated by cmd/contractgen from portal-gateway.yaml; DO NOT EDIT.
package contract

import "time"

const PortalSessionSourceSHA256 = %q

type PortalSession struct {
%s}

type MasterySubject struct {
	BankID           string `+"`json:\"bank_id\"`"+`
	Label            string `+"`json:\"label\"`"+`
	Value            int    `+"`json:\"value\"`"+`
	TotalQuestions   int64  `+"`json:\"total_questions\"`"+`
	CorrectQuestions int64  `+"`json:\"correct_questions\"`"+`
}

type PersonalPracticeStats struct {
	TotalAnswers   int64            `+"`json:\"total_answers\"`"+`
	CorrectAnswers int64            `+"`json:\"correct_answers\"`"+`
	Accuracy       int              `+"`json:\"accuracy\"`"+`
	StreakDays     int              `+"`json:\"streak_days\"`"+`
	Mastery        []MasterySubject `+"`json:\"mastery\"`"+`
}

type PersonalPracticeStatsEnvelope struct {
	RequestID string                `+"`json:\"request_id\"`"+`
	Data      PersonalPracticeStats `+"`json:\"data\"`"+`
}

type QuizCraftCatalogChapter struct {
	ID   string `+"`json:\"id\"`"+`
	Name string `+"`json:\"name\"`"+`
}

type QuizCraftCatalogBank struct {
	BankID        string                    `+"`json:\"bank_id\"`"+`
	BankVersionID string                    `+"`json:\"bank_version_id\"`"+`
	Name          string                    `+"`json:\"name\"`"+`
	QuestionCount int                       `+"`json:\"question_count\"`"+`
	Available     bool                      `+"`json:\"available\"`"+`
	Chapters      []QuizCraftCatalogChapter `+"`json:\"chapters\"`"+`
}

type QuizCraftCatalogResponse struct {
	Banks     []QuizCraftCatalogBank `+"`json:\"banks\"`"+`
	RequestID string                 `+"`json:\"request_id\"`"+`
}
`, digest, fields.String())
}

func renderTypeScript(value schema, digest string) string {
	required := stringSet(value.Required)
	var fields strings.Builder
	for _, property := range sortedProperties(value.Properties) {
		optional := ""
		if !required[property] {
			optional = "?"
		}
		fmt.Fprintf(&fields, "  %s%s: %s;\n", property, optional, tsType(value.Properties[property]))
	}
	return fmt.Sprintf(`// Code generated by portal-gateway/cmd/contractgen from portal-gateway.yaml (SHA256 %s); DO NOT EDIT.
export interface PortalSession {
%s}

export interface MasterySubject {
  bank_id: string;
  label: string;
  value: number;
  total_questions: number;
  correct_questions: number;
}

export interface PersonalPracticeStats {
  total_answers: number;
  correct_answers: number;
  accuracy: number;
  streak_days: number;
  mastery: MasterySubject[];
}

export interface PersonalPracticeStatsEnvelope {
  request_id: string;
  data: PersonalPracticeStats;
}

export interface QuizCraftCatalogChapter {
  id: string;
  name: string;
}

export interface QuizCraftCatalogBank {
  bank_id: string;
  bank_version_id: string;
  name: string;
  question_count: number;
  available: boolean;
  chapters: QuizCraftCatalogChapter[];
}

export interface QuizCraftCatalogResponse {
  banks: QuizCraftCatalogBank[];
  request_id: string;
}
`, digest, fields.String())
}

func validateQuizCraftCatalog(schemas map[string]schema) error {
	catalog, ok := schemas["QuizCraftCatalogResponse"]
	if !ok {
		return fmt.Errorf("QuizCraftCatalogResponse object schema is missing")
	}
	if err := requireExactObject(catalog, "QuizCraftCatalogResponse", []string{"banks", "request_id"}); err != nil {
		return err
	}
	if err := requireExactScalar(catalog.Properties["request_id"], "QuizCraftCatalogResponse.request_id", "string", ""); err != nil {
		return err
	}

	bank, err := requireExactArrayItem(catalog.Properties["banks"], "QuizCraftCatalogResponse.banks")
	if err != nil {
		return err
	}
	bankProperties := []string{"bank_id", "bank_version_id", "name", "question_count", "available", "chapters"}
	if err := requireExactObject(*bank, "QuizCraftCatalogResponse.banks[]", bankProperties); err != nil {
		return err
	}
	for _, property := range []string{"bank_id", "bank_version_id"} {
		if err := requireExactScalar(bank.Properties[property], "QuizCraftCatalogResponse.banks[]."+property, "string", "uuid"); err != nil {
			return err
		}
	}
	for _, scalar := range []struct {
		property   string
		scalarType string
	}{
		{property: "name", scalarType: "string"},
		{property: "question_count", scalarType: "integer"},
		{property: "available", scalarType: "boolean"},
	} {
		if err := requireExactScalar(bank.Properties[scalar.property], "QuizCraftCatalogResponse.banks[]."+scalar.property, scalar.scalarType, ""); err != nil {
			return err
		}
	}

	chapter, err := requireExactArrayItem(bank.Properties["chapters"], "QuizCraftCatalogResponse.banks[].chapters")
	if err != nil {
		return err
	}
	if err := requireExactObject(*chapter, "QuizCraftCatalogResponse.banks[].chapters[]", []string{"id", "name"}); err != nil {
		return err
	}
	for _, property := range []string{"id", "name"} {
		if err := requireExactScalar(chapter.Properties[property], "QuizCraftCatalogResponse.banks[].chapters[]."+property, "string", ""); err != nil {
			return err
		}
	}
	return nil
}

func requireExactObject(value schema, path string, properties []string) error {
	if !value.Type.isExactly("object") || value.Format != "" {
		return fmt.Errorf("%s must be an object without a format", path)
	}
	if !sameNames(sortedProperties(value.Properties), properties) {
		return fmt.Errorf("%s properties must be exactly %v", path, properties)
	}
	if !sameNames(value.Required, properties) {
		return fmt.Errorf("%s required properties must be exactly %v", path, properties)
	}
	return nil
}

func requireExactArrayItem(value schema, path string) (*schema, error) {
	if !value.Type.isExactly("array") || value.Format != "" || value.Items == nil {
		return nil, fmt.Errorf("%s must be an array without a format", path)
	}
	return value.Items, nil
}

func requireExactScalar(value schema, path, scalarType, format string) error {
	if !value.Type.isExactly(scalarType) || value.Format != format {
		return fmt.Errorf("%s must be %s with format %q", path, scalarType, format)
	}
	return nil
}

func sameNames(got, want []string) bool {
	gotCopy := append([]string(nil), got...)
	wantCopy := append([]string(nil), want...)
	sort.Strings(gotCopy)
	sort.Strings(wantCopy)
	if len(gotCopy) != len(wantCopy) {
		return false
	}
	for index := range gotCopy {
		if gotCopy[index] != wantCopy[index] {
			return false
		}
	}
	return true
}

func validatePersonalPracticeStats(schemas map[string]schema) {
	requireObjectSchema(schemas, "PersonalPracticeStatsEnvelope", []string{"request_id", "data"})
	envelope := schemas["PersonalPracticeStatsEnvelope"]
	if data := envelope.Properties["data"]; data.Ref != "#/components/schemas/PersonalPracticeStats" {
		fail(fmt.Errorf("PersonalPracticeStatsEnvelope.data must reference PersonalPracticeStats"))
	}

	requireObjectSchema(schemas, "PersonalPracticeStats", []string{"total_answers", "correct_answers", "accuracy", "streak_days", "mastery"})
	stats := schemas["PersonalPracticeStats"]
	for _, property := range []string{"total_answers", "correct_answers", "accuracy", "streak_days"} {
		if !stats.Properties[property].Type.isExactly("integer") {
			fail(fmt.Errorf("PersonalPracticeStats.%s must be integer", property))
		}
	}
	if mastery := stats.Properties["mastery"]; !mastery.Type.isExactly("array") || mastery.Items == nil || mastery.Items.Ref != "#/components/schemas/MasterySubject" {
		fail(fmt.Errorf("PersonalPracticeStats.mastery must reference MasterySubject items"))
	}

	requireObjectSchema(schemas, "MasterySubject", []string{"bank_id", "label", "value", "total_questions", "correct_questions"})
	subject := schemas["MasterySubject"]
	for _, property := range []string{"bank_id", "label"} {
		if !subject.Properties[property].Type.isExactly("string") {
			fail(fmt.Errorf("MasterySubject.%s must be string", property))
		}
	}
	for _, property := range []string{"value", "total_questions", "correct_questions"} {
		if !subject.Properties[property].Type.isExactly("integer") {
			fail(fmt.Errorf("MasterySubject.%s must be integer", property))
		}
	}
}

func requireObjectSchema(schemas map[string]schema, name string, required []string) {
	value, ok := schemas[name]
	if !ok || !value.Type.isExactly("object") {
		fail(fmt.Errorf("%s object schema is missing", name))
	}
	for _, property := range required {
		if !contains(value.Required, property) || (len(value.Properties[property].Type) == 0 && value.Properties[property].Ref == "") {
			fail(fmt.Errorf("%s.%s is missing or not required", name, property))
		}
	}
}

func goType(value schema) string {
	if value.Type.isExactly("string") && value.Format == "date-time" {
		return "time.Time"
	}
	if value.Type.isExactly("string") {
		return "string"
	}
	fail(fmt.Errorf("unsupported Go schema type %q format %q", []string(value.Type), value.Format))
	return ""
}

func tsType(value schema) string {
	if value.Type.isExactly("string") {
		return "string"
	}
	fail(fmt.Errorf("unsupported TypeScript schema type %q", []string(value.Type)))
	return ""
}

func sortedProperties(properties map[string]schema) []string {
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func stringSet(values []string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func goName(value string) string {
	var output []rune
	upper := true
	for _, char := range value {
		if char == '_' || char == '-' {
			upper = true
			continue
		}
		if upper {
			char = unicode.ToUpper(char)
			upper = false
		}
		output = append(output, char)
	}
	return strings.ReplaceAll(string(output), "Id", "ID")
}

func write(path string, content []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
