package worker

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"time"

	redislib "github.com/redis/go-redis/v9"
	"gorm.io/datatypes"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	"final-review-platform/services/worker/pkg/config"
)

type Runner struct {
	cfg config.Config
	log *slog.Logger
}

func NewRunner(cfg config.Config, log *slog.Logger) Runner {
	return Runner{cfg: cfg, log: log}
}

func (r Runner) Run(ctx context.Context) error {
	db, err := gorm.Open(postgres.Open(r.cfg.DatabaseURL), &gorm.Config{})
	if err != nil {
		return err
	}
	client := redislib.NewClient(&redislib.Options{
		Addr:     r.cfg.RedisAddr,
		Password: r.cfg.RedisPassword,
		DB:       r.cfg.RedisDB,
	})
	defer client.Close()

	if err := client.Ping(ctx).Err(); err != nil {
		return err
	}

	processor := Processor{db: db, log: r.log, llmMode: r.cfg.LLMMode}
	r.log.Info("worker started", slog.String("environment", r.cfg.Environment), slog.String("llm_mode", r.cfg.LLMMode))
	lastID := "0"
	for {
		if err := processor.ProcessNextPending(ctx); err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			r.log.Error("pending task processing failed", slog.String("error", err.Error()))
		}

		streams, err := client.XRead(ctx, &redislib.XReadArgs{
			Streams: []string{r.cfg.TaskStream, lastID},
			Count:   1,
			Block:   5 * time.Second,
		}).Result()
		if errors.Is(err, context.Canceled) || errors.Is(ctx.Err(), context.Canceled) {
			r.log.Info("worker shutdown requested")
			return nil
		}
		if err != nil && !errors.Is(err, redislib.Nil) {
			r.log.Error("redis stream read failed", slog.String("error", err.Error()))
			continue
		}
		for _, stream := range streams {
			for _, message := range stream.Messages {
				lastID = message.ID
				taskID, _ := message.Values["task_id"].(string)
				if taskID == "" {
					continue
				}
				if err := processor.ProcessTask(ctx, taskID); err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
					r.log.Error("stream task processing failed", slog.String("task_id", taskID), slog.String("error", err.Error()))
				}
			}
		}
	}
}

type Processor struct {
	db      *gorm.DB
	log     *slog.Logger
	llmMode string
}

func (p Processor) ProcessNextPending(ctx context.Context) error {
	var task aiTask
	if err := p.db.WithContext(ctx).Where("status = ?", taskPending).Order("created_at asc").First(&task).Error; err != nil {
		return err
	}
	return p.ProcessTask(ctx, task.ID)
}

func (p Processor) ProcessTask(ctx context.Context, taskID string) error {
	return p.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var task aiTask
		if err := tx.First(&task, "id = ?", taskID).Error; err != nil {
			return err
		}
		if task.Status != taskPending {
			return nil
		}

		startedAt := time.Now()
		if err := tx.Model(&task).Updates(map[string]interface{}{
			"status":     taskProcessing,
			"started_at": startedAt,
			"error":      "",
		}).Error; err != nil {
			return err
		}

		result := p.mockResult(task)
		draft := aiDraft{
			Status:       statusPending,
			TaskID:       task.ID,
			CourseID:     task.CourseID,
			OutputType:   task.Type,
			DraftContent: result,
		}
		if err := tx.Create(&draft).Error; err != nil {
			return err
		}

		endedAt := time.Now()
		if err := tx.Model(&task).Updates(map[string]interface{}{
			"status":   taskCompleted,
			"result":   result,
			"ended_at": endedAt,
		}).Error; err != nil {
			return err
		}

		usage := aiUsageLog{
			UserID:    task.UserID,
			TaskID:    &task.ID,
			Model:     fmt.Sprintf("%s-llm", p.llmMode),
			TokensIn:  120,
			TokensOut: 80,
			CostFen:   0,
		}
		return tx.Create(&usage).Error
	})
}

func (p Processor) mockResult(task aiTask) datatypes.JSON {
	payload := map[string]string{
		"title":        fmt.Sprintf("%s mock draft", task.Type),
		"summary":      "Mock AI result generated by worker. It is saved as a draft and must be reviewed before publication.",
		"sourceTaskId": task.ID,
	}
	data, err := json.Marshal(payload)
	if err != nil {
		return datatypes.JSON([]byte(`{"summary":"Mock AI result generated by worker. It is saved as a draft and must be reviewed before publication."}`))
	}
	return datatypes.JSON(data)
}
