package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

type document struct {
	Servers []struct {
		URL string `yaml:"url"`
	} `yaml:"servers"`
	Paths map[string]map[string]struct {
		OperationID string `yaml:"operationId"`
	} `yaml:"paths"`
}

func main() {
	contractPath := flag.String("contract", "../../packages/api-contracts/openapi/console-gateway.yaml", "OpenAPI contract")
	goOutput := flag.String("go-output", "internal/contract/generated.go", "generated Go output")
	tsOutput := flag.String("ts-output", "../../apps/console/src/lib/console-gateway.ts", "generated TypeScript output")
	flag.Parse()
	source, err := os.ReadFile(*contractPath)
	if err != nil {
		fail(err)
	}
	var spec document
	if err := yaml.Unmarshal(source, &spec); err != nil {
		fail(err)
	}
	if len(spec.Servers) == 0 || !strings.HasSuffix(spec.Servers[0].URL, "/api/v1") {
		fail(fmt.Errorf("console gateway server must end with /api/v1"))
	}
	prefix := "/api/v1"
	routes := map[string]string{}
	for path, methods := range spec.Paths {
		for _, operation := range methods {
			routes[operation.OperationID] = prefix + path
		}
	}
	required := []string{"getConsoleGatewayHealth", "beginConsoleLogin", "completeConsoleLogin", "getConsoleSession", "logoutConsoleSession"}
	for _, operationID := range required {
		if routes[operationID] == "" {
			fail(fmt.Errorf("required operation %s is missing", operationID))
		}
	}
	digest := fmt.Sprintf("%x", sha256.Sum256(source))
	goSource := fmt.Sprintf(`// Code generated by cmd/contractgen from console-gateway.yaml; DO NOT EDIT.
package contract

const (
	HealthRoute = %q
	LoginRoute = %q
	CallbackRoute = %q
	SessionRoute = %q
	LogoutRoute = %q
	SourceSHA256 = %q
)
`, routes["getConsoleGatewayHealth"], routes["beginConsoleLogin"], routes["completeConsoleLogin"], routes["getConsoleSession"], routes["logoutConsoleSession"], digest)
	formatted, err := format.Source([]byte(goSource))
	if err != nil {
		fail(err)
	}
	write(*goOutput, formatted)
	write(*tsOutput, []byte(strings.ReplaceAll(tsTemplate, "{{SHA}}", digest)))
}

func write(path string, content []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }

const tsTemplate = `// Code generated from console-gateway.yaml (SHA256 {{SHA}}); DO NOT EDIT.
export interface ConsoleScope {
  kind: "platform";
}

export interface ConsoleAccessContext {
  permissions: string[];
  scopes: ConsoleScope[];
  verified_at: string;
}

export interface ConsoleSession {
  user: { id: string };
  access_context: ConsoleAccessContext;
  expires_at: string;
}

interface SuccessEnvelope<T> {
  data: T;
  request_id: string;
}

export type ConsoleSessionResult =
  | { state: "authenticated"; session: ConsoleSession }
  | { state: "signed_out" | "denied" | "unavailable" };

export async function fetchConsoleSession(): Promise<ConsoleSessionResult> {
  try {
    const response = await fetch("/api/v1/session", { credentials: "same-origin", headers: { Accept: "application/json" } });
    if (response.status === 401) return { state: "signed_out" };
    if (response.status === 403) return { state: "denied" };
    if (!response.ok) return { state: "unavailable" };
    const envelope = (await response.json()) as SuccessEnvelope<ConsoleSession>;
    if (!isConsoleSession(envelope.data)) return { state: "unavailable" };
    return { state: "authenticated", session: envelope.data };
  } catch {
    return { state: "unavailable" };
  }
}

function isConsoleSession(value: unknown): value is ConsoleSession {
  if (!value || typeof value !== "object") return false;
  const candidate = value as Partial<ConsoleSession>;
  return Boolean(
    candidate.user?.id &&
      candidate.access_context &&
      Array.isArray(candidate.access_context.permissions) &&
      Array.isArray(candidate.access_context.scopes) &&
      candidate.access_context.permissions.every((permission) => typeof permission === "string") &&
      candidate.access_context.scopes.every((scope) => scope?.kind === "platform") &&
      typeof candidate.access_context.verified_at === "string" &&
      typeof candidate.expires_at === "string",
  );
}

export async function logoutConsoleSession(): Promise<void> {
  const response = await fetch("/api/v1/session/logout", { method: "POST", credentials: "same-origin" });
  if (!response.ok) throw new Error("Console logout failed");
}

export function consoleLoginHref(): string {
  const returnTo = window.location.pathname + window.location.search + window.location.hash;
  return "/api/v1/auth/login?return_to=" + encodeURIComponent(returnTo);
}
`
