package main

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/google/uuid"
	"gopkg.in/yaml.v3"
)

type schema struct {
	Ref                  string            `yaml:"$ref"`
	Type                 string            `yaml:"type"`
	Format               string            `yaml:"format"`
	Const                any               `yaml:"const"`
	Enum                 []string          `yaml:"enum"`
	MinItems             int               `yaml:"minItems"`
	MaxItems             int               `yaml:"maxItems"`
	MaxLength            int               `yaml:"maxLength"`
	Required             []string          `yaml:"required"`
	Properties           map[string]schema `yaml:"properties"`
	Items                *schema           `yaml:"items"`
	AdditionalProperties *bool             `yaml:"additionalProperties"`
	Example              any               `yaml:"example"`
	InvalidExample       any               `yaml:"x-invalid-example"`
}

type document struct {
	Servers []struct {
		URL string `yaml:"url"`
	} `yaml:"servers"`
	Paths map[string]map[string]struct {
		OperationID string `yaml:"operationId"`
	} `yaml:"paths"`
	Components struct {
		Schemas map[string]schema `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	contractPath := flag.String("contract", "../../packages/api-contracts/openapi/console-gateway.yaml", "OpenAPI contract")
	goOutput := flag.String("go-output", "internal/contract/generated.go", "generated Go output")
	tsOutput := flag.String("ts-output", "../../apps/console/src/lib/console-gateway.ts", "generated TypeScript output")
	flag.Parse()
	source, err := os.ReadFile(*contractPath)
	if err != nil {
		fail(err)
	}
	var spec document
	if err := yaml.Unmarshal(source, &spec); err != nil {
		fail(err)
	}
	if len(spec.Servers) == 0 || !strings.HasSuffix(spec.Servers[0].URL, "/api/v1") {
		fail(errors.New("console gateway server must end with /api/v1"))
	}
	routes := operationRoutes(spec)
	for _, operationID := range []string{"getConsoleGatewayHealth", "beginConsoleLogin", "completeConsoleLogin", "getConsoleSession", "getConsoleOverview", "logoutConsoleSession"} {
		if routes[operationID] == "" {
			fail(fmt.Errorf("required operation %s is missing", operationID))
		}
	}
	sessionSchema, ok := spec.Components.Schemas["ConsoleSession"]
	if !ok || sessionSchema.Example == nil || sessionSchema.InvalidExample == nil {
		fail(errors.New("ConsoleSession requires example and x-invalid-example"))
	}
	if err := validateSchema(sessionSchema, sessionSchema.Example, spec.Components.Schemas); err != nil {
		fail(fmt.Errorf("ConsoleSession example is invalid: %w", err))
	}
	if err := validateSchema(sessionSchema, sessionSchema.InvalidExample, spec.Components.Schemas); err == nil {
		fail(errors.New("ConsoleSession x-invalid-example unexpectedly satisfies the schema"))
	}
	overviewSchema, ok := spec.Components.Schemas["ConsoleOverview"]
	if !ok || overviewSchema.Example == nil || overviewSchema.InvalidExample == nil {
		fail(errors.New("ConsoleOverview requires example and x-invalid-example"))
	}
	if err := validateSchema(overviewSchema, overviewSchema.Example, spec.Components.Schemas); err != nil {
		fail(fmt.Errorf("ConsoleOverview example is invalid: %w", err))
	}
	if err := validateSchema(overviewSchema, overviewSchema.InvalidExample, spec.Components.Schemas); err == nil {
		fail(errors.New("ConsoleOverview x-invalid-example unexpectedly satisfies the schema"))
	}

	digest := fmt.Sprintf("%x", sha256.Sum256(source))
	goSource := renderGo(spec, routes, digest)
	formatted, err := format.Source([]byte(goSource))
	if err != nil {
		fail(fmt.Errorf("format generated Go: %w\n%s", err, goSource))
	}
	write(*goOutput, formatted)
	write(*tsOutput, []byte(renderTypeScript(spec, routes, digest)))
}

func operationRoutes(spec document) map[string]string {
	routes := map[string]string{}
	for path, methods := range spec.Paths {
		for _, operation := range methods {
			routes[operation.OperationID] = "/api/v1" + path
		}
	}
	return routes
}

func schemaNames(spec document) []string {
	names := make([]string, 0, len(spec.Components.Schemas))
	for name := range spec.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func renderGo(spec document, routes map[string]string, digest string) string {
	var output strings.Builder
	fmt.Fprintf(&output, `// Code generated by cmd/contractgen from console-gateway.yaml; DO NOT EDIT.
package contract

import "time"

const (
	HealthRoute = %q
	LoginRoute = %q
	CallbackRoute = %q
	SessionRoute = %q
	OverviewRoute = %q
	LogoutRoute = %q
	SourceSHA256 = %q
)

`, routes["getConsoleGatewayHealth"], routes["beginConsoleLogin"], routes["completeConsoleLogin"], routes["getConsoleSession"], routes["getConsoleOverview"], routes["logoutConsoleSession"], digest)
	for _, name := range schemaNames(spec) {
		fmt.Fprintf(&output, "type %s %s\n\n", name, goType(spec.Components.Schemas[name], 0))
	}
	return output.String()
}

func goType(value schema, indent int) string {
	if value.Ref != "" {
		return refName(value.Ref)
	}
	switch value.Type {
	case "string":
		if value.Format == "date-time" {
			return "time.Time"
		}
		return "string"
	case "boolean":
		return "bool"
	case "array":
		if value.Items == nil {
			return "[]any"
		}
		return "[]" + goType(*value.Items, indent)
	case "object":
		var output strings.Builder
		output.WriteString("struct {\n")
		required := stringSet(value.Required)
		for _, property := range sortedProperties(value.Properties) {
			fieldType := goType(value.Properties[property], indent+1)
			tag := property
			if !required[property] {
				fieldType = "*" + fieldType
				tag += ",omitempty"
			}
			fmt.Fprintf(&output, "%s%s %s `json:\"%s\"`\n", strings.Repeat("\t", indent+1), goName(property), fieldType, tag)
		}
		output.WriteString(strings.Repeat("\t", indent) + "}")
		return output.String()
	default:
		return "any"
	}
}

func renderTypeScript(spec document, routes map[string]string, digest string) string {
	var schemas strings.Builder
	var validators strings.Builder
	for _, name := range schemaNames(spec) {
		value := spec.Components.Schemas[name]
		fmt.Fprintf(&schemas, "export interface %s %s\n\n", name, tsObject(value))
		fmt.Fprintf(&validators, "function is%s(value: unknown): value is %s {\n  return %s;\n}\n\n", name, name, tsCheck("value", value))
	}
	template := `// Code generated from console-gateway.yaml (SHA256 {{SHA}}); DO NOT EDIT.
{{SCHEMAS}}function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function isUUID(value: unknown): value is string {
  return typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

function isDateTime(value: unknown): value is string {
  return typeof value === "string" && !Number.isNaN(Date.parse(value));
}

{{VALIDATORS}}export type ConsoleSessionResult =
  | { state: "authenticated"; session: ConsoleSession }
  | { state: "signed_out" | "denied" | "unavailable" };

export async function fetchConsoleSession(): Promise<ConsoleSessionResult> {
  try {
    const response = await fetch("{{SESSION_ROUTE}}", { credentials: "same-origin", headers: { Accept: "application/json" } });
    if (response.status === 401) return { state: "signed_out" };
    if (response.status === 403) return { state: "denied" };
    if (!response.ok) return { state: "unavailable" };
    const envelope: unknown = await response.json();
    if (!isSuccessEnvelope(envelope) || !isConsoleSession(envelope.data)) return { state: "unavailable" };
    return { state: "authenticated", session: envelope.data };
  } catch {
    return { state: "unavailable" };
  }
}

export async function fetchConsoleOverview(): Promise<ConsoleOverview> {
  const response = await fetch("{{OVERVIEW_ROUTE}}", { credentials: "same-origin", headers: { Accept: "application/json" } });
  if (!response.ok) throw new Error("Console overview failed");
  const envelope: unknown = await response.json();
  if (!isSuccessEnvelope(envelope) || !isConsoleOverview(envelope.data)) throw new Error("Console overview contract mismatch");
  return envelope.data;
}

export async function logoutConsoleSession(): Promise<void> {
  const response = await fetch("{{LOGOUT_ROUTE}}", { method: "POST", credentials: "same-origin" });
  if (!response.ok) throw new Error("Console logout failed");
}

export function consoleLoginHref(): string {
  const returnTo = window.location.pathname + window.location.search + window.location.hash;
  return "{{LOGIN_ROUTE}}?return_to=" + encodeURIComponent(returnTo);
}
`
	replacements := map[string]string{
		"{{SHA}}": digest, "{{SCHEMAS}}": schemas.String(), "{{VALIDATORS}}": validators.String(),
		"{{SESSION_ROUTE}}": routes["getConsoleSession"], "{{OVERVIEW_ROUTE}}": routes["getConsoleOverview"], "{{LOGOUT_ROUTE}}": routes["logoutConsoleSession"], "{{LOGIN_ROUTE}}": routes["beginConsoleLogin"],
	}
	for old, replacement := range replacements {
		template = strings.ReplaceAll(template, old, replacement)
	}
	return template
}

func tsObject(value schema) string {
	if value.Type != "object" {
		return tsType(value)
	}
	required := stringSet(value.Required)
	var output strings.Builder
	output.WriteString("{\n")
	for _, property := range sortedProperties(value.Properties) {
		optional := ""
		if !required[property] {
			optional = "?"
		}
		fmt.Fprintf(&output, "  %s%s: %s;\n", property, optional, tsType(value.Properties[property]))
	}
	output.WriteString("}")
	return output.String()
}

func tsType(value schema) string {
	if value.Ref != "" {
		return refName(value.Ref)
	}
	switch value.Type {
	case "string":
		if len(value.Enum) > 0 {
			encoded := make([]string, 0, len(value.Enum))
			for _, item := range value.Enum {
				quoted, _ := json.Marshal(item)
				encoded = append(encoded, string(quoted))
			}
			return strings.Join(encoded, " | ")
		}
		if literal, ok := value.Const.(string); ok {
			encoded, _ := json.Marshal(literal)
			return string(encoded)
		}
		return "string"
	case "boolean":
		return "boolean"
	case "array":
		if value.Items == nil {
			return "unknown[]"
		}
		return "Array<" + tsType(*value.Items) + ">"
	case "object":
		return tsObject(value)
	default:
		return "unknown"
	}
}

func tsCheck(expression string, value schema) string {
	if value.Ref != "" {
		return "is" + refName(value.Ref) + "(" + expression + ")"
	}
	switch value.Type {
	case "string":
		if len(value.Enum) > 0 {
			encoded, _ := json.Marshal(value.Enum)
			return "typeof " + expression + ` === "string" && ` + string(encoded) + ".includes(" + expression + ")"
		}
		if literal, ok := value.Const.(string); ok {
			encoded, _ := json.Marshal(literal)
			return expression + " === " + string(encoded)
		}
		if value.Format == "uuid" {
			return "isUUID(" + expression + ")"
		}
		if value.Format == "date-time" {
			return "isDateTime(" + expression + ")"
		}
		check := "typeof " + expression + ` === "string"`
		if value.MaxLength > 0 {
			check += fmt.Sprintf(" && %s.length <= %d", expression, value.MaxLength)
		}
		return check
	case "boolean":
		return "typeof " + expression + ` === "boolean"`
	case "array":
		if value.Items == nil {
			return "Array.isArray(" + expression + ")"
		}
		checks := []string{"Array.isArray(" + expression + ")"}
		if value.MinItems > 0 {
			checks = append(checks, fmt.Sprintf("%s.length >= %d", expression, value.MinItems))
		}
		if value.MaxItems > 0 {
			checks = append(checks, fmt.Sprintf("%s.length <= %d", expression, value.MaxItems))
		}
		checks = append(checks, expression+".every((item) => "+tsCheck("item", *value.Items)+")")
		return strings.Join(checks, " && ")
	case "object":
		checks := []string{"isRecord(" + expression + ")"}
		required := stringSet(value.Required)
		for _, property := range sortedProperties(value.Properties) {
			propertyExpression := expression + "[" + strconvQuote(property) + "]"
			check := tsCheck(propertyExpression, value.Properties[property])
			if required[property] {
				checks = append(checks, strconvQuote(property)+" in "+expression+" && "+check)
			} else {
				checks = append(checks, "(!("+strconvQuote(property)+" in "+expression+") || "+check+")")
			}
		}
		if value.AdditionalProperties != nil && !*value.AdditionalProperties {
			allowed, _ := json.Marshal(sortedProperties(value.Properties))
			checks = append(checks, "Object.keys("+expression+").every((key) => "+string(allowed)+".includes(key))")
		}
		return strings.Join(checks, " && ")
	default:
		return "true"
	}
}

func validateSchema(value schema, candidate any, schemas map[string]schema) error {
	if value.Ref != "" {
		referenced, ok := schemas[refName(value.Ref)]
		if !ok {
			return fmt.Errorf("unknown schema reference %s", value.Ref)
		}
		return validateSchema(referenced, candidate, schemas)
	}
	switch value.Type {
	case "string":
		text, ok := candidate.(string)
		if !ok {
			return errors.New("expected string")
		}
		if literal, ok := value.Const.(string); ok && text != literal {
			return fmt.Errorf("expected constant %q", literal)
		}
		if len(value.Enum) > 0 && !stringSet(value.Enum)[text] {
			return fmt.Errorf("value %q is outside enum", text)
		}
		if value.Format == "uuid" {
			_, err := uuid.Parse(text)
			return err
		}
		if value.Format == "date-time" {
			_, err := time.Parse(time.RFC3339, text)
			return err
		}
		if value.MaxLength > 0 && len([]rune(text)) > value.MaxLength {
			return fmt.Errorf("string exceeds %d characters", value.MaxLength)
		}
	case "boolean":
		if _, ok := candidate.(bool); !ok {
			return errors.New("expected boolean")
		}
	case "array":
		items, ok := candidate.([]any)
		if !ok {
			return errors.New("expected array")
		}
		if value.MinItems > 0 && len(items) < value.MinItems {
			return fmt.Errorf("expected at least %d items", value.MinItems)
		}
		if value.MaxItems > 0 && len(items) > value.MaxItems {
			return fmt.Errorf("expected at most %d items", value.MaxItems)
		}
		if value.Items != nil {
			for _, item := range items {
				if err := validateSchema(*value.Items, item, schemas); err != nil {
					return err
				}
			}
		}
	case "object":
		object, ok := candidate.(map[string]any)
		if !ok {
			return errors.New("expected object")
		}
		for _, required := range value.Required {
			if _, exists := object[required]; !exists {
				return fmt.Errorf("missing required property %s", required)
			}
		}
		for property, child := range object {
			propertySchema, exists := value.Properties[property]
			if !exists {
				if value.AdditionalProperties != nil && !*value.AdditionalProperties {
					return fmt.Errorf("unexpected property %s", property)
				}
				continue
			}
			if err := validateSchema(propertySchema, child, schemas); err != nil {
				return fmt.Errorf("property %s: %w", property, err)
			}
		}
	}
	return nil
}

func sortedProperties(properties map[string]schema) []string {
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func stringSet(values []string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}

func refName(ref string) string { return ref[strings.LastIndex(ref, "/")+1:] }

func goName(value string) string {
	var output []rune
	upper := true
	for _, char := range value {
		if char == '_' || char == '-' {
			upper = true
			continue
		}
		if upper {
			char = unicode.ToUpper(char)
			upper = false
		}
		output = append(output, char)
	}
	if string(output) == "Id" {
		return "ID"
	}
	return strings.ReplaceAll(string(output), "Id", "ID")
}

func strconvQuote(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func write(path string, content []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
