FROM docker.m.daocloud.io/library/golang:1.26.6-alpine AS build
RUN apk add --no-cache git ca-certificates
ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /src
COPY go.mod go.sum ./
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 /usr/local/go/bin/go build -trimpath -ldflags="-s -w" -o /out/platform-mail-worker ./cmd/mail-worker

FROM docker.m.daocloud.io/library/alpine:3.22
RUN addgroup -S platform && adduser -S -G platform platform
COPY --from=build /out/platform-mail-worker /usr/local/bin/platform-mail-worker
USER platform
ENTRYPOINT ["platform-mail-worker"]
