package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

type document struct {
	Paths      map[string]pathItem `yaml:"paths"`
	Components struct {
		Schemas map[string]*schema `yaml:"schemas"`
	} `yaml:"components"`
}

type pathItem struct {
	Get  *operation `yaml:"get"`
	Post *operation `yaml:"post"`
}

type operation struct {
	OperationID string                 `yaml:"operationId"`
	Security    []map[string][]string  `yaml:"security"`
	Parameters  []reference            `yaml:"parameters"`
	RequestBody requestBody            `yaml:"requestBody"`
	Responses   map[string]apiResponse `yaml:"responses"`
}

type reference struct {
	Ref string `yaml:"$ref"`
}
type requestBody struct {
	Required bool                 `yaml:"required"`
	Content  map[string]mediaType `yaml:"content"`
}
type apiResponse struct {
	Content map[string]mediaType `yaml:"content"`
}
type mediaType struct {
	Schema *schema `yaml:"schema"`
}
type schema struct {
	Ref        string             `yaml:"$ref"`
	Type       any                `yaml:"type"`
	Format     string             `yaml:"format"`
	Required   []string           `yaml:"required"`
	Properties map[string]*schema `yaml:"properties"`
	AllOf      []*schema          `yaml:"allOf"`
}

func main() {
	contractPath := flag.String("contract", "../../packages/api-contracts/openapi/platform-core.yaml", "OpenAPI contract")
	outputPath := flag.String("output", "internal/contract/generated.go", "generated Go output")
	flag.Parse()
	source, err := os.ReadFile(*contractPath)
	if err != nil {
		fail(err)
	}
	var spec document
	if err := yaml.Unmarshal(source, &spec); err != nil {
		fail(fmt.Errorf("parse OpenAPI: %w", err))
	}
	authorizePath, authorize := findOperation(spec.Paths, "authorizeOAuthClient")
	tokenPath, token := findOperation(spec.Paths, "exchangeAuthorizationCode")
	if authorize == nil || token == nil {
		fail(fmt.Errorf("required authorization operations are missing"))
	}
	validateTokenOperation(token)
	requestSchema := token.RequestBody.Content["application/json"].Schema
	if requestSchema == nil {
		fail(fmt.Errorf("token request application/json schema is missing"))
	}
	userSchema := spec.Components.Schemas["PlatformUser"]
	if userSchema == nil {
		fail(fmt.Errorf("PlatformUser schema is missing"))
	}
	responseSchema := responseDataSchema(token.Responses["200"].Content["application/json"].Schema)
	if responseSchema == nil {
		fail(fmt.Errorf("token 200 response data schema is missing"))
	}
	digest := sha256.Sum256(source)
	generated := fmt.Sprintf(`// Code generated by cmd/contractgen from platform-core.yaml; DO NOT EDIT.
package contract

import "time"

const (
	AuthorizeRoute = %q
	TokenRoute = %q
	SourceSHA256 = %q
)

%s

%s

%s
`, authorizePath, tokenPath, fmt.Sprintf("%x", digest), renderStruct("ExchangeAuthorizationCodeRequest", requestSchema), renderStruct("PlatformUser", userSchema), renderStruct("ExchangeAuthorizationCodeResponse", responseSchema))
	formatted, err := format.Source([]byte(generated))
	if err != nil {
		fail(fmt.Errorf("format generated contract: %w", err))
	}
	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fail(err)
	}
}

func findOperation(paths map[string]pathItem, operationID string) (string, *operation) {
	for path, item := range paths {
		for _, operation := range []*operation{item.Get, item.Post} {
			if operation != nil && operation.OperationID == operationID {
				return "/api/v1" + path, operation
			}
		}
	}
	return "", nil
}

func validateTokenOperation(operation *operation) {
	validSecurity := false
	for _, requirement := range operation.Security {
		_, basic := requirement["clientSecret"]
		_, hmac := requirement["serviceHmac"]
		validSecurity = validSecurity || basic && hmac
	}
	if !validSecurity {
		fail(fmt.Errorf("token operation must require clientSecret and serviceHmac together"))
	}
	requiredParameters := map[string]bool{
		"#/components/parameters/RequiredIdempotencyKey": false,
		"#/components/parameters/ServiceId":              false, "#/components/parameters/KeyId": false,
		"#/components/parameters/Timestamp": false, "#/components/parameters/Nonce": false,
	}
	for _, parameter := range operation.Parameters {
		if _, ok := requiredParameters[parameter.Ref]; ok {
			requiredParameters[parameter.Ref] = true
		}
	}
	for parameter, present := range requiredParameters {
		if !present {
			fail(fmt.Errorf("token operation is missing %s", parameter))
		}
	}
	if !operation.RequestBody.Required {
		fail(fmt.Errorf("token request body must be required"))
	}
}

func responseDataSchema(root *schema) *schema {
	if root == nil {
		return nil
	}
	for _, member := range root.AllOf {
		if data := member.Properties["data"]; data != nil {
			return data
		}
	}
	return root.Properties["data"]
}

func renderStruct(name string, value *schema) string {
	if value == nil {
		fail(fmt.Errorf("cannot generate %s from an empty schema", name))
	}
	fields := append([]string(nil), value.Required...)
	required := make(map[string]bool, len(fields))
	for _, field := range fields {
		required[field] = true
	}
	var optional []string
	for field := range value.Properties {
		if !required[field] {
			optional = append(optional, field)
		}
	}
	sort.Strings(optional)
	fields = append(fields, optional...)
	var output strings.Builder
	fmt.Fprintf(&output, "type %s struct {\n", name)
	for _, field := range fields {
		property := value.Properties[field]
		if property == nil {
			fail(fmt.Errorf("%s requires missing property %s", name, field))
		}
		goType := schemaType(property)
		if !required[field] {
			goType = "*" + goType
		}
		fmt.Fprintf(&output, "\t%s %s `json:\"%s\"`\n", goName(field), goType, field)
	}
	output.WriteString("}\n")
	return output.String()
}

func schemaType(value *schema) string {
	if value.Ref != "" {
		parts := strings.Split(value.Ref, "/")
		return parts[len(parts)-1]
	}
	typeName, _ := value.Type.(string)
	if typeName == "string" && value.Format == "date-time" {
		return "time.Time"
	}
	switch typeName {
	case "string":
		return "string"
	case "boolean":
		return "bool"
	case "integer":
		return "int"
	default:
		fail(fmt.Errorf("unsupported generated schema type %v", value.Type))
		return ""
	}
}

func goName(value string) string {
	parts := strings.Split(value, "_")
	for index, part := range parts {
		switch strings.ToLower(part) {
		case "id":
			parts[index] = "ID"
			continue
		case "uri":
			parts[index] = "URI"
			continue
		case "url":
			parts[index] = "URL"
			continue
		}
		runes := []rune(part)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}

func fail(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
