# Auto generated by LangBot Plugin SDK, then implemented as sales guard.
from __future__ import annotations

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import context, events
from langbot_plugin.api.entities.builtin.platform.message import Image, MessageChain, Plain

from final_review_sales.constants import COMMAND_PREFIXES, SALES_KEYWORDS
from final_review_sales.services.runtime import sales_flow


def _identity(event) -> dict[str, str | None]:
    launcher_type = str(getattr(event, "launcher_type", ""))
    return {
        "chatPlatform": "langbot",
        "chatUserId": str(getattr(event, "sender_id", "") or getattr(event, "launcher_id", "")),
        "chatGroupId": str(getattr(event, "launcher_id", "")) if launcher_type == "group" else None,
    }


async def _reply(ctx: context.EventContext, text: str, image_path=None) -> None:
    chain = MessageChain([Plain(text=text)])
    if image_path:
        chain.append(Image(path=str(image_path)))
    await ctx.reply(chain, quote_origin=True)


def _parse_prefixed_message(text: str) -> tuple[str, list[str]] | None:
    stripped = text.strip()
    for prefix in COMMAND_PREFIXES:
        if stripped == prefix:
            return prefix, []
        if stripped.startswith(prefix + " "):
            return prefix, stripped[len(prefix):].strip().split()
    return None


class DefaultEventListener(EventListener):
    async def initialize(self):
        await super().initialize()

        @self.handler(events.PersonCommandSent)
        async def person_command(ctx: context.EventContext):
            event = ctx.event
            command = str(event.command)
            command = command if command.startswith("!") else f"!{command}"
            if command not in COMMAND_PREFIXES:
                return
            text, image = await sales_flow.handle_command_alias(command, list(event.params), _identity(event))
            await _reply(ctx, text, image)
            ctx.prevent_default()

        @self.handler(events.GroupCommandSent)
        async def group_command(ctx: context.EventContext):
            event = ctx.event
            command = str(event.command)
            command = command if command.startswith("!") else f"!{command}"
            if command not in COMMAND_PREFIXES:
                return
            text, image = await sales_flow.handle_command_alias(command, list(event.params), _identity(event))
            await _reply(ctx, text, image)
            ctx.prevent_default()

        @self.handler(events.PersonNormalMessageReceived)
        async def person_normal(ctx: context.EventContext):
            event = ctx.event
            parsed = _parse_prefixed_message(event.text_message)
            if parsed:
                command, args = parsed
                text, image = await sales_flow.handle_command_alias(command, args, _identity(event))
                await _reply(ctx, text, image)
                ctx.prevent_default()
                return

            if "支付了" in event.text_message:
                await _reply(ctx, "可以发送 !订单 查询支付状态；支付成功后我会按后端状态发货。")
            elif "没收到" in event.text_message:
                await _reply(ctx, "如果已支付成功，请发送 !重发 <订单号> 重发下载入口。")

        @self.handler(events.GroupNormalMessageReceived)
        async def group_normal(ctx: context.EventContext):
            event = ctx.event
            parsed = _parse_prefixed_message(event.text_message)
            if parsed:
                command, args = parsed
                text, image = await sales_flow.handle_command_alias(command, args, _identity(event))
                await _reply(ctx, text, image)
                ctx.prevent_default()
                return

            if any(keyword in event.text_message for keyword in SALES_KEYWORDS):
                await _reply(ctx, "需要查询资料可以发送：!资料 课程名；购买请发送：!购买 课程名。群聊不会发送 paid PDF。")
