// Package foodclient is food-mcp's private client for the Food Post owner. It
// mirrors the portal-gateway foodposts contract (five-line signing, envelope
// unwrap, verbatim error passthrough) without depending on that service's
// internal packages. Create uses the food-post-create credential ring; reads
// use the independent food-post-read ring.
package foodclient

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"henukit.dev/food-mcp/internal/signing"
)

const (
	postsPath   = "/api/v1/food/posts"
	minePath    = "/api/v1/food/posts/mine"
	venuesPath  = "/api/v1/food/venues"
	maxBodySize = 20 << 20
)

// UpstreamError carries a non-2xx Food response so tool handlers can present
// the exact error code (e.g. DAILY_POST_CAP_REACHED) to the model.
type UpstreamError struct {
	StatusCode int
	Code       string
	Message    string
	RequestID  string
}

func (e *UpstreamError) Error() string {
	return fmt.Sprintf("Food responded %d %s: %s", e.StatusCode, e.Code, e.Message)
}

// ErrUnavailable wraps transport-level failures (Food down, unconfigured).
var ErrUnavailable = errors.New("Food service is unavailable")

// ErrInvalidResponse wraps a response that is not a usable Food envelope.
var ErrInvalidResponse = errors.New("Food returned an invalid response")

// Client talks to services/food over its signed HTTP contract.
type Client struct {
	baseURL      string
	httpClient   *http.Client
	createSigner *signing.Signer
	readSigner   *signing.Signer
}

// NewClient validates the base URL and both credential triples. food-mcp
// exposes create and read tools in the same remote service, so a partially
// configured ring must fail startup rather than leaving individual tools to
// fail later. Public deployment placeholders are rejected at this remote
// boundary so copying an example Compose value cannot become working auth.
func NewClient(baseURL, createClientID, createSecret, createKeyID, readClientID, readSecret, readKeyID string) (*Client, error) {
	parsed, err := url.Parse(strings.TrimSpace(baseURL))
	if err != nil || parsed.Scheme == "" || parsed.Host == "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" || (parsed.Scheme != "http" && parsed.Scheme != "https") {
		return nil, errors.New("invalid Food client configuration")
	}
	if err := validateCredential("create", createClientID, createSecret, createKeyID); err != nil {
		return nil, err
	}
	if err := validateCredential("read", readClientID, readSecret, readKeyID); err != nil {
		return nil, err
	}
	return &Client{
		baseURL:      strings.TrimRight(parsed.String(), "/"),
		httpClient:   &http.Client{Timeout: 15 * time.Second},
		createSigner: signing.NewSigner(strings.TrimSpace(createClientID), createSecret, strings.TrimSpace(createKeyID)),
		readSigner:   signing.NewSigner(strings.TrimSpace(readClientID), readSecret, strings.TrimSpace(readKeyID)),
	}, nil
}

func validateCredential(name, clientID, secret, keyID string) error {
	if strings.TrimSpace(clientID) == "" || secret == "" || strings.TrimSpace(keyID) == "" {
		return fmt.Errorf("Food %s credential is incomplete", name)
	}
	if len(secret) < 32 || isPlaceholderSecret(secret) {
		return fmt.Errorf("Food %s credential secret is not deployment-safe", name)
	}
	return nil
}

func isPlaceholderSecret(secret string) bool {
	value := strings.ToLower(strings.TrimSpace(secret))
	return strings.HasPrefix(value, "replace-") ||
		strings.HasPrefix(value, "change-me") ||
		strings.HasPrefix(value, "example-") ||
		strings.Contains(value, "placeholder")
}

// CreatePost submits one signed-in actor's create command and returns the
// unwrapped {post, request_id} payload. The idempotency key is generated by
// the caller so retries can reuse it.
func (c *Client) CreatePost(ctx context.Context, actorUserID, actorDisplayName, idempotencyKey string, input any) (map[string]any, error) {
	body, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("encode Food post input: %w", err)
	}
	data, err := c.call(ctx, http.MethodPost, postsPath, c.createSigner, actorUserID, actorDisplayName, idempotencyKey, body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

// ListPosts returns the public post list, optionally campus-filtered.
func (c *Client) ListPosts(ctx context.Context, campus string) (map[string]any, error) {
	path := postsPath
	if campus != "" {
		path += "?campus=" + url.QueryEscape(campus)
	}
	return c.read(ctx, path)
}

// MyPosts returns the signed-in actor's own posts.
func (c *Client) MyPosts(ctx context.Context, actorUserID string) (map[string]any, error) {
	return c.read(ctx, minePath, withActor(actorUserID))
}

// Post returns one public post detail.
func (c *Client) Post(ctx context.Context, postID string) (map[string]any, error) {
	return c.read(ctx, postsPath+"/"+url.PathEscape(postID))
}

// Venues returns the venue summary for one campus.
func (c *Client) Venues(ctx context.Context, campus string) (map[string]any, error) {
	return c.read(ctx, venuesPath+"?campus="+url.QueryEscape(campus))
}

func (c *Client) read(ctx context.Context, path string, options ...func(*http.Request)) (map[string]any, error) {
	return c.call(ctx, http.MethodGet, path, c.readSigner, "", "", "", nil, options...)
}

func withActor(actorUserID string) func(*http.Request) {
	return func(request *http.Request) {
		request.Header.Set("X-Actor-User-Id", actorUserID)
	}
}

func (c *Client) call(ctx context.Context, method, path string, signer *signing.Signer, actorUserID, actorDisplayName, idempotencyKey string, body []byte, options ...func(*http.Request)) (map[string]any, error) {
	if c == nil || c.baseURL == "" || signer == nil {
		return nil, ErrUnavailable
	}
	var reader io.Reader
	if body != nil {
		reader = bytes.NewReader(body)
	}
	request, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, reader)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUnavailable, err)
	}
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	if actorUserID != "" {
		request.Header.Set("X-Actor-User-Id", actorUserID)
	}
	if actorDisplayName != "" {
		request.Header.Set("X-Actor-Display-Name", actorDisplayName)
	}
	if idempotencyKey != "" {
		request.Header.Set("Idempotency-Key", idempotencyKey)
	}
	for _, option := range options {
		option(request)
	}
	if err := signer.Sign(request); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUnavailable, err)
	}
	response, err := c.httpClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUnavailable, err)
	}
	defer response.Body.Close()
	raw, err := io.ReadAll(io.LimitReader(response.Body, maxBodySize+1))
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUnavailable, err)
	}
	if len(raw) > maxBodySize {
		return nil, fmt.Errorf("%w: response exceeds the size limit", ErrInvalidResponse)
	}
	if response.StatusCode < 200 || response.StatusCode > 299 {
		return nil, parseUpstreamError(response.StatusCode, raw)
	}
	var envelope struct {
		Data      map[string]any `json:"data"`
		RequestID string         `json:"request_id"`
	}
	if err := json.Unmarshal(raw, &envelope); err != nil || envelope.Data == nil || envelope.RequestID == "" {
		return nil, fmt.Errorf("%w: missing data or request_id", ErrInvalidResponse)
	}
	envelope.Data["request_id"] = envelope.RequestID
	return envelope.Data, nil
}

func parseUpstreamError(status int, raw []byte) error {
	var envelope struct {
		Error     map[string]string `json:"error"`
		RequestID string            `json:"request_id"`
	}
	_ = json.Unmarshal(raw, &envelope)
	code := envelope.Error["code"]
	message := envelope.Error["message"]
	if code == "" {
		code = "UNKNOWN"
	}
	if message == "" {
		message = strconv.Itoa(status)
	}
	return &UpstreamError{StatusCode: status, Code: code, Message: message, RequestID: envelope.RequestID}
}
