# Auto generated by LangBot Plugin SDK, then implemented for final-review-platform.
from __future__ import annotations

import base64
from typing import AsyncGenerator

from langbot_plugin.api.definition.components.command.command import Command
from langbot_plugin.api.entities.builtin.command.context import CommandReturn, ExecuteContext

from final_review_sales.services.runtime import sales_flow


def _session_identity(context: ExecuteContext) -> dict[str, str | None]:
    launcher_type = getattr(context.session.launcher_type, "value", str(context.session.launcher_type))
    chat_group_id = str(context.session.launcher_id) if launcher_type == "group" else None
    chat_user_id = str(context.session.sender_id or context.session.launcher_id)
    return {
        "chatPlatform": "langbot",
        "chatUserId": chat_user_id,
        "chatGroupId": chat_group_id,
    }


async def _return_message(text: str, image_path=None) -> AsyncGenerator[CommandReturn, None]:
    if image_path:
        encoded = base64.b64encode(image_path.read_bytes()).decode("ascii")
        yield CommandReturn(text=text, image_base64=encoded)
        return
    yield CommandReturn(text=text)


class FinalReview(Command):
    async def initialize(self):
        await super().initialize()
        self.flow = sales_flow

        @self.subcommand("帮助", help="查看期末复习资料销售助手命令", usage="!final_review 帮助", aliases=["help"])
        async def help_command(_self, context: ExecuteContext):
            text, image = await self.flow.help()
            async for item in _return_message(text, image):
                yield item

        @self.subcommand("资料", help="查询课程资料包", usage="!final_review 资料 离散数学", aliases=["search"])
        async def search_command(_self, context: ExecuteContext):
            text, image = await self.flow.search(" ".join(context.crt_params), _session_identity(context))
            async for item in _return_message(text, image):
                yield item

        @self.subcommand("购买", help="创建微信 Native mock 订单", usage="!final_review 购买 离散数学", aliases=["buy"])
        async def buy_command(_self, context: ExecuteContext):
            text, image = await self.flow.purchase(" ".join(context.crt_params), _session_identity(context))
            async for item in _return_message(text, image):
                yield item

        @self.subcommand("订单", help="查询最近订单", usage="!final_review 订单", aliases=["orders"])
        async def orders_command(_self, context: ExecuteContext):
            text, image = await self.flow.recent_orders(_session_identity(context))
            async for item in _return_message(text, image):
                yield item

        @self.subcommand("重发", help="重发已支付订单下载入口", usage="!final_review 重发 ord_xxx", aliases=["resend"])
        async def resend_command(_self, context: ExecuteContext):
            order_id = context.crt_params[0] if context.crt_params else ""
            text, image = await self.flow.resend(order_id, _session_identity(context))
            async for item in _return_message(text, image):
                yield item

        @self.subcommand("*", help="默认帮助", usage="!final_review")
        async def fallback_command(_self, context: ExecuteContext):
            text, image = await self.flow.help()
            async for item in _return_message(text, image):
                yield item
